const crypto=require('crypto');
const UA='Mozilla/5.0 AppleWebKit/537.36 Chrome/140 Safari/537.36';
function J(res,s,o){res.statusCode=s;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(o))}
function N(v){return Number(String(v??'').replace(/[, %+원주]/g,''))||0}
function C(s){return String(s??'').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function tok(){return crypto.createHmac('sha256',process.env.AUTH_SECRET||'').update('theme-radar-permanent').digest('hex')}
function ok(req){let a=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');let b=tok();try{return a&&b&&a.length===b.length&&crypto.timingSafeEqual(Buffer.from(a),Buffer.from(b))}catch{return false}}
async function T(u){let c=new AbortController(),t=setTimeout(()=>c.abort(),9000);try{let r=await fetch(u,{headers:{'user-agent':UA,'accept-language':'ko-KR,ko;q=.9'},signal:c.signal,redirect:'follow'});if(!r.ok)throw Error('HTTP '+r.status);return await r.text()}finally{clearTimeout(t)}}
async function Q(u){return JSON.parse(await T(u))}
async function leaders(th){let out=[];for(const m of ['KOSPI','KOSDAQ']){try{let j=await Q('https://m.stock.naver.com/api/stocks/marketValue/'+m+'?page=1&pageSize=2000'),a=Array.isArray(j)?j:(j.stocks||j.result?.stocks||[]);for(const x of a){let r=N(x.fluctuationsRatio??x.fluctuationRate),code=String(x.itemCode||x.stockCode||'');if(r>=th&&/^\d{6}$/.test(code))out.push({code,name:C(x.stockName||x.itemName),market:m,rate:r,price:N(x.closePrice),volume:N(x.accumulatedTradingVolume)})}}catch{}}
 return out.sort((a,b)=>b.rate-a.rate).slice(0,30)}
async function quote(code){try{let x=await Q('https://m.stock.naver.com/api/stock/'+code+'/basic');return{code,name:C(x.stockName||x.itemName),rate:N(x.fluctuationsRatio??x.fluctuationRate),price:N(x.closePrice||x.currentPrice),volume:N(x.accumulatedTradingVolume||x.accumulatedVolume)}}catch{return{code,name:'',rate:0,price:0,volume:0}}}
async function hist(code){let x=await T('https://fchart.stock.naver.com/sise.nhn?symbol='+code+'&timeframe=day&count=520&requestType=0'),a=[],m,r=/data="(\d{8})\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)"/g;while((m=r.exec(x)))a.push({date:m[1],close:N(m[5]),volume:N(m[6])});return a}
async function inv(code){let h=await T('https://finance.naver.com/item/frgn.naver?code='+code+'&page=1'),a=[],m,r=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;while((m=r.exec(h))){let z=[],n,q=/<td[^>]*>([\s\S]*?)<\/td>/gi;while((n=q.exec(m[1])))z.push(C(n[1]));if(/^\d{4}\.\d{2}\.\d{2}$/.test(z[0]||''))a.push({date:z[0].replaceAll('.','-'),institution:N(z[5]),foreign:N(z[6])})}return a.slice(0,20)}
async function news(name){try{let x=await T('https://news.google.com/rss/search?q='+encodeURIComponent(name+' 주가 급등 수주 계약 정책')+'&hl=ko&gl=KR&ceid=KR:ko'),a=[],m,r=/<item>([\s\S]*?)<\/item>/gi;while((m=r.exec(x))&&a.length<5){let b=m[1],g=k=>C((b.match(new RegExp('<'+k+'>([\\s\\S]*?)<\\/'+k+'>','i'))||[])[1]||'');a.push({title:g('title'),link:g('link'),pubDate:g('pubDate')})}return a}catch{return[]}}
function links(h){let s=new Set(),m,r=/\/Theme\/ThemeDB\/ThemeAllAllowed\/(\d+)/g;while((m=r.exec(h)))s.add(m[1]);return[...s].slice(0,6)}
function themePage(h,id){let body=C(h),parts=body.split('인포스탁 국내 테마분류'),name='인포스탁 테마';if(parts[1]){let t=parts[1].replace(/^\s*목록\s*/,'').split(/테마 히스토리|관련 종목/)[0].trim();if(t&&t.length<80)name=t}let sec=body.includes('관련 종목')?body.split('관련 종목').slice(1).join('관련 종목'):body,a=[],seen=new Set(),m,r=/([가-힣A-Za-z0-9&·().+\- ]{1,35})\s*\((\d{6})\)/g;while((m=r.exec(sec))&&a.length<45)if(!seen.has(m[2])){seen.add(m[2]);a.push({name:C(m[1]),code:m[2]})}return{name,url:'https://infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed/'+id,members:a,body}}
async function leaderInfo(code,name){let nw=await news(name),ids=[];for(const u of ['https://infostock.co.kr/stockitem?code='+code,'https://infostock.co.kr/Company/Analysis/StockInfo?code='+code]){try{ids.push(...links(await T(u)))}catch{}}ids=[...new Set(ids)];if(!ids.length)try{ids=links((await T('https://search.naver.com/search.naver?where=web&query='+encodeURIComponent('site:infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed '+name))).replaceAll('&amp;','&'))}catch{}
 let th=[];for(const id of ids.slice(0,5))try{let p=themePage(await T('https://infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed/'+id),id);if(p.body.includes(name)||p.members.some(x=>x.code===code))th.push({name:p.name,url:p.url,members:p.members,source:'InfoStock'})}catch{}
 if(!th.length)th=[{name:infer(nw),url:'https://infostock.co.kr/Theme/ThemeDB',members:[{code,name}],source:'뉴스추론/InfoStock연결대기'}];return{news:nw,themes:th.slice(0,2)}}
function infer(n){let s=n.map(x=>x.title).join(' '),r=[['휴머노이드/로봇',/휴머노이드|협동로봇|로봇/i],['유리기판',/유리기판|글라스기판/i],['반도체/HBM',/HBM|반도체|PCB|FC-BGA/i],['전력설비/전선',/변압기|전력망|전선/i],['원전/SMR',/SMR|원전|원자력/i],['방산',/방산|방위산업|미사일/i],['2차전지',/2차전지|배터리|리튬/i],['바이오/제약',/FDA|임상|신약|바이오|제약/i],['보안',/보안|해킹|딥페이크/i],['AI/데이터센터',/AI|인공지능|데이터센터|GPU/i],['우주항공',/스페이스X|우주항공|위성/i],['자율주행',/자율주행|ADAS|라이다/i],['광통신',/광통신|광케이블|광섬유/i],['LNG/가스',/LNG|천연가스|가스관/i]];for(const x of r)if(x[1].test(s))return x[0];return'뉴스 연관 테마'}
module.exports=async(req,res)=>{let a=String(req.query.action||'leaders');if(a==='login'){if(req.method!=='POST')return J(res,405,{error:'POST only'});let b='';for await(const c of req)b+=c;let d={};try{d=JSON.parse(b)}catch{}let x=String(process.env.AUTH_CODE||''),y=String(d.code||''),z=false;try{z=x&&x.length===y.length&&crypto.timingSafeEqual(Buffer.from(x),Buffer.from(y))}catch{}return z?J(res,200,{token:tok()}):J(res,401,{error:'인증번호가 맞지 않습니다.'})}if(!ok(req))return J(res,401,{error:'인증 필요'});try{if(a==='leaders')return J(res,200,{leaders:await leaders(Math.max(5,Math.min(30,N(req.query.threshold)||10)))});if(a==='leader')return J(res,200,await leaderInfo(String(req.query.code),String(req.query.name||'')));if(a==='member'){let code=String(req.query.code),[q,h,i]=await Promise.all([quote(code),hist(code),inv(code).catch(()=>[])]);return J(res,200,{quote:q,hist:h,inv:i})}return J(res,404,{error:'unknown'})}catch(e){return J(res,500,{error:String(e.message||e)})}};
