const crypto=require('crypto');
const UA='Mozilla/5.0 AppleWebKit/537.36 Chrome/140 Safari/537.36';
const ACCESS_HASH=process.env.AUTH_CODE_HASH||'849d23da0efca8936bb6c0afb12200f47ce67b205a2077da72d318c52e48f309';
function J(res,s,o){res.statusCode=s;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(o))}
function N(v){return Number(String(v??'').replace(/[, %+원주]/g,''))||0}
function C(s){return String(s??'').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim()}
function validToken(v){try{return !!v&&crypto.createHash('sha256').update(String(v)).digest('hex')===ACCESS_HASH}catch{return false}}
function ok(req){let a=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'');return validToken(a)}
async function T(u,opt={}){let c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{let r=await fetch(u,{...opt,headers:{'user-agent':UA,'accept-language':'ko-KR,ko;q=.9',...(opt.headers||{})},signal:c.signal,redirect:'follow'});if(!r.ok)throw Error('HTTP '+r.status+' '+u);return await r.text()}finally{clearTimeout(t)}}
async function Q(u,opt){return JSON.parse(await T(u,opt))}
function kstNow(){let p=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false,weekday:'short'}).formatToParts(new Date()).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));return{date:p.year+'-'+p.month+'-'+p.day,hm:(+p.hour)*60+(+p.minute),weekday:p.weekday}}
function isoAdd(d,days){let x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+days);return x.toISOString().slice(0,10)}
function daysBetween(a,b){return Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000)}
async function naverMobileMarket(market){let j=await Q('https://m.stock.naver.com/api/stocks/marketValue/'+market+'?page=1&pageSize=2000');let a=Array.isArray(j)?j:(j.stocks||j.stockList||j.items||j.result?.stocks||j.result?.items||[]);return a.map(x=>({code:String(x.itemCode||x.stockCode||x.code||''),name:C(x.stockName||x.itemName||x.name),market,rate:N(x.fluctuationsRatio??x.fluctuationRate??x.changeRate??x.compareToPreviousPrice?.ratio),price:N(x.closePrice||x.currentPrice||x.price),volume:N(x.accumulatedTradingVolume||x.accumulatedVolume||x.volume)})).filter(x=>/^\d{6}$/.test(x.code))}
async function naverRisePage(sosok,page,market){let h=await T('https://finance.naver.com/sise/sise_rise.naver?sosok='+sosok+'&page='+page),out=[],m,r=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;while((m=r.exec(h))){let row=m[1],cm=row.match(/item\/main\.naver\?code=(\d{6})[^>]*>([\s\S]*?)<\/a>/i);if(!cm)continue;let pm=row.match(/([+-]?\d+(?:\.\d+)?)\s*%/),nums=[...row.matchAll(/<td[^>]*class="number"[^>]*>([\s\S]*?)<\/td>/gi)].map(x=>C(x[1]));let price=0;for(const z of nums){let v=N(z);if(v>0&&!String(z).includes('%')){price=v;break}}out.push({code:cm[1],name:C(cm[2]),market,rate:pm?N(pm[1]):0,price,volume:0})}return out}
async function naverCurrent(th){let rows=[];try{let ps=[];for(const [s,m] of [['0','KOSPI'],['1','KOSDAQ']])for(let p=1;p<=3;p++)ps.push(naverRisePage(s,p,m));rows=(await Promise.all(ps)).flat()}catch{}if(!rows.length){try{rows=(await Promise.all([naverMobileMarket('KOSPI'),naverMobileMarket('KOSDAQ')])).flat()}catch(e){throw Error('NAVER_CURRENT_FAILED: '+e.message)}}if(!rows.length)throw Error('NAVER_CURRENT_EMPTY');let map=new Map();for(const x of rows)if(!map.has(x.code)||map.get(x.code).rate<x.rate)map.set(x.code,x);return[...map.values()].filter(x=>x.rate>=th).sort((a,b)=>b.rate-a.rate).slice(0,60)}
const KRX_LOGIN_PAGE='https://data.krx.co.kr/contents/MDC/COMS/client/MDCCOMS001.cmd';
const KRX_LOGIN_JSP='https://data.krx.co.kr/contents/MDC/COMS/client/view/login.jsp?site=mdc';
const KRX_LOGIN_URL='https://data.krx.co.kr/contents/MDC/COMS/client/MDCCOMS001D1.cmd';
const krxCache=new Map();
function absorbCookies(jar,r){let a=[];try{a=r.headers.getSetCookie?r.headers.getSetCookie():[]}catch{}if(!a.length){let s=r.headers.get('set-cookie');if(s)a=[s]}for(const raw of a){let p=String(raw).split(';')[0],i=p.indexOf('=');if(i>0)jar.set(p.slice(0,i).trim(),p.slice(i+1).trim())}}
function cookieText(jar){return[...jar].map(([k,v])=>k+'='+v).join('; ')}
async function krxReq(url,opt={},jar=new Map()){let method=opt.method||'GET',body=opt.body,headers={...opt.headers};for(let i=0;i<5;i++){let r=await fetch(url,{method,body,headers:{'user-agent':UA,'accept-language':'ko-KR,ko;q=.9',...(cookieText(jar)?{cookie:cookieText(jar)}:{}),...headers},redirect:'manual'});absorbCookies(jar,r);if(r.status>=300&&r.status<400&&r.headers.get('location')){url=new URL(r.headers.get('location'),url).toString();if(r.status!==307&&r.status!==308){method='GET';body=undefined;headers={}}continue}return{r,text:await r.text(),jar}}throw Error('KRX_REDIRECT_LOOP')}
async function krxSession(id,pw,force=false){id=String(id||'').trim();pw=String(pw||'');if(!id||!pw)throw Error('KRX_LOGIN_REQUIRED: KRX 아이디와 비밀번호를 먼저 입력해 주세요.');let key=crypto.createHash('sha256').update(id+'\0'+pw).digest('hex'),hit=krxCache.get(key);if(!force&&hit&&hit.expires>Date.now())return hit.jar;let jar=new Map();await krxReq(KRX_LOGIN_PAGE,{},jar);await krxReq(KRX_LOGIN_JSP,{headers:{referer:KRX_LOGIN_PAGE}},jar);let payload={mbrNm:'',telNo:'',di:'',certType:'',mbrId:id,pw},post=async p=>krxReq(KRX_LOGIN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8',referer:KRX_LOGIN_PAGE},body:new URLSearchParams(p).toString()},jar),x=await post(payload),j={};try{j=JSON.parse(x.text)}catch{throw Error('KRX_LOGIN_PARSE_FAILED')}let code=String(j._error_code||''),msg=C(j._error_message||'');if(code==='CD011'){x=await post({...payload,skipDup:'Y'});try{j=JSON.parse(x.text)}catch{}code=String(j._error_code||'');msg=C(j._error_message||'')}if(code==='CD010')throw Error('KRX_PASSWORD_CHANGE_REQUIRED: KRX에서 비밀번호 변경이 필요합니다.');if(code!=='CD001')throw Error('KRX_LOGIN_FAILED: '+(msg||code||'아이디/비밀번호를 확인해 주세요.'));krxCache.set(key,{jar,expires:Date.now()+25*60*1000});return jar}
async function krxDay(date,id,pw){let jar=await krxSession(id,pw),trd=date.replaceAll('-',''),body=new URLSearchParams({bld:'dbms/MDC/STAT/standard/MDCSTAT01501',locale:'ko_KR',mktId:'ALL',trdDd:trd,share:'1',money:'1',csvxls_isNo:'false'}).toString(),x=await krxReq('https://data.krx.co.kr/comm/bldAttendant/getJsonData.cmd',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded; charset=UTF-8',referer:'https://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101','x-requested-with':'XMLHttpRequest'},body},jar);if(!x.r.ok)throw Error('KRX_DATA_HTTP_'+x.r.status);let j={};try{j=JSON.parse(x.text)}catch{throw Error('KRX_DATA_PARSE_FAILED')}if(j._error_code&&j._error_code!=='CD001')throw Error('KRX_DATA_'+j._error_code+': '+C(j._error_message||''));let a=j.OutBlock_1||j.output||j.result||[];return a.map(x=>({code:String(x.ISU_SRT_CD||x.ISU_CD||''),name:C(x.ISU_ABBRV||x.ISU_NM),market:C(x.MKT_NM||''),rate:N(x.FLUC_RT),price:N(x.TDD_CLSPRC),volume:N(x.ACC_TRDVOL)})).filter(x=>/^\d{6}$/.test(x.code)&&(/KOSPI|KOSDAQ|코스피|코스닥/i.test(x.market)||!x.market))}
async function previousTradingDay(date,id,pw){for(let i=1;i<=10;i++){let d=isoAdd(date,-i);try{let a=await krxDay(d,id,pw);if(a.length)return d}catch(e){if(String(e.message||e).startsWith('KRX_LOGIN_')||String(e.message||e).startsWith('KRX_PASSWORD_'))throw e}}throw Error('직전 거래일을 찾지 못했습니다.')}
async function resolveDate(requested,id,pw){let now=kstNow(),req=requested||now.date;if(req>now.date)throw Error('미래 날짜는 조회할 수 없습니다.');if(daysBetween(req,now.date)>240)throw Error('검색일은 최근 240일 이내만 가능합니다.');if(req<now.date)return{requestedDate:req,effectiveDate:req,mode:'historical',source:'KRX_CLOSE',label:'과거 장마감'};if(['Sat','Sun'].includes(now.weekday)){let d=await previousTradingDay(req,id,pw);return{requestedDate:req,effectiveDate:d,mode:'premarket',source:'KRX_CLOSE',label:'휴장일 → 직전 거래일'}}if(now.hm<540){let d=await previousTradingDay(req,id,pw);return{requestedDate:req,effectiveDate:d,mode:'premarket',source:'KRX_CLOSE',label:'장 시작 전 → 직전 거래일'}}if(now.hm<930)return{requestedDate:req,effectiveDate:req,mode:'realtime',source:'NAVER_REALTIME',label:'장중 실시간'};return{requestedDate:req,effectiveDate:req,mode:'closed',source:'NAVER_CLOSE',label:'장마감'}}
async function leaders(th,date,id,pw){let meta=await resolveDate(date,id,pw),a;if(meta.mode==='realtime'||meta.mode==='closed')a=await naverCurrent(th);else{let all=await krxDay(meta.effectiveDate,id,pw);if(!all.length)throw Error('KRX_DATE_EMPTY: '+meta.effectiveDate+' 거래일 데이터를 찾지 못했습니다.');a=all.filter(x=>x.rate>=th).sort((x,y)=>y.rate-x.rate).slice(0,60)}return{leaders:a,meta:{...meta,count:a.length,threshold:th,krxLogin:!(meta.mode==='realtime'||meta.mode==='closed')}}}
async function quote(code){try{let x=await Q('https://m.stock.naver.com/api/stock/'+code+'/basic');return{code,name:C(x.stockName||x.itemName),rate:N(x.fluctuationsRatio??x.fluctuationRate),price:N(x.closePrice||x.currentPrice),volume:N(x.accumulatedTradingVolume||x.accumulatedVolume)}}catch{return{code,name:'',rate:0,price:0,volume:0}}}
async function hist(code){let x=await T('https://fchart.stock.naver.com/sise.nhn?symbol='+code+'&timeframe=day&count=900&requestType=0'),a=[],m,r=/data="(\d{8})\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)\|([\d.-]+)"/g;while((m=r.exec(x)))a.push({date:m[1],close:N(m[5]),volume:N(m[6])});return a}
function parseInv(h){let a=[],m,r=/<tr[^>]*>([\s\S]*?)<\/tr>/gi;while((m=r.exec(h))){let z=[],n,q=/<td[^>]*>([\s\S]*?)<\/td>/gi;while((n=q.exec(m[1])))z.push(C(n[1]));if(/^\d{4}\.\d{2}\.\d{2}$/.test(z[0]||''))a.push({date:z[0].replaceAll('.','-'),institution:N(z[5]),foreign:N(z[6])})}return a}
async function inv(code,asof){let today=kstNow().date,gap=Math.max(0,daysBetween(asof,today)),est=Math.max(1,Math.floor((gap*5/7)/20)+1),pages=[est-1,est,est+1,est+2].filter((x,i,a)=>x>=1&&a.indexOf(x)===i),out=[];let rs=await Promise.all(pages.map(p=>T('https://finance.naver.com/item/frgn.naver?code='+code+'&page='+p).catch(()=>'')));for(const h of rs)out.push(...parseInv(h));let map=new Map();for(const x of out)map.set(x.date,x);let a=[...map.values()].filter(x=>x.date<=asof).sort((x,y)=>y.date.localeCompare(x.date));if(a.length<10&&est>2){for(let p=Math.max(1,est-3);p<=est+3;p++)if(!pages.includes(p)){try{for(const x of parseInv(await T('https://finance.naver.com/item/frgn.naver?code='+code+'&page='+p)))map.set(x.date,x)}catch{}}a=[...map.values()].filter(x=>x.date<=asof).sort((x,y)=>y.date.localeCompare(x.date))}return a.slice(0,25)}
async function news(name,date){try{let next=isoAdd(date,1),query=name+' 주가 급등 after:'+date+' before:'+next,x=await T('https://news.google.com/rss/search?q='+encodeURIComponent(query)+'&hl=ko&gl=KR&ceid=KR:ko'),a=[],m,r=/<item>([\s\S]*?)<\/item>/gi;while((m=r.exec(x))&&a.length<6){let b=m[1],g=k=>C((b.match(new RegExp('<'+k+'>([\\s\\S]*?)<\\/'+k+'>','i'))||[])[1]||'');a.push({title:g('title'),link:g('link'),pubDate:g('pubDate')})}return a}catch{return[]}}
function links(h){let s=new Set(),m,r=/\/Theme\/ThemeDB\/ThemeAllAllowed\/(\d+)/g;while((m=r.exec(h)))s.add(m[1]);return[...s].slice(0,6)}
function themePage(h,id){let body=C(h),parts=body.split('인포스탁 국내 테마분류'),name='인포스탁 테마';if(parts[1]){let t=parts[1].replace(/^\s*목록\s*/,'').split(/테마 히스토리|관련 종목/)[0].trim();if(t&&t.length<80)name=t}let sec=body.includes('관련 종목')?body.split('관련 종목').slice(1).join('관련 종목'):body,a=[],seen=new Set(),m,r=/([가-힣A-Za-z0-9&·().+\- ]{1,35})\s*\((\d{6})\)/g;while((m=r.exec(sec))&&a.length<45)if(!seen.has(m[2])){seen.add(m[2]);a.push({name:C(m[1]),code:m[2]})}return{name,url:'https://infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed/'+id,members:a,body}}
async function leaderInfo(code,name,date){let nw=await news(name,date),ids=[];for(const u of ['https://infostock.co.kr/stockitem?code='+code,'https://infostock.co.kr/Company/Analysis/StockInfo?code='+code]){try{ids.push(...links(await T(u)))}catch{}}ids=[...new Set(ids)];if(!ids.length)try{ids=links((await T('https://search.naver.com/search.naver?where=web&query='+encodeURIComponent('site:infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed '+name))).replaceAll('&amp;','&'))}catch{}
 let th=[];for(const id of ids.slice(0,5))try{let p=themePage(await T('https://infostock.co.kr/Theme/ThemeDB/ThemeAllAllowed/'+id),id);if(p.body.includes(name)||p.members.some(x=>x.code===code))th.push({name:p.name,url:p.url,members:p.members,source:'InfoStock'})}catch{}
 if(!th.length)th=[{name:infer(nw),url:'https://infostock.co.kr/Theme/ThemeDB',members:[{code,name}],source:'뉴스추론/InfoStock연결대기'}];return{news:nw,themes:th.slice(0,2)}}
function infer(n){let s=n.map(x=>x.title).join(' '),r=[['휴머노이드/로봇',/휴머노이드|협동로봇|로봇/i],['유리기판',/유리기판|글라스기판/i],['반도체/HBM',/HBM|반도체|PCB|FC-BGA/i],['전력설비/전선',/변압기|전력망|전선/i],['원전/SMR',/SMR|원전|원자력/i],['방산',/방산|방위산업|미사일/i],['2차전지',/2차전지|배터리|리튬/i],['바이오/제약',/FDA|임상|신약|바이오|제약/i],['보안',/보안|해킹|딥페이크/i],['AI/데이터센터',/AI|인공지능|데이터센터|GPU/i],['우주항공',/스페이스X|우주항공|위성/i],['자율주행',/자율주행|ADAS|라이다/i],['광통신',/광통신|광케이블|광섬유/i],['LNG/가스',/LNG|천연가스|가스관/i]];for(const x of r)if(x[1].test(s))return x[0];return'뉴스 연관 테마'}
async function member(code,date,mode){let h=await hist(code),cut=date.replaceAll('-',''),z=h.filter(x=>x.date<=cut),row=z.at(-1),prev=z.at(-2),q;if((mode==='realtime'||mode==='closed')&&date===kstNow().date)q=await quote(code);else q={code,name:'',price:row?.close||0,volume:row?.volume||0,rate:row&&prev&&prev.close?((row.close/prev.close)-1)*100:0};let i=await inv(code,date).catch(()=>[]);return{quote:q,hist:z.slice(-520),inv:i,actualDate:row?row.date.slice(0,4)+'-'+row.date.slice(4,6)+'-'+row.date.slice(6):null}}
module.exports=async(req,res)=>{let a=String(req.query.action||'leaders');if(a==='login'){if(req.method!=='POST')return J(res,405,{error:'POST only'});let b='';for await(const c of req)b+=c;let d={};try{d=JSON.parse(b)}catch{}let y=String(d.code||''),z=validToken(y);return z?J(res,200,{token:y}):J(res,401,{error:'인증키가 맞지 않습니다.'})}if(!ok(req))return J(res,401,{error:'인증 필요'});try{if(a==='krx-login'){let id=String(req.headers['x-krx-id']||''),pw=String(req.headers['x-krx-pw']||'');await krxSession(id,pw,true);return J(res,200,{ok:true,message:'KRX 로그인 성공'})}if(a==='leaders'){let th=Math.max(5,Math.min(30,N(req.query.threshold)||10)),date=String(req.query.date||''),id=String(req.headers['x-krx-id']||''),pw=String(req.headers['x-krx-pw']||'');return J(res,200,await leaders(th,date,id,pw))}if(a==='leader')return J(res,200,await leaderInfo(String(req.query.code),String(req.query.name||''),String(req.query.date||kstNow().date)));if(a==='member')return J(res,200,await member(String(req.query.code),String(req.query.date||kstNow().date),String(req.query.mode||'historical')));return J(res,404,{error:'unknown'})}catch(e){console.error('[theme-radar]',a,e);return J(res,500,{error:String(e.message||e)})}};
