import {NextResponse} from 'next/server';
export const runtime='nodejs';export const dynamic='force-dynamic';export const maxDuration=60;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const med=a=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};const pct=(a,b)=>b?(a/b-1)*100:0;
async function yahoo(sym,days){const r=await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(sym)}?range=2y&interval=1d&includePrePost=false&events=div%2Csplits`,{headers:{'User-Agent':'Mozilla/5.0'},cache:'no-store'});if(!r.ok)throw new Error(`Yahoo ${r.status}`);const j=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error('Yahoo no data');const q=x.indicators?.quote?.[0]||{},c=x.indicators?.adjclose?.[0]?.adjclose||q.close||[],o=[];(x.timestamp||[]).forEach((t,i)=>{const v=Number(c[i]);if(Number.isFinite(v)&&v>0)o.push({date:new Date(t*1000).toISOString().slice(0,10),close:v})});if(o.length<Math.min(days,12))throw new Error('Yahoo short');return o.slice(-days)}
async function naver(code,days){const r=await fetch(`https://fchart.stock.naver.com/sise.nhn?symbol=${code}&timeframe=day&count=${Math.max(days+10,30)}&requestType=0`,{headers:{'User-Agent':'Mozilla/5.0','Referer':'https://finance.naver.com/'},cache:'no-store'});if(!r.ok)throw new Error(`Naver ${r.status}`);const x=await r.text(),o=[];for(const m of x.matchAll(/data="(\d{8})\|([^|]+)\|([^|]+)\|([^|]+)\|([^|]+)\|([^\"]+)"/g)){const v=Number(m[5]);if(Number.isFinite(v)&&v>0)o.push({date:`${m[1].slice(0,4)}-${m[1].slice(4,6)}-${m[1].slice(6,8)}`,close:v})}if(o.length<Math.min(days,12))throw new Error('Naver short');return o.slice(-days)}
async function history(s,d){try{return{rows:await yahoo(s.yahoo,d),source:'Yahoo'}}catch{return{rows:await naver(s.code,d),source:'Naver'}}}
function pivots(rows){const n=rows.length,w=n<35?1:n<90?2:3,p=[];for(let i=w;i<n-w;i++){const c=rows[i].close,ns=[];for(let j=i-w;j<=i+w;j++)if(j!==i)ns.push(rows[j].close);if(ns.every(x=>c<=x)&&ns.some(x=>c<x))p.push({type:'low',idx:i,price:c});if(ns.every(x=>c>=x)&&ns.some(x=>c>x))p.push({type:'high',idx:i,price:c})}const z=[];for(const a of p){const l=z.at(-1);if(!l||l.type!==a.type)z.push(a);else if((a.type==='low'&&a.price<l.price)||(a.type==='high'&&a.price>l.price))z[z.length-1]=a}return z}
function analyze(s,rows,proximity){if(rows.length<12)return null;const p=pivots(rows),lo=p.filter(x=>x.type==='low'),hi=p.filter(x=>x.type==='high');if(lo.length<2||hi.length<2)return null;const L=lo.slice(-5),H=hi.slice(-5),support=med(L.map(x=>x.price)),resistance=med(H.map(x=>x.price));if(!(support>0&&resistance>support))return null;const disp=(a,c)=>med(a.map(v=>Math.abs(v-c)/c*100)),lowDisp=disp(L.map(x=>x.price),support),highDisp=disp(H.map(x=>x.price),resistance),amplitude=pct(resistance,support),current=rows.at(-1).close,distance=pct(current,support),rangePos=(current-support)/(resistance-support),alt=Math.max(0,p.length-1),r5=rows.length>6?pct(current,rows.at(-6).close):0;const gaps=[];for(let i=1;i<lo.length;i++)gaps.push(lo[i].idx-lo[i-1].idx);const avg=gaps.length?gaps.reduce((a,b)=>a+b,0)/gaps.length:0,gdisp=avg?med(gaps.map(g=>Math.abs(g-avg)/avg*100)):50;const prox=clamp(100-Math.max(distance,0)/Math.max(proximity,.5)*100,0,100),rep=clamp(100-lowDisp*7-highDisp*3,0,100),cyc=clamp(25+alt*8-gdisp*.45,0,100),amp=clamp((amplitude-5)*4.2,0,100),score=clamp(Math.round(prox*.4+rep*.28+cyc*.17+amp*.15+(r5<0?8:0)),0,100);if(!(distance>=-5&&distance<=proximity&&rangePos<=.38&&amplitude>=7&&lowDisp<=12&&highDisp<=20&&alt>=4))return null;return{...s,current,support,resistance,distance,rangePos:rangePos*100,amplitude,lowDisp,highDisp,cycles:Math.floor(alt/2),pivotLows:lo.length,pivotHighs:hi.length,score,ret5:r5,reason:`반복저점 ${lo.length}회 · 반복고점 ${hi.length}회 · 지지선 대비 ${distance>=0?'+':''}${distance.toFixed(1)}% · 저점 편차 ${lowDisp.toFixed(1)}% · 고저 변동폭 ${amplitude.toFixed(1)}%${r5<0?' · 최근 5일 저점 방향 접근':''}`,spark:rows.slice(-60).map(r=>[r.date,r.close])}}
async function one(s,d,p){try{const h=await history(s,d),hit=analyze(s,h.rows,p);return{ok:true,hit:hit?{...hit,source:h.source}:null}}catch(e){return{ok:false,code:s.code,name:s.name,error:String(e?.message||e)}}}
export async function POST(req){try{const b=await req.json(),days=Math.min(240,Math.max(1,Number(b.days||240))),proximity=Math.min(20,Math.max(1,Number(b.proximity||7))),stocks=Array.isArray(b.stocks)?b.stocks.slice(0,25):[],z=await Promise.all(stocks.map(s=>one(s,days,proximity)));return NextResponse.json({ok:true,scanned:stocks.length,hits:z.filter(x=>x.ok&&x.hit).map(x=>x.hit),errors:z.filter(x=>!x.ok)})}catch(e){return NextResponse.json({ok:false,error:String(e?.message||e)},{status:500})}}
