// @ts-nocheck
import {EVENT_WORDS,THEME_RULES} from './config';
import {clean,validDate,dateObj,daysInMonth,ymd,addDays,dday,sha} from './base';
function refDate(iso:string){const d=new Date(iso);return Number.isNaN(d.getTime())?new Date():d}
const PAST_YEAR=/작년|지난해|전년/;
const PAST_CUE=/지난\s*(?:달|주|분기|상반기|하반기)?|지난달|전월|당시|앞서|이미|종료|완료/;
const FUTURE_CUE=/내년|다음해|오는|향후|앞으로|예정|계획|목표|전망|예고|앞두|결정|공개|발표|개최|시행|출시|상장|착공|준공|재신청/;
function contextualYear(m:number,ref:Date,around:string){const y=ref.getFullYear(),rm=ref.getMonth()+1;if(PAST_YEAR.test(around))return y-1;if(/내년|다음해/.test(around))return y+1;if(PAST_CUE.test(around))return m>rm?y-1:y;if(m<rm&&/오는|향후|앞으로/.test(around))return y+1;if(rm===12&&m<=2&&FUTURE_CUE.test(around))return y+1;return y}
export function extractDates(text:string,publishedAt:string){const s=clean(text),ref=refDate(publishedAt),found:any[]=[];const context=(idx:number)=>s.slice(Math.max(0,idx-150),Math.min(s.length,idx+260));const add=(sortDate:string,displayDate:string,precision:string,raw:string,idx=-1)=>sortDate&&found.push({sortDate,displayDate,precision,raw,context:idx>=0?context(idx):''});const near=(idx:number,r=110)=>EVENT_WORDS.test(s.slice(Math.max(0,idx-80),idx+r));let m:any;
 const full=/(20\d{2})\s*[년.\/-]\s*(1[0-2]|0?\d)\s*[월.\/-]\s*([0-3]?\d)\s*일?/g;while((m=full.exec(s)))if(near(m.index))add(dateObj(+m[1],+m[2],+m[3]),`${m[1]}-${String(+m[2]).padStart(2,'0')}-${String(+m[3]).padStart(2,'0')}`,'day',m[0],m.index);
 const numeric=/(20\d{2})[-\/.](1[0-2]|0?\d)[-\/.]([0-3]?\d)/g;while((m=numeric.exec(s)))if(near(m.index))add(dateObj(+m[1],+m[2],+m[3]),m[0].replace(/[./]/g,'-'),'day',m[0],m.index);
 const ny=/내년\s*(1[0-2]|0?\d)\s*월\s*([0-3]?\d)\s*일/g;while((m=ny.exec(s))){const y=ref.getFullYear()+1;add(dateObj(y,+m[1],+m[2]),`${y}-${String(+m[1]).padStart(2,'0')}-${String(+m[2]).padStart(2,'0')}`,'day',m[0],m.index)}
 const md=/(?<!\d)(1[0-2]|0?\d)\s*월\s*([0-3]?\d)\s*일/g;while((m=md.exec(s))){if(!near(m.index))continue;const around=context(m.index),y=contextualYear(+m[1],ref,around);add(dateObj(y,+m[1],+m[2]),`${y}-${String(+m[1]).padStart(2,'0')}-${String(+m[2]).padStart(2,'0')}`,'day',m[0],m.index)}
 const coming=/(?:오는|이달)\s*([0-3]?\d)\s*일/g;while((m=coming.exec(s))){let y=ref.getFullYear(),mo=ref.getMonth()+1,d=+m[1],x=validDate(y,mo,d);if(x&&(x.getTime()-ref.getTime())/86400000<-7){if(++mo===13){mo=1;y++}}add(dateObj(y,mo,d),`${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`,'day',m[0],m.index)}
 const nmd=/(?:내달|다음\s*달)\s*([0-3]?\d)\s*일/g;while((m=nmd.exec(s))){let y=ref.getFullYear(),mo=ref.getMonth()+2;if(mo>12){mo-=12;y++}add(dateObj(y,mo,+m[1]),`${y}-${String(mo).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`,'day',m[0],m.index)}
 const nm=/(?:내달|다음\s*달)(?!\s*\d+\s*일)/g;while((m=nm.exec(s))){const around=context(m.index);if(!EVENT_WORDS.test(around))continue;let y=ref.getFullYear(),mo=ref.getMonth()+2;if(mo>12){mo-=12;y++}add(dateObj(y,mo,15),`${y}-${String(mo).padStart(2,'0')}`,'month',m[0],m.index)}
 const month=/(?<!\d)(1[0-2]|0?\d)\s*월\s*(초|초순|중|중순|말|말경)?(?!\s*\d+\s*일)/g;while((m=month.exec(s))){const around=context(m.index);if(!EVENT_WORDS.test(around))continue;const mo=+m[1],y=contextualYear(mo,ref,around);let d=15,label=m[2]||'';if(/초/.test(label))d=5;else if(/말/.test(label))d=Math.max(25,daysInMonth(y,mo)-4);add(dateObj(y,mo,d),`${y}-${String(mo).padStart(2,'0')}${label?' '+label:''}`,'month',m[0],m.index)}
 const q=/(?:(20\d{2})년\s*)?([1-4])\s*분기/g;while((m=q.exec(s))){const around=context(m.index);if(!EVENT_WORDS.test(around))continue;let y=m[1]?+m[1]:ref.getFullYear();if(!m[1]&&PAST_YEAR.test(around))y--;else if(!m[1]&&/내년|다음해/.test(around))y++;const mo=+m[2]*3;add(dateObj(y,mo,daysInMonth(y,mo)),`${y}년 ${m[2]}분기`,'period',m[0],m.index)}
 const half=/(내년\s*)?(상반기|하반기|연말)/g;while((m=half.exec(s))){const around=context(m.index);if(!EVENT_WORDS.test(around))continue;let y=ref.getFullYear();if(m[1]||/내년|다음해/.test(around))y++;else if(PAST_YEAR.test(around))y--;const mo=m[2]==='상반기'?6:12;add(dateObj(y,mo,daysInMonth(y,mo)),`${y}년 ${m[2]}`,'period',m[0],m.index)}
 const wk=/다음\s*주/g;while((m=wk.exec(s))){const around=context(m.index);if(!EVENT_WORDS.test(around))continue;const d=new Date(ref),day=d.getDay();d.setDate(d.getDate()+((8-day)%7||7));add(ymd(d),`${ymd(d)} 주간`,'week',m[0],m.index)}
 const rank:any={day:4,week:3,month:2,period:1},best=new Map<string,any>();for(const x of found){const k=`${x.sortDate}|${x.raw}`,old=best.get(k);if(!old||rank[x.precision]>rank[old.precision])best.set(k,x)}return[...best.values()]}
export function eventType(t:string){if(/FDA|PDUFA|NDA\b|BLA\b|CRL\b|품목허가|허가심사|식약처|EMA|승인|허가/.test(t))return'허가·승인';if(/임상|탑라인|톱라인|학회|ASCO|ESMO|AACR|SITC|중간결과|중간 결과/.test(t))return'임상·학회';if(/실적|IR\b|NDR|컨퍼런스콜|기업설명회/.test(t))return'실적·IR';if(/정책|법안|시행령|규제|정부|공청회|청문회/.test(t))return'정책·시행';if(/입찰|선정|수주|계약|납품/.test(t))return'입찰·수주·계약';if(/출시|공개|오픈|상용화/.test(t))return'제품·서비스 출시';if(/양산|가동|생산/.test(t))return'생산·양산';if(/착공|준공|완공|진수|인도/.test(t))return'착공·준공·인도';if(/주주총회|배당|기준일|권리락|증자|신주상장/.test(t))return'주총·자본정책';if(/M&A|인수|합병|분할|매각|공개매수|지분/.test(t))return'M&A·지배구조';if(/판결|선고|소송|특허|가처분/.test(t))return'법원·특허';if(/MSCI|코스피200|코스닥150|리밸런싱|편입|편출/.test(t))return'지수·시장제도';if(/행사|회의|정상회의|박람회|전시회|CES|MWC|SEMICON/.test(t))return'행사·회의';return'기타 일정'}
export function classify(text:string){const hits=THEME_RULES.filter(r=>r[2].test(text));return{sector:hits[0]?.[0]||'기타',themes:[...new Set(hits.map(h=>h[1]))].slice(0,4)}}
const escRe=(s:string)=>s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
function mention(text:string,name:string){const n=name.trim();if(!n)return false;if(n==='NAVER')return/(^|[^A-Za-z0-9가-힣])(NAVER|네이버)(?=$|[^A-Za-z0-9가-힣])/i.test(text);if(n==='SK하이닉스')return/SK\s*하이닉스|(?<![가-힣])하이닉스(?![가-힣])/.test(text);if(/^[A-Za-z0-9&. -]+$/.test(n))return new RegExp(`(^|[^A-Za-z0-9가-힣])${escRe(n)}(?=$|[^A-Za-z0-9가-힣])`,'i').test(text);const core=n.replace(/\(주\)|㈜|주식회사/g,'').trim();if(core.length<=2)return new RegExp(`(^|[^가-힣A-Za-z0-9])${escRe(core)}(?=$|[^가-힣A-Za-z0-9])`).test(text);return new RegExp(`(^|[^가-힣A-Za-z0-9])${escRe(core)}(?=$|[^가-힣A-Za-z0-9]|은|는|이|가|의|을|를|과|와|도|에|서|로|으로|측|사|그룹)`).test(text)}
function matched(text:string,stocks:any[],limit=8){const out:any[]=[];for(const s of stocks){if(mention(text,s.name)){out.push(s);if(out.length>=limit)break}}return out}
export function eventFromArticle(a:any,stocks:any[],horizon:number){const fullText=clean(`${a.title} ${a.snippet} ${a.bodyText||''}`);if(!EVENT_WORDS.test(fullText))return[];const dates=extractDates(fullText,a.publishedAt),tomorrow=addDays(ymd(new Date()),1),max=addDays(ymd(new Date()),horizon),titleStocks=matched(clean(`${a.title} ${a.snippet}`),stocks,6),fullStocks=matched(fullText,stocks,8),out:any[]=[];for(const d of dates){if(d.sortDate<tomorrow||d.sortDate>max)continue;const local=clean(`${a.title} ${d.context||''}`),localStocks=matched(local,stocks,8),linked=localStocks.length?localStocks:(titleStocks.length?titleStocks:fullStocks.slice(0,4)),cls=classify(local),et=eventType(local);const base:any={...a,eventDate:d.sortDate,displayDate:d.displayDate,precision:d.precision,dateText:d.raw,dDay:dday(d.sortDate),stocks:linked.map(s=>({code:s.code,name:s.name,market:s.market,price:s.price,changePct:s.changePct,naver:s.naver})),sector:cls.sector,themes:cls.themes,eventType:et,text:fullText,eventContext:d.context||''};let score=d.precision==='day'?76:d.precision==='week'?68:d.precision==='month'?63:56;if(EVENT_WORDS.test(local))score+=7;if(linked.length)score+=5;if(a.naverNewsUrl)score+=5;if(a.bodyText)score+=4;if(a.searchGroup==='bio')score+=4;if(a.title.includes(d.raw))score+=4;if(et!=='기타 일정')score+=3;score=Math.min(99,score);const articleKey=(a.naverNewsUrl||a.originUrl||a.title).replace(/[?#].*$/,'');out.push({...base,score,naverSearchUrl:`https://search.naver.com/search.naver?where=news&query=${encodeURIComponent('"'+a.title.slice(0,80)+'"')}`,id:sha(`${articleKey}|${d.sortDate}`)})}return out}
