// @ts-nocheck
import * as cheerio from 'cheerio';
import {SEARCH_TERMS,BIO_SEARCH_TERMS,WINDOW_DAYS,BIO_WINDOW_DAYS,BIO_HINT_RE} from './config';
import {fetchText,clean,addDays,compact,fmtNaverDate,ymd} from './base';
const cache=new Map<string,any>(),bodyCache=new Map<string,any>();
const UAS={desktop:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140 Safari/537.36',mobile:'Mozilla/5.0 (Linux; Android 16; SM-S937N) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36'};
function windows(range:any,days:number){const out:any[]=[];let cur=range.start;while(cur<=range.end){const z=addDays(cur,days-1),to=z>range.end?range.end:z;out.push({from:cur,to});cur=addDays(to,1)}return out}
export function buildTasks(range:any,pageDepth:number){
 const generalWindows=windows(range,WINDOW_DAYS),bioWindows=windows(range,BIO_WINDOW_DAYS),bioDepth=Math.min(4,Math.max(2,pageDepth+1)),tasks:any[]=[];
 for(const w of bioWindows)for(const term of BIO_SEARCH_TERMS)tasks.push({group:'bio',term,...w,pageDepth:bioDepth});
 for(const w of generalWindows)for(const term of SEARCH_TERMS)tasks.push({group:'general',term,...w,pageDepth});
 return{windows:generalWindows,bioWindows,tasks,bioDepth};
}
export function searchUrl(term:string,from:string,to:string,start=1){const p=new URLSearchParams({where:'news',ssc:'tab.news.all',query:term,sm:'tab_opt',sort:'1',photo:'0',field:'0',pd:'3',ds:fmtNaverDate(from),de:fmtNaverDate(to),nso:`so:dd,p:from${compact(from)}to${compact(to)},a:all`,start:String(start)});return`https://search.naver.com/search.naver?${p}`}
function searchCandidates(term:string,from:string,to:string,start:number){const desktop=searchUrl(term,from,to,start),u=new URL(desktop),mobile=new URL(desktop),internal=new URL(desktop);mobile.hostname='m.search.naver.com';internal.hostname='s.search.naver.com';internal.pathname='/p/newssearch/search.naver';internal.searchParams.delete('ssc');return[
 {provider:'naver-desktop',url:desktop,headers:{'User-Agent':UAS.desktop,Referer:'https://search.naver.com/'}},
 {provider:'naver-mobile',url:mobile.toString(),headers:{'User-Agent':UAS.mobile,Referer:'https://m.search.naver.com/'}},
 {provider:'naver-news-ajax',url:internal.toString(),headers:{'User-Agent':UAS.desktop,Referer:'https://search.naver.com/'}}
]}
const abs=(h:string)=>!h?'':h.startsWith('//')?'https:'+h:h.startsWith('/')?'https://search.naver.com'+h:h;
const hosted=(h:string)=>/https?:\/\/(?:n\.news\.naver\.com|news\.naver\.com)\//i.test(h||'');
function published(text:string,fallback:string){const m=text.match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})[.]?/);if(m){const d=new Date(+m[1],+m[2]-1,+m[3],12);if(!Number.isNaN(d.getTime()))return d.toISOString()}const r=text.match(/(\d+)\s*(분|시간|일)\s*전/);if(r){const d=new Date(),n=+r[1];r[2]==='분'?d.setMinutes(d.getMinutes()-n):r[2]==='시간'?d.setHours(d.getHours()-n):d.setDate(d.getDate()-n);return d.toISOString()}return new Date(fallback+'T12:00:00+09:00').toISOString()}
export function parseSearch(html:string,task:any){const $=cheerio.load(html),out:any[]=[],seen=new Set<string>();let as=$('a[data-heatmap-target=".tit"],a.news_tit');if(!as.length)as=$('a[href]').filter((_,e)=>{const a=$(e),t=clean(a.text()),h=abs(a.attr('href')||'');return t.length>=12&&(/news|article/.test(h)||hosted(h))});as.each((_,e)=>{const a=$(e),title=clean(a.attr('title')||a.text()).replace(/새\s*창\s*열림.*$/,'').trim(),href=abs(a.attr('href')||'');if(title.length<8)return;let box=a.closest('div.sds-comps-vertical-layout,li.bx,div.news_area,div.news_wrap,div[data-template-id]');if(!box.length)box=a.parent().parent().parent();const snippet=clean(box.find('a[data-heatmap-target=".body"],.news_dsc,.dsc_txt_wrap').first().text()),source=clean(box.find('a[data-heatmap-target=".prof"],.info.press,.press,.info_group .press').first().text());let naverNewsUrl='';box.find('a[href]').each((__,x)=>{if(!naverNewsUrl){const h=abs($(x).attr('href')||'');if(hosted(h))naverNewsUrl=h}});if(hosted(href))naverNewsUrl=href;const key=(naverNewsUrl||href||title).replace(/[?#].*$/,'');if(seen.has(key))return;seen.add(key);out.push({title,snippet,source:source||'언론사 미상',naverNewsUrl,originUrl:href,publishedAt:published(clean(box.text()),task.to),queryTerm:task.term,searchGroup:task.group||'general',windowFrom:task.from,windowTo:task.to})});return out}
async function fetchSearchItems(task:any,start:number){let lastError:any=null,hadSuccess=false;for(const c of searchCandidates(task.term,task.from,task.to,start)){try{const html=await fetchText(c.url,c.headers),items=parseSearch(html,task);hadSuccess=true;if(items.length)return{items,provider:c.provider};}catch(e){lastError=e}}if(hadSuccess)return{items:[],provider:'naver-empty'};throw lastError||new Error('NAVER_SEARCH_UNAVAILABLE')}
export async function searchTask(task:any){const k=`${task.group}|${task.term}|${task.from}|${task.to}|${task.pageDepth}`,c=cache.get(k);if(c&&Date.now()-c.at<900000)return c.items;const req=[];for(let p=0;p<task.pageDepth;p++)req.push(fetchSearchItems(task,1+p*10).then(r=>r.items).catch(()=>[]));const seen=new Set<string>(),items:any[]=[];for(const x of (await Promise.all(req)).flat()){const key=(x.naverNewsUrl||x.originUrl||x.title).replace(/[?#].*$/,'');if(!seen.has(key)){seen.add(key);items.push(x)}}cache.set(k,{at:Date.now(),items});return items}
async function articleBody(url:string){const key=url.replace(/[?#].*$/,''),c=bodyCache.get(key);if(c&&Date.now()-c.at<3600000)return c.text;try{const html=await fetchText(key,{'User-Agent':UAS.mobile,Referer:'https://n.news.naver.com/'}),$=cheerio.load(html);let text='';for(const sel of ['#dic_area','#articeBody','.newsct_article','#articleBodyContents','article']){const t=clean($(sel).first().text());if(t.length>text.length)text=t}if(text.length<80)text=clean($('meta[property="og:description"]').attr('content')||'');text=text.replace(/기사원문|무단\s*전재[^.]{0,120}/g,' ').replace(/Copyright\s*[^.]{0,120}/gi,' ').replace(/\s+/g,' ').trim().slice(0,18000);bodyCache.set(key,{at:Date.now(),text});return text}catch{return''}}
export async function enrichArticles(items:any[]){const out=items.map(x=>({...x})),targets=out.map((x,i)=>({x,i})).filter(({x})=>x.naverNewsUrl&&(x.searchGroup==='bio'||BIO_HINT_RE.test(`${x.title} ${x.snippet}`))).slice(0,48);for(let s=0;s<targets.length;s+=8){const batch=targets.slice(s,s+8),texts=await Promise.all(batch.map(({x})=>articleBody(x.naverNewsUrl)));for(let j=0;j<batch.length;j++)if(texts[j])out[batch[j].i].bodyText=texts[j]}return out}
export async function health(){const task={group:'general',term:'예정',from:addDays(ymd(new Date()),-3),to:ymd(new Date()),pageDepth:1};const bio={group:'bio',term:'HLB FDA',from:'2026-08-20',to:'2026-09-05',pageDepth:1};try{const [r,b]=await Promise.all([fetchSearchItems(task,1),fetchSearchItems(bio,1)]);return{ok:true,naverSearch:true,provider:r.provider,selectorCount:r.items.length,titleSample:r.items[0]?.title||null,bioProbeCount:b.items.length,bioProbeSample:b.items.find(x=>/HLB/i.test(x.title))?.title||b.items[0]?.title||null,checkedAt:new Date().toISOString()}}catch(e:any){return{ok:false,naverSearch:false,error:String(e?.message||e),checkedAt:new Date().toISOString()}}}
