// @ts-nocheck
import {fetchJson,fetchText,num,capEok,ymd} from './base';
let universeCache:any={at:0,rows:[]};const tradingCache=new Map<number,any>();
function arr(j:any){if(Array.isArray(j))return j;for(const k of ['stocks','items','data','stockList','result'])if(Array.isArray(j?.[k]))return j[k];if(Array.isArray(j?.result?.stocks))return j.result.stocks;return []}
async function market(market:'KOSPI'|'KOSDAQ'){
 const size=100,first=await fetchJson(`https://m.stock.naver.com/api/stocks/marketValue/${market}?page=1&pageSize=${size}`,{Referer:'https://m.stock.naver.com/'}),r1=arr(first),count=Number(first?.totalCount??first?.result?.totalCount??0),pages=count?Math.min(35,Math.ceil(count/size)):30,out:any[]=[...r1];
 for(let s=2;s<=pages;s+=8){const batch=[];for(let p=s;p<Math.min(s+8,pages+1);p++)batch.push(fetchJson(`https://m.stock.naver.com/api/stocks/marketValue/${market}?page=${p}&pageSize=${size}`,{Referer:'https://m.stock.naver.com/'}).then(arr).catch(()=>[]));const xs=await Promise.all(batch);for(const x of xs)out.push(...x)}
 const seen=new Set<string>();return out.map(x=>{const code=String(x?.itemCode??x?.stockCode??x?.code??'').match(/\d{6}/)?.[0]||'',name=String(x?.stockName??x?.name??x?.itemName??'').trim();return{code,name,market,price:num(x?.closePrice??x?.currentPrice),changePct:num(x?.fluctuationsRatio??x?.changeRate),marketCapEok:capEok(x?.marketValue??x?.marketCap),naver:`https://finance.naver.com/item/main.naver?code=${code}`}}).filter(x=>x.code&&x.name&&!seen.has(x.code)&&!!seen.add(x.code))
}
export async function universe(){if(Date.now()-universeCache.at<21600000&&universeCache.rows.length>1000)return universeCache.rows;const [a,b]=await Promise.all([market('KOSPI'),market('KOSDAQ')]);return universeCache={at:Date.now(),rows:[...a,...b]},universeCache.rows}
export async function tradingRange(trades:number){const n=Math.max(20,Math.min(240,trades||240)),c=tradingCache.get(n);if(c&&Date.now()-c.at<21600000)return c;try{const xml=await fetchText(`https://fchart.stock.naver.com/sise.nhn?symbol=005930&timeframe=day&count=${Math.max(280,n+35)}&requestType=0`,{Referer:'https://finance.naver.com/'}),ds=[...xml.matchAll(/<item\s+data="(\d{8})\|/g)].map(m=>`${m[1].slice(0,4)}-${m[1].slice(4,6)}-${m[1].slice(6,8)}`),dates=[...new Set(ds)].sort();if(dates.length>=n){const o={at:Date.now(),start:dates[dates.length-n],end:dates.at(-1),dates:dates.slice(-n)};tradingCache.set(n,o);return o}}catch{}const end=new Date(),start=new Date();start.setDate(start.getDate()-Math.ceil(n*1.48));const o={at:Date.now(),start:ymd(start),end:ymd(end),dates:[]};tradingCache.set(n,o);return o}
