import {NextResponse} from 'next/server';
import {isAuthed,unauthorized} from '@/lib/guard';
export const runtime='nodejs';export const maxDuration=60;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const n=(v:any)=>{if(typeof v==='number')return Number.isFinite(v)?v:null;const x=Number(String(v??'').replace(/[, +%원]/g,''));return Number.isFinite(x)?x:null};
const kst=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
function rowsOf(j:any){return Array.isArray(j)?j:Array.isArray(j?.stocks)?j.stocks:Array.isArray(j?.result?.stocks)?j.result.stocks:Array.isArray(j?.items)?j.items:Array.isArray(j?.result?.items)?j.result.items:Array.isArray(j?.data)?j.data:[];}
async function getJson(url:string){let last='';for(let a=0;a<3;a++){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),8500);try{const r=await fetch(url,{signal:ctl.signal,cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36','Accept':'application/json, text/plain, */*','Accept-Language':'ko-KR,ko;q=0.9','Referer':'https://m.stock.naver.com/'}});clearTimeout(t);if(!r.ok){last=`HTTP ${r.status}`;await sleep(180*(a+1));continue;}return rowsOf(await r.json());}catch(e){clearTimeout(t);last=e instanceof Error?e.message:'fetch error';await sleep(180*(a+1));}}throw new Error(last||'네이버 시세 수집 실패');}
function norm(x:any){const code=String(x?.itemCode??x?.itemcode??x?.stockCode??x?.code??'').match(/\d{6}/)?.[0]||'',name=String(x?.stockName??x?.name??x?.itemName??'').trim();if(!code||!name)return null;const traded=String(x?.localTradedAt??x?.tradedAt??x?.tradeDate??x?.date??'');return {name,code,market:'KOSDAQ' as const,currentPrice:n(x?.closePrice??x?.currentPrice??x?.nowVal??x?.price),changePct:n(x?.fluctuationsRatio??x?.changeRate??x?.changePct??x?.rate),marketCap:n(x?.marketValue??x?.marketCap??x?.marketValueAmount),sector:null,theme:null,currentVolume:n(x?.accumulatedTradingVolume??x?.volume??x?.tradingVolume),openPrice:n(x?.openPrice??x?.open??x?.openingPrice),highPrice:n(x?.highPrice??x?.high??x?.highestPrice),lowPrice:n(x?.lowPrice??x?.low??x?.lowestPrice),quoteDate:traded.match(/\d{4}-\d{2}-\d{2}/)?.[0]||kst()};}
async function collect(kind:'mobile'|'front'){const all:any[]=[],seen=new Set<string>();for(let p=1;p<=30;p++){const url=kind==='mobile'?`https://m.stock.naver.com/api/stocks/marketValue/KOSDAQ?page=${p}&pageSize=100&_=${Date.now()}`:`https://m.stock.naver.com/front-api/stock/domestic/stockList?sortType=marketValue&category=KOSDAQ&page=${p}&pageSize=100`;const rows=await getJson(url);if(!rows.length)break;let added=0;for(const x of rows){const s=norm(x);if(s&&!seen.has(s.code)){seen.add(s.code);all.push(s);added++;}}if(!added||rows.length<100)break;}if(all.length<1000)throw new Error(`${kind} KOSDAQ ${all.length}건`);return all;}
export async function GET(){if(!await isAuthed())return unauthorized();const errors:string[]=[];try{let stocks:any[]=[],source='';try{stocks=await collect('mobile');source='naver-mobile-json';}catch(e1){errors.push(e1 instanceof Error?e1.message:'mobile 오류');stocks=await collect('front');source='naver-front-api';}stocks=[...new Map(stocks.map(x=>[x.code,x])).values()].sort((a:any,b:any)=>(b.marketCap||0)-(a.marketCap||0)).map((x:any,i:number)=>({...x,rank:i+1}));return NextResponse.json({stocks,errors,sources:[`${source}(${stocks.length})`],updatedAt:new Date().toISOString()},{headers:{'Cache-Control':'no-store, max-age=0'}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'KOSDAQ 전종목 수집 실패',stocks:[],errors},{status:502});}}
