import {NextResponse} from 'next/server';
import {isAuthed,unauthorized} from '@/lib/guard';
export const runtime='nodejs';export const maxDuration=60;
type Market='KOSPI'|'KOSDAQ';
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const n=(v:any)=>{if(typeof v==='number')return Number.isFinite(v)?v:null;const x=Number(String(v??'').replace(/[, +%원]/g,''));return Number.isFinite(x)?x:null};
const kst=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
function rowsOf(j:any){return Array.isArray(j)?j:Array.isArray(j?.stocks)?j.stocks:Array.isArray(j?.result?.stocks)?j.result.stocks:Array.isArray(j?.items)?j.items:Array.isArray(j?.result?.items)?j.result.items:Array.isArray(j?.data)?j.data:[];}
async function getJson(url:string){let last='';for(let a=0;a<3;a++){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),8500);try{const r=await fetch(url,{signal:ctl.signal,cache:'no-store',headers:{'User-Agent':'Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36','Accept':'application/json, text/plain, */*','Accept-Language':'ko-KR,ko;q=0.9','Referer':'https://m.stock.naver.com/'}});clearTimeout(t);if(!r.ok){last=`HTTP ${r.status}`;await sleep(180*(a+1));continue;}return rowsOf(await r.json());}catch(e){clearTimeout(t);last=e instanceof Error?e.message:'fetch error';await sleep(180*(a+1));}}throw new Error(last||'네이버 시세 수집 실패');}
function norm(x:any,market:Market){const code=String(x?.itemCode??x?.itemcode??x?.stockCode??x?.code??'').match(/\d{6}/)?.[0]||'',name=String(x?.stockName??x?.name??x?.itemName??'').trim();if(!code||!name)return null;const traded=String(x?.localTradedAt??x?.tradedAt??x?.tradeDate??x?.date??'');return {name,code,market,currentPrice:n(x?.closePrice??x?.currentPrice??x?.nowVal??x?.price),changePct:n(x?.fluctuationsRatio??x?.changeRate??x?.changePct??x?.rate),marketCap:n(x?.marketValue??x?.marketCap??x?.marketValueAmount),sector:null,theme:null,currentVolume:n(x?.accumulatedTradingVolume??x?.volume??x?.tradingVolume),openPrice:n(x?.openPrice??x?.open??x?.openingPrice),highPrice:n(x?.highPrice??x?.high??x?.highestPrice),lowPrice:n(x?.lowPrice??x?.low??x?.lowestPrice),quoteDate:traded.match(/\d{4}-\d{2}-\d{2}/)?.[0]||kst()};}
async function collect(kind:'mobile'|'front',market:Market,limit:number){const all:any[]=[],seen=new Set<string>(),pages=Math.max(1,Math.ceil(limit/100)+1);for(let p=1;p<=pages;p++){const url=kind==='mobile'?`https://m.stock.naver.com/api/stocks/marketValue/${market}?page=${p}&pageSize=100&_=${Date.now()}`:`https://m.stock.naver.com/front-api/stock/domestic/stockList?sortType=marketValue&category=${market}&page=${p}&pageSize=100`;const rows=await getJson(url);if(!rows.length)break;let added=0;for(const x of rows){const s=norm(x,market);if(s&&!seen.has(s.code)){seen.add(s.code);all.push(s);added++;}}if(!added||rows.length<100||all.length>=limit)break;}if(all.length<Math.min(limit,100))throw new Error(`${kind} ${market} ${all.length}건`);return all.sort((a,b)=>(b.marketCap||0)-(a.marketCap||0)).slice(0,limit).map((x,i)=>({...x,marketRank:i+1}));}
async function market(market:Market,limit:number){const errors:string[]=[];try{return {stocks:await collect('mobile',market,limit),source:`naver-mobile-${market}`,errors};}catch(e1){errors.push(e1 instanceof Error?e1.message:'mobile 오류');return {stocks:await collect('front',market,limit),source:`naver-front-${market}`,errors};}}
export async function GET(req:Request){if(!await isAuthed())return unauthorized();const u=new URL(req.url),kp=Math.max(50,Math.min(900,Number(u.searchParams.get('kospi')||500))),kq=Math.max(50,Math.min(900,Number(u.searchParams.get('kosdaq')||300)));try{const [a,b]=await Promise.all([market('KOSPI',kp),market('KOSDAQ',kq)]);const stocks=[...a.stocks,...b.stocks].map((x,i)=>({...x,rank:i+1}));return NextResponse.json({stocks,errors:[...a.errors,...b.errors],sources:[`${a.source}(${a.stocks.length})`,`${b.source}(${b.stocks.length})`],updatedAt:new Date().toISOString(),limits:{kospi:kp,kosdaq:kq}},{headers:{'Cache-Control':'no-store, max-age=0'}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'한국시장 종목 수집 실패',stocks:[]},{status:502});}}
