'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import PriceChart from './PriceChart';
import {BASE_WEIGHTS,type Weights,type WeightKey} from '@/lib/learning';

type Stock={name:string;code:string;market:'KOSPI'|'KOSDAQ';currentPrice:number|null;changePct:number|null;marketCap:number|null;sector:string|null;theme:string|null};
type Row=Stock&{ret5?:number;volumeScore?:number|null;newsScore?:number|null;supplyScore?:number|null;chartScore?:number|null;disclosureScore?:number|null;sectorScore?:number|null;penalty?:number;reasons?:string[];newsReasons?:string[];supplyReasons?:string[];news?:any[];detectedAt?:string;dataStatus?:string;error?:string;events?:any[];stats?:any;finalScore?:number;coverage?:number;stage?:string};
type Tab='top'|'all'|'30'|'50'|'70'|'engine'|'history'|'track'|'settings';
const rawMax:Record<WeightKey,number>={volume:25,news:20,supply:15,chart:15,disclosure:15,sector:10};
const field:Record<WeightKey,keyof Row>={volume:'volumeScore',news:'newsScore',supply:'supplyScore',chart:'chartScore',disclosure:'disclosureScore',sector:'sectorScore'};
const labels:Record<WeightKey,string>={volume:'거래량',news:'뉴스',supply:'수급',chart:'차트',disclosure:'공시',sector:'섹터'};
const pct=(n:any)=>typeof n==='number'&&Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'데이터 없음';
const fmt=(n:any,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:d}):'데이터 없음';
const stage=(v:number)=>v>=85?'강한 전조':v>=70?'전조 집중':v>=50?'이상징후':v>=30?'관심':'관찰';
function scoreRow(r:Row,w:Weights){let earned=0,possible=0;for(const k of Object.keys(w) as WeightKey[]){const v=r[field[k]] as number|null|undefined;if(typeof v==='number'){earned+=Math.max(0,Math.min(1,v/rawMax[k]))*w[k];possible+=w[k];}}const base=possible?earned/possible*100:0;const final=Math.max(0,Math.min(100,base+(r.penalty||0)));return {...r,finalScore:+final.toFixed(1),coverage:+possible.toFixed(1),stage:stage(final)};}
function features(r:Row){const o:any={};for(const k of Object.keys(rawMax) as WeightKey[]){const v=r[field[k]] as any;if(typeof v==='number')o[k]=Math.max(0,Math.min(1,v/rawMax[k]));}return o;}

export default function DashboardV5(){
 const [tab,setTab]=useState<Tab>('top'),[universe,setUniverse]=useState<Stock[]>([]),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const [period,setPeriod]=useState(120),[thr,setThr]=useState({d1:5,d3:8,d5:10,d10:15}),[progress,setProgress]=useState({done:0,total:0,ok:0,fail:0,start:0});
 const [weights,setWeights]=useState<Weights>(BASE_WEIGHTS),[learning,setLearning]=useState<any>(null),[round,setRound]=useState(0),[tracking,setTracking]=useState<any[]>([]),[selected,setSelected]=useState<Row|null>(null),[bars,setBars]=useState<any[]>([]);
 const [db,setDb]=useState<{configured:boolean;detections:number;learningRuns:number;updatedAt?:string;note?:string}>({configured:false,detections:0,learningRuns:0,note:'확인 중'});

 useEffect(()=>{(async()=>{try{const r=await fetch('/api/v5/state',{cache:'no-store'});const j=await r.json();if(j.configured){setWeights({...BASE_WEIGHTS,...j.weights});setLearning(j.learning||null);setRound(Number(j.round||0));setTracking(Array.isArray(j.detections)?j.detections:[]);setDb({configured:true,detections:Number(j.counts?.detections||0),learningRuns:Number(j.counts?.learning_runs||0),updatedAt:j.updatedAt,note:'Neon 서버 DB 연결됨'});setMsg(`Neon DB 연결 완료 · 저장 탐지 ${Number(j.counts?.detections||0)}건`);}else{setDb({configured:false,detections:0,learningRuns:0,note:j.error||j.reason||'Neon DB 미연결'});const w=JSON.parse(localStorage.getItem('psr_v5_weights')||'null');if(w)setWeights({...BASE_WEIGHTS,...w});const t=JSON.parse(localStorage.getItem('psr_v5_tracking')||'[]');if(Array.isArray(t))setTracking(t);setMsg('Neon DB가 아직 연결되지 않아 임시 로컬 저장 모드입니다.');}}catch{setMsg('DB 상태 확인 실패 · 임시 로컬 저장 모드');}try{const u=JSON.parse(localStorage.getItem('psr_v5_universe')||'null');if(u&&Date.now()-u.ts<6*3600000)setUniverse(u.stocks||[]);const r=JSON.parse(localStorage.getItem('psr_v5_latest')||'[]');if(Array.isArray(r))setRows(r);}catch{}})()},[]);

 async function persist(w=weights,l=learning,rnd=round,dets=tracking){
  localStorage.setItem('psr_v5_weights',JSON.stringify(w));localStorage.setItem('psr_v5_tracking',JSON.stringify(dets.slice(-500)));localStorage.setItem('psr_v5_learning',JSON.stringify(l||null));
  if(!db.configured)return;
  try{const r=await fetch('/api/v5/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({weights:w,learning:l,round:rnd,detections:dets.slice(-250)})});const j=await r.json();if(r.ok&&j.configured)setDb(x=>({...x,detections:Number(j.counts?.detections??x.detections),learningRuns:Number(j.counts?.learning_runs??x.learningRuns),updatedAt:new Date().toISOString(),note:'Neon 서버 DB 저장 정상'}));}
  catch{setDb(x=>({...x,note:'Neon DB 저장 재시도 필요'}));}
 }

 async function loadUniverse(force=false){if(universe.length&&!force)return universe;setMsg('KOSPI 500 + KOSDAQ 300 종목목록 수집 중…');const r=await fetch('/api/universe',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.stocks?.length)throw new Error(j.error||'종목목록 수집 실패');setUniverse(j.stocks);localStorage.setItem('psr_v5_universe',JSON.stringify({ts:Date.now(),stocks:j.stocks}));setMsg(`종목목록 ${j.stocks.length}개 준비 완료`);return j.stocks as Stock[];}

 async function updateTracking(base=tracking){if(!base.length)return base;const recent=base.slice(-80);let fresh:any[]=[];for(let i=0;i<recent.length;i+=20){try{const r=await fetch('/api/performance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({detections:recent.slice(i,i+20)})});const j=await r.json();if(r.ok)fresh.push(...(j.results||[]));}catch{}}
  if(!fresh.length)return base;const m=new Map(fresh.map((x:any)=>[`${x.date}-${x.code}`,x]));const merged=base.map(x=>m.get(`${x.date}-${x.code}`)||x);setTracking(merged);await persist(weights,learning,round,merged);return merged;
 }

 async function autoLearn(source:Row[],tracked:any[]){const stats=source.filter(x=>x.dataStatus==='ok').map(x=>x.stats).filter(Boolean);const r=await fetch('/api/learn',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stats,tracking:tracked.slice(-200),previous:weights})});const j=await r.json();if(!r.ok)throw new Error(j.error||'자동학습 실패');const nw={...BASE_WEIGHTS,...j.weights} as Weights;const nr=round+1;const rec={...j,round:nr};setWeights(nw);setLearning(rec);setRound(nr);return {weights:nw,learning:rec,round:nr};}

 function buildDetections(source:Row[],w:Weights,base:any[]){const day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});const old=[...base];const keys=new Set(old.map(x=>`${x.date}-${x.code}`));for(const r of source.filter(x=>x.dataStatus==='ok').slice(0,80)){const k=`${day}-${r.code}`;if(!keys.has(k)){old.push({date:day,code:r.code,name:r.name,market:r.market,price:r.currentPrice,score:r.finalScore,features:features(r),weights:w});keys.add(k);}}return old.slice(-500);}

 async function scan(){setBusy(true);setRows([]);setMsg('V5 분석 준비 중…');try{const stocks=await loadUniverse();const started=Date.now();setProgress({done:0,total:stocks.length,ok:0,fail:0,start:started});let all:Row[]=[];
  for(let i=0;i<stocks.length;i+=12){const batch=stocks.slice(i,i+12);const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:batch,period,thresholds:thr})});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 API 실패');all.push(...(j.results||[]));const scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);setProgress({done:all.length,total:stocks.length,ok:all.filter(x=>x.dataStatus==='ok').length,fail:all.filter(x=>x.dataStatus!=='ok').length,start:started});setMsg(`${all.length} / ${stocks.length} 가격·거래량·차트 분석`);}
  let scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));const pre=scored.filter(x=>x.dataStatus==='ok').slice(0,80);setMsg('TOP80 후보 뉴스·수급 보강 중…');for(let i=0;i<pre.length;i+=20){const pack=pre.slice(i,i+20);const r=await fetch('/api/enrich',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:pack})});if(!r.ok)continue;const j=await r.json();const map=new Map((j.results||[]).map((x:any)=>[x.code,x]));all=all.map(x=>{const e:any=map.get(x.code);return e?{...x,...e}:x;});scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);}
  setMsg('과거 백테스트 + 실제 탐지성과 자동학습 중…');const tracked=await updateTracking(tracking);const learned=await autoLearn(all,tracked);scored=all.map(x=>scoreRow(x,learned.weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);localStorage.setItem('psr_v5_latest',JSON.stringify(scored));const dets=buildDetections(scored,learned.weights,tracked);setTracking(dets);await persist(learned.weights,learned.learning,learned.round,dets);setMsg(`V5 분석·자동학습 완료 · TOP80 저장 · 학습 ${learned.round}회차 · 성공 ${scored.filter(x=>x.dataStatus==='ok').length}`);
 }catch(e){setMsg(e instanceof Error?e.message:'분석 실패');}finally{setBusy(false)}}

 async function refreshTracking(){setMsg('TOP80 탐지 후 실제 성과 갱신 중…');const t=await updateTracking(tracking);if(rows.length){try{const l=await autoLearn(rows,t);const rescored=rows.map(x=>scoreRow(x,l.weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(rescored);localStorage.setItem('psr_v5_latest',JSON.stringify(rescored));await persist(l.weights,l.learning,l.round,t);setMsg('실제 성과 반영 + Neon 저장 + 가중치 재학습 완료');}catch{setMsg('성과는 갱신됐고 학습은 다음 분석 때 재시도합니다.');}}else setMsg('탐지 후 성과 갱신 완료');}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 async function openDetail(r:Row){setSelected(r);setBars([]);try{const x=await fetch(`/api/detail?code=${r.code}&market=${r.market}`);const j=await x.json();if(x.ok)setBars(j.bars||[]);}catch{}}

 const filtered=useMemo(()=>{let a=rows.filter(r=>!query||r.name.includes(query)||r.code.includes(query));if(tab==='top')return a.filter(r=>r.dataStatus==='ok').slice(0,80);if(tab==='30')return a.filter(r=>(r.finalScore||0)>=30);if(tab==='50')return a.filter(r=>(r.finalScore||0)>=50);if(tab==='70')return a.filter(r=>(r.finalScore||0)>=70);return a;},[rows,query,tab]);
 const events=useMemo(()=>rows.flatMap(r=>(r.events||[]).map((e:any)=>({...e,name:r.name,code:r.code}))).sort((a,b)=>String(b.date).localeCompare(String(a.date))),[rows]);
 const elapsed=progress.start?Math.round((Date.now()-progress.start)/1000):0;
 function exportXlsx(){const src=filtered.length?filtered:rows;const data=src.map(r=>({종목명:r.name,코드:r.code,시장:r.market,현재가:r.currentPrice,등락률:r.changePct,'5일수익률':r.ret5,자동학습점수:r.finalScore,단계:r.stage,거래량:r.volumeScore,뉴스:r.newsScore,수급:r.supplyScore,차트:r.chartScore,공시:r.disclosureScore,섹터:r.sectorScore,급등감점:r.penalty,커버리지:r.coverage,거래량가중치:weights.volume,뉴스가중치:weights.news,수급가중치:weights.supply,차트가중치:weights.chart,공시가중치:weights.disclosure,섹터가중치:weights.sector,탐지일:r.detectedAt?.slice(0,10)||''}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'자동학습V5');XLSX.writeFile(wb,`급등전조_자동학습V5_${new Date().toISOString().slice(0,10)}.xlsx`);}

 return <main className="app"><header className="hero"><div><div className="eyebrow">KOREA PRE-SPIKE AUTO-LEARNING RADAR V5 · NEON DB</div><h1>급등 전조 자동학습 레이더 V5</h1><p>TOP80 탐지 · 과거/실전 성과 학습 · Neon 서버 DB 누적 저장</p></div><button className="ghost" onClick={logout}>로그아웃</button></header>
 <nav className="tabs">{([['top','오늘의 전조 TOP80'],['all','전체 800종목'],['30','30점 이상'],['50','50점 이상'],['70','70점 이상'],['engine','자동학습 엔진'],['history','과거 급등 학습'],['track','탐지 후 성과'],['settings','설정']] as [Tab,string][]).map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 <section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목명/코드 검색"/><button className="primary" onClick={scan} disabled={busy}>{busy?'분석·학습 중…':'800종목 분석 + 자동학습'}</button><button onClick={()=>loadUniverse(true)} disabled={busy}>종목목록 새로고침</button><button onClick={exportXlsx} disabled={!rows.length}>Excel .xlsx</button></section>
 <div className={`status ${db.configured?'dbOk':'dbWarn'}`}>{db.configured?`● Neon DB 연결 · 탐지 ${db.detections}건 · 학습기록 ${db.learningRuns}건`:`● ${db.note||'Neon DB 미연결'} · 임시 로컬 저장`}</div>
 {(busy||progress.done>0)&&<section className="progress"><div className="progressHead"><b>{progress.done} / {progress.total||800}</b><span>성공 {progress.ok} · 실패 {progress.fail} · {elapsed}초</span></div><div className="bar"><i style={{width:`${progress.total?progress.done/progress.total*100:0}%`}}/></div></section>}
 {msg&&<div className="status">{msg}</div>}
 {tab==='engine'?<Engine weights={weights} learning={learning} round={round} db={db}/>:tab==='history'?<History events={events}/>:tab==='track'?<Track tracking={tracking} refresh={refreshTracking}/>:tab==='settings'?<Settings period={period} setPeriod={setPeriod} thr={thr} setThr={setThr}/>:<Results title={tab==='top'?'아직 크게 오르지 않은 급등 전조 TOP 80':tab==='all'?'전체 분석 종목':`${tab}점 이상`} rows={filtered} open={openDetail}/>} 
 {selected&&<Detail row={selected} bars={bars} close={()=>setSelected(null)}/>}<footer>V5 점수는 상승 확률이 아닙니다. 서버 DB에는 원시 시세 전체가 아니라 탐지·성과·가중치만 제한적으로 저장합니다.</footer></main>;
}

function Results({title,rows,open}:{title:string;rows:Row[];open:(r:Row)=>void}){return <section><div className="sectionTitle"><h2>{title}</h2><span>{rows.length}종목</span></div>{!rows.length?<div className="empty">아직 분석 결과가 없습니다.</div>:<div className="cards">{rows.map((r,i)=><article className="stockCard" key={`${r.market}-${r.code}`} onClick={()=>open(r)}><div className="rank">{i+1}</div><div className="stockMain"><div><b>{r.name}</b><span>{r.code} · {r.market}</span></div><div className="price"><b>{fmt(r.currentPrice)}</b><span className={(r.changePct||0)>=0?'up':'down'}>{pct(r.changePct)}</span></div></div><div className="scoreHero"><strong>{fmt(r.finalScore,1)}</strong><span>{r.stage} · 데이터 {fmt(r.coverage,0)}%</span></div><div className="miniGrid"><label>5일 <b>{pct(r.ret5)}</b></label><label>거래량 <b>{fmt(r.volumeScore,1)}</b></label><label>뉴스 <b>{fmt(r.newsScore,1)}</b></label><label>수급 <b>{fmt(r.supplyScore,1)}</b></label><label>차트 <b>{fmt(r.chartScore,1)}</b></label><label>공시 <b>{fmt(r.disclosureScore,1)}</b></label><label>섹터 <b>{fmt(r.sectorScore,1)}</b></label><label>급등감점 <b>{fmt(r.penalty,0)}</b></label></div>{r.dataStatus==='error'&&<div className="errorBox">{r.error||'데이터 수집 실패'}</div>}</article>)}</div>}</section>}

function Engine({weights,learning,round,db}:{weights:Weights;learning:any;round:number;db:any}){const h=learning?.metrics?.historical;return <section className="panel"><h2>자동학습 엔진 · {round}회차</h2><div className="stats">{(Object.keys(weights) as WeightKey[]).map(k=><article key={k}><span>{labels[k]} 가중치</span><b>{weights[k].toFixed(1)}</b></article>)}</div><div className="metricCard"><h3>서버 저장</h3><div className="metricGrid"><span>Neon DB<b>{db.configured?'연결됨':'미연결'}</b></span><span>탐지 저장<b>{db.detections||0}건</b></span><span>학습 스냅샷<b>{db.learningRuns||0}건</b></span><span>저장 제한<b>탐지 5,000건</b></span></div></div>{h&&<div className="metricCard"><h3>과거 검증</h3><div className="metricGrid"><span>거래량 Precision<b>{(Number(h.volume?.precision||0)*100).toFixed(1)}%</b></span><span>거래량 FPR<b>{(Number(h.volume?.fpr||0)*100).toFixed(1)}%</b></span><span>차트 Precision<b>{(Number(h.chart?.precision||0)*100).toFixed(1)}%</b></span><span>차트 FPR<b>{(Number(h.chart?.fpr||0)*100).toFixed(1)}%</b></span></div></div>}<p className="note">새 가중치는 이전값 70% + 새 학습값 30%로 완만하게 반영됩니다. Neon에는 원시 일봉 800종목 전체를 저장하지 않고 TOP80 탐지·성과와 학습 요약만 보관해 무료 사용량을 아끼도록 설계했습니다.</p></section>}

function History({events}:{events:any[]}){return <section className="panel"><h2>과거 급등 학습</h2><div className="tableWrap"><table><thead><tr><th>종목</th><th>급등일</th><th>급등폭</th><th>D-20</th><th>D-10</th><th>D-5</th><th>D-1</th></tr></thead><tbody>{events.slice(0,300).map((e,i)=><tr key={i}><td>{e.name}<small>{e.code}</small></td><td>{e.date}</td><td>{fmt(e.spikePct,1)}%</td><td>{e.d20?.score??'-'}</td><td>{e.d10?.score??'-'}</td><td>{e.d5?.score??'-'}</td><td>{e.d1?.score??'-'}</td></tr>)}</tbody></table></div></section>}

function Track({tracking,refresh}:{tracking:any[];refresh:()=>void}){return <section className="panel"><div className="sectionTitle"><h2>탐지 후 성과</h2><button onClick={refresh}>성과 갱신 + 재학습</button></div><div className="tableWrap"><table><thead><tr><th>종목</th><th>탐지일</th><th>점수</th><th>1일</th><th>5일</th><th>10일</th><th>20일</th><th>20일 MFE</th></tr></thead><tbody>{[...tracking].reverse().slice(0,500).map((x:any,i)=><tr key={`${x.date}-${x.code}-${i}`}><td>{x.name}<small>{x.code}</small></td><td>{x.date}</td><td>{fmt(x.score,1)}</td><td>{pct(x.r1)}</td><td>{pct(x.r5)}</td><td>{pct(x.r10)}</td><td>{pct(x.r20)}</td><td>{pct(x.mfe20)}</td></tr>)}</tbody></table></div></section>}

function Settings({period,setPeriod,thr,setThr}:{period:number;setPeriod:(n:number)=>void;thr:any;setThr:(x:any)=>void}){return <section className="panel"><h2>설정</h2><p>분석 기간</p><div className="choice">{[30,60,90,120].map(n=><button key={n} className={period===n?'active':''} onClick={()=>setPeriod(n)}>{n}거래일</button>)}</div><div className="settingsGrid"><label>1일 급등 기준<div><input type="range" min="1" max="30" step="1" value={thr.d1} onChange={e=>setThr({...thr,d1:+e.target.value})}/><b>{thr.d1}%</b></div></label><label>3일 누적<div><input type="range" min="1" max="30" step="1" value={thr.d3} onChange={e=>setThr({...thr,d3:+e.target.value})}/><b>{thr.d3}%</b></div></label><label>5일 누적<div><input type="range" min="1" max="40" step="1" value={thr.d5} onChange={e=>setThr({...thr,d5:+e.target.value})}/><b>{thr.d5}%</b></div></label><label>10일 누적<div><input type="range" min="1" max="50" step="1" value={thr.d10} onChange={e=>setThr({...thr,d10:+e.target.value})}/><b>{thr.d10}%</b></div></label></div></section>}

function Detail({row,bars,close}:{row:Row;bars:any[];close:()=>void}){const reasons=[...(row.reasons||[]),...(row.newsReasons||[]),...(row.supplyReasons||[])];return <div className="modalBack" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><h2>{row.name} <small>{row.code} · {row.market}</small></h2><div className="detailHero"><div><span>자동학습 점수</span><b>{fmt(row.finalScore,1)}</b><small>{row.stage}</small></div><div><span>현재가</span><b>{fmt(row.currentPrice)}</b><small>{pct(row.changePct)}</small></div></div><h3>이 종목을 포착한 이유</h3>{reasons.length?<ul className="reasons">{reasons.map((x,i)=><li key={i}>{x}</li>)}</ul>:<div className="empty">계산된 상세 이유 없음</div>}<h3>120거래일 차트</h3><PriceChart bars={bars.slice(-120)} marks={(row.events||[]).map((e:any)=>e.date)}/></section></div>}
