'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import PriceChart from './PriceChart';

type Stock={name:string;code:string;market:'KOSPI'|'KOSDAQ';currentPrice:number|null;changePct:number|null;marketCap:number|null;sector:string|null;theme:string|null};
type Row=Stock&{ret5?:number;volumeScore?:number|null;newsScore?:number|null;supplyScore?:number|null;chartScore?:number|null;disclosureScore?:number|null;sectorScore?:number|null;penalty?:number;reasons?:string[];newsReasons?:string[];supplyReasons?:string[];news?:any[];detectedAt?:string;dataStatus?:string;error?:string;events?:any[];stats?:any;finalScore?:number;coverage?:number;stage?:string};
type Tab='top'|'all'|'30'|'50'|'70'|'learn'|'signals'|'track'|'settings';
const maxes:{[k:string]:number}={volumeScore:25,newsScore:20,supplyScore:15,chartScore:15,disclosureScore:15,sectorScore:10};
function calc(r:Row){let raw=0,max=0;for(const [k,m] of Object.entries(maxes)){const v=(r as any)[k];if(typeof v==='number'){raw+=v;max+=m;}}const normalized=max?raw/max*100:0;const final=Math.max(0,Math.min(100,normalized+(r.penalty||0)));return {...r,finalScore:Math.round(final*10)/10,coverage:Math.round(max),stage:final>=85?'강한 전조':final>=70?'전조 집중':final>=50?'이상징후':final>=30?'관심':'관찰'};}
const fmt=(n:any,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:d}):'데이터 없음';
const pct=(n:any)=>typeof n==='number'?`${n>=0?'+':''}${n.toFixed(2)}%`:'데이터 없음';

export default function Dashboard(){
 const [tab,setTab]=useState<Tab>('top'),[universe,setUniverse]=useState<Stock[]>([]),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState({done:0,total:0,ok:0,fail:0,start:0}),[period,setPeriod]=useState(120),[thr,setThr]=useState({d1:5,d3:8,d5:10,d10:15}),[msg,setMsg]=useState(''),[selected,setSelected]=useState<Row|null>(null),[bars,setBars]=useState<any[]>([]),[tracking,setTracking]=useState<any[]>([]);
 useEffect(()=>{try{const r=localStorage.getItem('psr_v3_latest');if(r)setRows(JSON.parse(r));const d=localStorage.getItem('psr_v3_tracking');if(d)setTracking(JSON.parse(d));const u=localStorage.getItem('psr_v3_universe');if(u){const x=JSON.parse(u);if(Date.now()-x.ts<6*3600000)setUniverse(x.stocks)}}catch{}},[]);
 async function loadUniverse(force=false){if(universe.length&&!force)return universe;setMsg('네이버 금융에서 KOSPI 500 + KOSDAQ 300 종목목록 수집 중…');const r=await fetch('/api/universe');const j=await r.json();if(!r.ok)throw new Error(j.error||'종목목록 수집 실패');setUniverse(j.stocks||[]);localStorage.setItem('psr_v3_universe',JSON.stringify({ts:Date.now(),stocks:j.stocks||[]}));if(j.errors?.length)setMsg(`종목목록 ${j.stocks.length}개 수집. 일부 페이지 오류 ${j.errors.length}건`);else setMsg(`종목목록 ${j.stocks.length}개 수집 완료`);return j.stocks as Stock[];}
 async function scan(){setBusy(true);setRows([]);setMsg('분석 준비 중…');try{const stocks=await loadUniverse();if(!stocks.length)throw new Error('분석할 종목이 없습니다.');const started=Date.now();setProgress({done:0,total:stocks.length,ok:0,fail:0,start:started});let all:Row[]=[];for(let i=0;i<stocks.length;i+=12){const batch=stocks.slice(i,i+12);const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:batch,period,thresholds:thr})});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 API 실패');all=[...all,...j.results.map((x:Row)=>calc(x))];const ok=all.filter(x=>x.dataStatus==='ok').length;setRows([...all].sort((a,b)=>(b.finalScore||0)-(a.finalScore||0)));setProgress({done:all.length,total:stocks.length,ok,fail:all.length-ok,start:started});setMsg(`${all.length} / ${stocks.length} 분석 완료`);}const pre=[...all].filter(x=>x.dataStatus==='ok').sort((a,b)=>(b.finalScore||0)-(a.finalScore||0)).slice(0,40);setMsg('상위 후보 뉴스·수급 보강 중…');for(let i=0;i<pre.length;i+=20){const pack=pre.slice(i,i+20);const r=await fetch('/api/enrich',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:pack})});if(!r.ok)continue;const j=await r.json();const map=new Map((j.results||[]).map((x:any)=>[x.code,x]));all=all.map(x=>{const e:any=map.get(x.code);return e?calc({...x,...e}):x;});setRows([...all].sort((a,b)=>(b.finalScore||0)-(a.finalScore||0)));}all=[...all].sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(all);localStorage.setItem('psr_v3_latest',JSON.stringify(all));saveDetections(all.slice(0,20));setMsg(`분석 완료: 성공 ${all.filter(x=>x.dataStatus==='ok').length}, 실패 ${all.filter(x=>x.dataStatus!=='ok').length}`);}catch(e){setMsg(e instanceof Error?e.message:'분석 실패');}finally{setBusy(false)}}
 function saveDetections(top:Row[]){const day=new Date().toISOString().slice(0,10);let old:any[]=[];try{old=JSON.parse(localStorage.getItem('psr_v3_tracking')||'[]')}catch{}const keys=new Set(old.map(x=>`${x.date}-${x.code}`));for(const r of top){const k=`${day}-${r.code}`;if(!keys.has(k))old.push({date:day,code:r.code,name:r.name,market:r.market,price:r.currentPrice,score:r.finalScore});}old=old.slice(-120);localStorage.setItem('psr_v3_tracking',JSON.stringify(old));setTracking(old);}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 const filtered=useMemo(()=>{let a=rows.filter(r=>!query||r.name.includes(query)||r.code.includes(query));if(tab==='top')return a.filter(r=>r.dataStatus==='ok').slice(0,20);if(tab==='30')return a.filter(r=>(r.finalScore||0)>=30);if(tab==='50')return a.filter(r=>(r.finalScore||0)>=50);if(tab==='70')return a.filter(r=>(r.finalScore||0)>=70);return a;},[rows,query,tab]);
 function exportXlsx(){const src=filtered.length?filtered:rows;const data=src.map(r=>({종목명:r.name,종목코드:r.code,시장:r.market,현재가:r.currentPrice,등락률:r.changePct,최근5일상승률:r.ret5,최종점수:r.finalScore,거래량점수:r.volumeScore,뉴스점수:r.newsScore,수급점수:r.supplyScore,차트점수:r.chartScore,공시점수:r.disclosureScore,섹터점수:r.sectorScore,급등감점:r.penalty,데이터커버리지:r.coverage,포착이유:[...(r.reasons||[]),...(r.newsReasons||[]),...(r.supplyReasons||[])].join(' | '),뉴스:(r.news||[]).map((n:any)=>`${n.date?.slice(0,10)} ${n.title} ${n.link}`).join('\n'),섹터:r.sector||'데이터 없음',테마:r.theme||'데이터 없음',탐지일:r.detectedAt?.slice(0,10)||''}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'전조레이더');XLSX.writeFile(wb,`급등전조학습레이더V3_${new Date().toISOString().slice(0,10)}.xlsx`);}
 async function openDetail(r:Row){setSelected(r);setBars([]);try{const x=await fetch(`/api/detail?code=${r.code}&market=${r.market}`);const j=await x.json();if(x.ok)setBars(j.bars||[]);}catch{}}
 const events=useMemo(()=>rows.flatMap(r=>(r.events||[]).map((e:any)=>({...e,name:r.name,code:r.code,market:r.market}))).sort((a,b)=>b.date.localeCompare(a.date)),[rows]);
 const leadStats=useMemo(()=>{const pack=(key:'volume'|'chart')=>{const ss=rows.map(r=>r.stats?.[key]).filter(Boolean);const a=ss.reduce((o:any,x:any)=>({tp:o.tp+x.tp,fp:o.fp+x.fp,fn:o.fn+x.fn,tn:o.tn+x.tn,signalCount:o.signalCount+x.signalCount,sumReturn:o.sumReturn+x.sumReturn,maxDrawdown:Math.min(o.maxDrawdown,x.maxDrawdown),medians:[...o.medians,x.medianReturn]}),{tp:0,fp:0,fn:0,tn:0,signalCount:0,sumReturn:0,maxDrawdown:0,medians:[]});const precision=a.tp+a.fp?a.tp/(a.tp+a.fp)*100:0,recall=a.tp+a.fn?a.tp/(a.tp+a.fn)*100:0,fpr=a.fp+a.tn?a.fp/(a.fp+a.tn)*100:0;const med=[...a.medians].sort((x:number,y:number)=>x-y);return {...a,precision,recall,fpr,avgReturn:a.signalCount?a.sumReturn/a.signalCount:0,medianReturn:med.length?med[Math.floor(med.length/2)]:0};};return {n:events.length,volumeLead:events.length?events.filter(e=>e.leads?.volume).length/events.length*100:0,chartLead:events.length?events.filter(e=>e.leads?.chart).length/events.length*100:0,volume:pack('volume'),chart:pack('chart')};},[events,rows]);
 async function refreshTracking(){const recent=tracking.slice(-25);if(!recent.length)return;setMsg('탐지 후 1/3/5/10/20거래일 성과 계산 중…');const r=await fetch('/api/performance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({detections:recent})});const j=await r.json();if(r.ok){setTracking(j.results||[]);setMsg('탐지 후 성과 갱신 완료');}}
 const elapsed=progress.start?Math.round((Date.now()-progress.start)/1000):0;
 return <main className="app"><header className="hero"><div><div className="eyebrow">KOREA PRE-SPIKE LEARNING RADAR V3</div><h1>급등 전조 학습 레이더 V3</h1><p>급등 후 뉴스가 아니라, 급등 전 이상징후를 찾습니다.</p></div><button className="ghost" onClick={logout}>로그아웃</button></header>
 <nav className="tabs">{([['top','오늘의 전조 TOP20'],['all','전체 800종목'],['30','30점 이상'],['50','50점 이상'],['70','70점 이상'],['learn','과거 급등 학습'],['signals','신호별 성과'],['track','탐지 후 성과'],['settings','설정']] as [Tab,string][]).map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 <section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목명/코드 검색"/><button className="primary" onClick={scan} disabled={busy}>{busy?'분석 중…':'800종목 분석 시작'}</button><button onClick={()=>loadUniverse(true)} disabled={busy}>종목목록 새로고침</button><button onClick={exportXlsx} disabled={!rows.length}>Excel .xlsx</button></section>
 {(busy||progress.done>0)&&<section className="progress"><div className="progressHead"><b>{progress.done} / {progress.total||800} 분석 완료</b><span>성공 {progress.ok} · 실패 {progress.fail} · {elapsed}초</span></div><div className="bar"><i style={{width:`${progress.total?progress.done/progress.total*100:0}%`}}/></div></section>}
 {msg&&<div className="status">{msg}</div>}
 {tab==='settings'?<Settings period={period} setPeriod={setPeriod} thr={thr} setThr={setThr}/>:tab==='learn'?<Learning events={events}/>:tab==='signals'?<Signals stats={leadStats}/>:tab==='track'?<Tracking rows={tracking} refresh={refreshTracking}/>:<Results title={tab==='top'?'아직 크게 오르지 않은 급등 전조 TOP 20':tab==='all'?'전체 분석 종목':`${tab}점 이상`} rows={filtered} open={openDetail}/>} 
 {selected&&<Detail row={selected} bars={bars} close={()=>setSelected(null)}/>}<footer>이 점수는 상승 확률이 아닙니다. 과거 급등 전 반복된 이상 패턴을 현재 시장에서 탐지하는 학습용 지표입니다.</footer></main>
}
function Score({v,max}:{v:any,max:number}){return <span className={typeof v==='number'?'score':'score missing'}>{typeof v==='number'?`${v}/${max}`:'없음'}</span>}
function Results({title,rows,open}:{title:string;rows:Row[];open:(r:Row)=>void}){return <section><div className="sectionTitle"><h2>{title}</h2><span>{rows.length}종목</span></div>{!rows.length?<div className="empty">아직 분석 결과가 없습니다.</div>:<div className="cards">{rows.map((r,i)=><article className="stockCard" key={`${r.market}-${r.code}`} onClick={()=>open(r)}><div className="rank">{i+1}</div><div className="stockMain"><div><b>{r.name}</b><span>{r.code} · {r.market}</span></div><div className="price"><b>{fmt(r.currentPrice)}</b><span className={(r.changePct||0)>=0?'up':'down'}>{pct(r.changePct)}</span></div></div><div className="scoreHero"><strong>{fmt(r.finalScore,1)}</strong><span>{r.stage} · 데이터 {r.coverage||0}%</span></div><div className="miniGrid"><label>5일 <b>{pct(r.ret5)}</b></label><label>거래량 <Score v={r.volumeScore} max={25}/></label><label>뉴스 <Score v={r.newsScore} max={20}/></label><label>수급 <Score v={r.supplyScore} max={15}/></label><label>차트 <Score v={r.chartScore} max={15}/></label><label>공시 <Score v={r.disclosureScore} max={15}/></label><label>섹터 <Score v={r.sectorScore} max={10}/></label><label>급등감점 <b>{r.penalty||0}</b></label></div>{r.dataStatus==='error'&&<div className="errorBox">데이터 수집 실패: {r.error}</div>}<div className="detected">탐지 {r.detectedAt?.slice(0,16).replace('T',' ')||'-'}</div></article>)}</div>}</section>}
function Settings({period,setPeriod,thr,setThr}:any){return <section className="panel"><h2>설정</h2><h3>분석기간</h3><div className="choice">{[30,60,90,120].map(x=><button className={period===x?'active':''} key={x} onClick={()=>setPeriod(x)}>최근 {x}거래일</button>)}</div><h3>급등 사례 기준</h3><div className="settingsGrid">{[['d1','1거래일'],['d3','3거래일 누적'],['d5','5거래일 누적'],['d10','10거래일 누적']].map(([k,l])=><label key={k}>{l}<div><input type="range" min="1" max="30" value={thr[k]} onChange={e=>setThr({...thr,[k]:Number(e.target.value)})}/><b>+{thr[k]}%</b></div></label>)}</div><div className="note">기본값 5% / 8% / 10% / 15%. 과거 이벤트의 D-60~D-1만 사용하며 미래 데이터는 점수 계산에 넣지 않습니다.</div></section>}
function Learning({events}:{events:any[]}){return <section className="panel"><div className="sectionTitle"><h2>과거 급등 학습</h2><span>{events.length} 이벤트</span></div><div className="tableWrap"><table><thead><tr><th>종목</th><th>급등일</th><th>급등률</th><th>D-30</th><th>D-20</th><th>D-10</th><th>D-5</th><th>D-3</th><th>D-1</th></tr></thead><tbody>{events.slice(0,500).map((e,i)=><tr key={i}><td>{e.name}<small>{e.code}</small></td><td>{e.date}</td><td>{pct(e.spikePct)}</td>{[30,20,10,5,3,1].map(x=><td key={x}>{e[`d${x}`]?.score??'-'}</td>)}</tr>)}</tbody></table></div>{!events.length&&<div className="empty">분석을 실행하면 Yahoo 과거가격으로 급등 사례가 자동 생성됩니다.</div>}</section>}
function Signals({stats}:{stats:any}){const R=({name,x,lead}:{name:string,x:any,lead:number})=><article className="metricCard"><h3>{name}</h3><div className="metricGrid"><span>급등 전 선행률 <b>{lead.toFixed(1)}%</b></span><span>Precision <b>{x.precision.toFixed(1)}%</b></span><span>Recall <b>{x.recall.toFixed(1)}%</b></span><span>False Positive <b>{x.fpr.toFixed(1)}%</b></span><span>평균 향후 10일 수익률 <b>{pct(x.avgReturn)}</b></span><span>중앙값 향후 10일 수익률 <b>{pct(x.medianReturn)}</b></span><span>최대낙폭 <b>{pct(x.maxDrawdown)}</b></span><span>신호 표본 <b>{x.signalCount}</b></span></div></article>;return <section className="panel"><h2>신호별 성과</h2><div className="stats"><article><span>급등 사례</span><b>{stats.n}</b></article><article><span>거래량 선행</span><b>{stats.volumeLead.toFixed(1)}%</b></article><article><span>차트 선행</span><b>{stats.chartLead.toFixed(1)}%</b></article></div><R name="거래량 이상 신호" x={stats.volume} lead={stats.volumeLead}/><R name="차트 선행 신호" x={stats.chart} lead={stats.chartLead}/><div className="note">가격·거래량 신호는 급등 구간과 비급등 대조군을 함께 계산합니다. 뉴스·공시·섹터의 과거시점 통계는 역사 데이터 API가 연결되기 전까지 임의 생성하지 않습니다. 자동 가중치 변경은 충분한 표본이 쌓인 뒤 적용하도록 분리되어 있습니다.</div></section>}
function Tracking({rows,refresh}:{rows:any[];refresh:()=>void}){return <section className="panel"><div className="sectionTitle"><h2>탐지 후 성과</h2><button onClick={refresh}>성과 갱신</button></div><div className="tableWrap"><table><thead><tr><th>탐지일</th><th>종목</th><th>점수</th><th>1일</th><th>3일</th><th>5일</th><th>10일</th><th>20일</th><th>20일 MFE</th><th>20일 MAE</th></tr></thead><tbody>{rows.slice().reverse().map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.name}<small>{r.code}</small></td><td>{r.score}</td>{[1,3,5,10,20].map(x=><td key={x}>{r[`r${x}`]===undefined?'-':pct(r[`r${x}`])}</td>)}<td>{r.mfe20===undefined?'-':pct(r.mfe20)}</td><td>{r.mae20===undefined?'-':pct(r.mae20)}</td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty">TOP20 탐지 결과가 저장되면 이후 1·3·5·10·20거래일 성과를 추적합니다.</div>}</section>}
function Detail({row,bars,close}:{row:Row;bars:any[];close:()=>void}){const reasons=[...(row.reasons||[]),...(row.newsReasons||[]),...(row.supplyReasons||[])];return <div className="modalBack" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal"><button className="close" onClick={close}>×</button><div className="eyebrow">SIGNAL DETAIL</div><h2>{row.name} <small>{row.code} · {row.market}</small></h2><div className="detailHero"><div><span>Pre-Spike Score</span><b>{fmt(row.finalScore,1)}</b><small>{row.stage} · 데이터 커버리지 {row.coverage}%</small></div><div><span>현재가</span><b>{fmt(row.currentPrice)}</b><small>{pct(row.changePct)} · 5일 {pct(row.ret5)}</small></div></div><h3>이 종목을 포착한 이유</h3>{reasons.length?<ul className="reasons">{reasons.map((x,i)=><li key={i}>{x}</li>)}</ul>:<div className="empty">계산 가능한 선행 신호가 충분하지 않습니다.</div>}<div className="miniGrid detailScores"><label>거래량 <Score v={row.volumeScore} max={25}/></label><label>뉴스 <Score v={row.newsScore} max={20}/></label><label>수급 <Score v={row.supplyScore} max={15}/></label><label>차트 <Score v={row.chartScore} max={15}/></label><label>공시 <Score v={row.disclosureScore} max={15}/></label><label>섹터 <Score v={row.sectorScore} max={10}/></label><label>급등 감점 <b>{row.penalty||0}</b></label><label>최종 <b>{row.finalScore}</b></label></div><h3>최근 120거래일</h3><PriceChart bars={bars} marks={(row.events||[]).map((e:any)=>e.date)}/><h3>뉴스</h3>{row.news?.length?<div className="newsList">{row.news.map((n:any,i:number)=><a key={i} href={n.link} target="_blank" rel="noreferrer"><time>{n.date?.slice(0,10)}</time>{n.title}</a>)}</div>:<div className="empty">뉴스 데이터 없음 또는 API 미연결</div>}<h3>섹터 / 테마</h3><p>{row.sector||'데이터 없음'} / {row.theme||'데이터 없음'}</p></section></div>}
