'use client';
import {useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import PriceChart from './PriceChart';

type Stock={name:string;code:string;market:'KOSDAQ';currentPrice:number|null;changePct:number|null;marketCap:number|null};
type Row=Stock&{stage?:string;dataStatus?:string;error?:string;age?:number;belowCount?:number;spikeDate?:string;spikeRet?:number;spikeVolume?:number;spikeVolRatio?:number;firstBelowDate?:string;signalDate?:string;signalClose?:number;ma5?:number;ma20?:number;ma60?:number;ma20Gap?:number;pullback?:number;score?:number;structureOk?:boolean;bars?:any[]};
const fmt=(n:any,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:d}):'-';
const pct=(n:any)=>typeof n==='number'&&Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'-';
export default function Dashboard(){
 const [universe,setUniverse]=useState<Stock[]>([]),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[done,setDone]=useState(0),[query,setQuery]=useState(''),[tab,setTab]=useState<'buy'|'wait'|'near'|'all'>('buy'),[selected,setSelected]=useState<Row|null>(null),[detailBars,setDetailBars]=useState<any[]>([]);
 const [p,setP]=useState({lookback:20,spikePct:7,volRatio:3,waitDays:3,mode:'relaxed',maxAfterSpike:15,ma20Distance:10,pullbackMin:-25,pullbackMax:8});
 async function loadUniverse(){setMsg('네이버 금융에서 코스닥 전종목 목록 수집 중…');const r=await fetch('/api/universe');const j=await r.json();if(!r.ok)throw new Error(j.error||'종목목록 수집 실패');setUniverse(j.stocks||[]);setMsg(`코스닥 ${j.stocks?.length||0}종목 수집 완료 · ${j.source||''}`);return j.stocks as Stock[];}
 async function scan(){setBusy(true);setRows([]);setDone(0);try{const stocks=universe.length?universe:await loadUniverse();if(!stocks.length)throw new Error('종목 목록이 없습니다.');const batches=[];for(let i=0;i<stocks.length;i+=24)batches.push(stocks.slice(i,i+24));let next=0;let all:Row[]=[];async function worker(){while(true){const idx=next++;if(idx>=batches.length)return;const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:batches[idx],params:p})});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 API 실패');all=[...all,...(j.results||[])];setRows([...all]);setDone(Math.min(stocks.length,all.length));}}await Promise.all([worker(),worker(),worker()]);setRows(all);setMsg(`분석 완료 · 매수후보 ${all.filter(x=>x.stage==='buy').length} · 대기 ${all.filter(x=>x.stage==='wait').length} · 오류 ${all.filter(x=>x.dataStatus==='error').length}`);}catch(e){setMsg(e instanceof Error?e.message:'분석 실패');}finally{setBusy(false)}}
 async function openDetail(r:Row){setSelected(r);setDetailBars([]);try{const q=await fetch(`/api/detail?code=${r.code}&market=KOSDAQ`);const j=await q.json();if(q.ok)setDetailBars(j.bars||[]);}catch{}}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 const filtered=useMemo(()=>rows.filter(r=>(!query||r.name.includes(query)||r.code.includes(query))&&(tab==='all'||(tab==='buy'?r.stage==='buy':tab==='wait'?r.stage==='wait':r.stage!=='none'&&r.stage!=='error'&&r.stage!=='buy'&&r.stage!=='wait'))).sort((a,b)=>(b.score||0)-(a.score||0)),[rows,query,tab]);
 function exportXlsx(){const data=filtered.map(r=>({종목명:r.name,코드:r.code,단계:r.stage==='buy'?'3일째 매수후보':r.stage==='wait'?`${r.age}일째 대기`:r.stage,신호점수:r.score,급등일:r.spikeDate,급등률:r.spikeRet,급등일거래량:r.spikeVolume,거래량배수:r.spikeVolRatio,눌림시작일:r.firstBelowDate,판정일:r.signalDate,종가:r.signalClose,MA5:r.ma5,MA20:r.ma20,MA60:r.ma60,MA20괴리율:r.ma20Gap,급등후등락률:r.pullback,하회일수:r.age}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'코스닥5일선3일째');XLSX.writeFile(wb,`코스닥_대량거래급등후_5일선_${new Date().toISOString().slice(0,10)}.xlsx`);}
 return <main className="app"><header className="hero"><div><div className="eyebrow">KOSDAQ 5MA THIRD-DAY RADAR</div><h1>코스닥 대량거래 급등 후 5일선 3일째 레이더</h1><p>앞선 대량거래 급등 → 5일선 아래 눌림 → 기본값 3거래일째 종가를 자동 탐지합니다.</p></div><button className="ghost" onClick={logout}>로그아웃</button></header>
 <section className="logic"><b>기본 판정</b><span>최근 {p.lookback}거래일 안에 +{p.spikePct}% 이상 급등</span><span>직전 20일 평균 대비 거래량 {p.volRatio}배 이상</span><span>급등 후 5일선 하회</span><span>{p.waitDays}거래일째 종가</span><span>20일선 ±{p.ma20Distance}% 이내</span></section>
 <section className="settings"><Num label="검색기간" value={p.lookback} min={10} max={60} step={1} unit="일" set={v=>setP({...p,lookback:v})}/><Num label="급등 기준" value={p.spikePct} min={2} max={20} step={0.5} unit="%" set={v=>setP({...p,spikePct:v})}/><Num label="거래량 배수" value={p.volRatio} min={1.2} max={15} step={0.1} unit="배" set={v=>setP({...p,volRatio:v})}/><Num label="매수 대기" value={p.waitDays} min={2} max={7} step={1} unit="일째" set={v=>setP({...p,waitDays:v})}/><Num label="급등 후 최대" value={p.maxAfterSpike} min={3} max={30} step={1} unit="일" set={v=>setP({...p,maxAfterSpike:v})}/><Num label="20일선 허용" value={p.ma20Distance} min={1} max={25} step={1} unit="%" set={v=>setP({...p,ma20Distance:v})}/><label className="mode"><span>5일선 판정</span><select value={p.mode} onChange={e=>setP({...p,mode:e.target.value})}><option value="relaxed">완화형(중간 1회 재진입 허용)</option><option value="strict">엄격형(연속 하회)</option></select></label></section>
 <section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목명 / 코드 검색"/><button className="primary" onClick={scan} disabled={busy}>{busy?'코스닥 전종목 분석 중…':'코스닥 전종목 스크리닝'}</button><button onClick={()=>loadUniverse()} disabled={busy}>종목목록 새로고침</button><button onClick={exportXlsx} disabled={!filtered.length}>Excel .xlsx</button></section>
 {(busy||done>0)&&<div className="progress"><div><b>{done} / {universe.length||'전종목'}</b><span>{universe.length?Math.round(done/universe.length*100):0}%</span></div><i><em style={{width:`${universe.length?done/universe.length*100:0}%`}}/></i></div>}{msg&&<div className="status">{msg}</div>}
 <nav className="tabs"><button className={tab==='buy'?'active':''} onClick={()=>setTab('buy')}>오늘 3일째 매수후보 <b>{rows.filter(x=>x.stage==='buy').length}</b></button><button className={tab==='wait'?'active':''} onClick={()=>setTab('wait')}>1~2일째 대기 <b>{rows.filter(x=>x.stage==='wait').length}</b></button><button className={tab==='near'?'active':''} onClick={()=>setTab('near')}>조건근접</button><button className={tab==='all'?'active':''} onClick={()=>setTab('all')}>전체 결과</button></nav>
 <section className="tableWrap"><table><thead><tr><th>종목</th><th>단계</th><th>점수</th><th>급등일</th><th>급등률</th><th>거래량 배수</th><th>눌림 시작</th><th>현재/판정 종가</th><th>MA5</th><th>MA20</th><th>20일선 괴리</th><th>급등후 등락</th></tr></thead><tbody>{filtered.map(r=><tr key={r.code} onClick={()=>openDetail(r)} className={r.stage==='buy'?'buyRow':''}><td><b>{r.name}</b><small>{r.code}</small></td><td><Stage r={r}/></td><td><strong>{fmt(r.score)}</strong></td><td>{r.spikeDate||'-'}</td><td className={(r.spikeRet||0)>=0?'up':'down'}>{pct(r.spikeRet)}</td><td>{fmt(r.spikeVolRatio,1)}배</td><td>{r.firstBelowDate||'-'}</td><td>{fmt(r.signalClose)}</td><td>{fmt(r.ma5)}</td><td>{fmt(r.ma20)}</td><td>{pct(r.ma20Gap)}</td><td className={(r.pullback||0)>=0?'up':'down'}>{pct(r.pullback)}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">조건에 맞는 종목이 아직 없습니다. 스크리닝을 실행하거나 조건을 조금 완화해 보세요.</div>}</section>
 {selected&&<Detail row={selected} bars={detailBars} close={()=>setSelected(null)}/>}<footer>이 사이트의 ‘매수후보’는 사용자가 지정한 차트 규칙과 일치한다는 뜻이며 상승을 보장하지 않습니다. 종가 확정 데이터 기준으로 사용하세요.</footer></main>}
function Num({label,value,min,max,step,unit,set}:{label:string;value:number;min:number;max:number;step:number;unit:string;set:(n:number)=>void}){return <label className="num"><span>{label}</span><div><input type="number" value={value} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/><b>{unit}</b></div></label>}
function Stage({r}:{r:Row}){if(r.stage==='buy')return <span className="badge buy">● {r.age}일째 매수후보</span>;if(r.stage==='wait')return <span className="badge wait">{r.age}일째 대기</span>;if(r.stage==='late')return <span className="badge late">{r.age}일째 지남</span>;if(r.stage==='error')return <span className="badge err">데이터 오류</span>;return <span className="badge none">불일치</span>}
function Detail({row,bars,close}:{row:Row;bars:any[];close:()=>void}){const enriched=useMemo(()=>bars.map((b:any,i:number)=>{const ma=(n:number)=>i>=n-1?bars.slice(i-n+1,i+1).reduce((s:number,x:any)=>s+x.close,0)/n:null;const prev=i?bars[i-1].close:null;return {...b,ret:prev?(b.close/prev-1)*100:null,ma5:ma(5),ma20:ma(20)};}),[bars]);return <div className="modal" onClick={close}><section className="modalCard" onClick={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><div className="detailHead"><div><h2>{row.name}</h2><p>{row.code} · 급등일 {row.spikeDate||'-'} · 눌림 시작 {row.firstBelowDate||'-'}</p></div><Stage r={row}/></div><PriceChart bars={bars} spikeDate={row.spikeDate} signalDate={row.signalDate}/><div className="facts"><div><span>급등률</span><b>{pct(row.spikeRet)}</b></div><div><span>거래량 배수</span><b>{fmt(row.spikeVolRatio,1)}배</b></div><div><span>판정 종가</span><b>{fmt(row.signalClose)}</b></div><div><span>MA5</span><b>{fmt(row.ma5)}</b></div><div><span>MA20</span><b>{fmt(row.ma20)}</b></div><div><span>20일선 괴리</span><b>{pct(row.ma20Gap)}</b></div></div><h3>최근 20거래일 날짜별 급등락 · 이동평균 위치</h3><div className="miniTable"><table><thead><tr><th>날짜</th><th>종가</th><th>등락률</th><th>거래량</th><th>MA5</th><th>MA20</th><th>5일선 위치</th></tr></thead><tbody>{enriched.slice(-20).reverse().map((b:any)=><tr key={b.date} className={b.date===row.signalDate?'focus':''}><td>{b.date}</td><td>{fmt(b.close)}</td><td className={(b.ret||0)>=0?'up':'down'}>{pct(b.ret)}</td><td>{fmt(b.volume)}</td><td>{fmt(b.ma5)}</td><td>{fmt(b.ma20)}</td><td>{b.ma5?(b.close<b.ma5?<span className="below">아래</span>:<span className="above">위</span>):'-'}</td></tr>)}</tbody></table></div></section></div>}
