'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import PriceChart from './PriceChart';

type Market='KOSPI'|'KOSDAQ';
type Stock={name:string;code:string;market:Market;currentPrice:number|null;changePct:number|null;marketCap:number|null};
type ChartBar={date:string;open:number;high:number;low:number;close:number;volume:number};
type Row=Stock&{dataStatus:string;match:boolean;score:number;error?:string;daily?:any;reasons?:string[];chartBars?:ChartBar[];source?:string};
type Settings={searchDays:number;downtrendDays:number;near20Pct:number;minDeclinePct:number;minNegativeMa20Ratio:number;minDowntrendR2:number;requireStepDown:boolean;requireMa5Above20Now:boolean};
const defaults:Settings={searchDays:20,downtrendDays:150,near20Pct:3,minDeclinePct:8,minNegativeMa20Ratio:55,minDowntrendR2:.12,requireStepDown:true,requireMa5Above20Now:true};
const fmt=(n:any,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:d}):'-';
const pct=(n:any,d=2)=>typeof n==='number'&&Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(d)}%`:'-';
const day=(v:any)=>typeof v==='string'?v.slice(0,10):'-';
function Field({label,value,onChange,min,max,step=1,unit=''}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number;unit?:string}){return <div><label>{label}</label><input type="number" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{unit}</small></div>}

export default function Dashboard(){
  const [universe,setUniverse]=useState<Stock[]>([]),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[query,setQuery]=useState(''),[market,setMarket]=useState<'ALL'|Market>('ALL');
  const [progress,setProgress]=useState({done:0,total:0,ok:0,fail:0,cross:0,down:0,near:0,match:0,start:0});
  const [settings,setSettings]=useState<Settings>(defaults);
  useEffect(()=>{try{const u=JSON.parse(localStorage.getItem('krx_ma20_retest_universe')||'null');if(u&&Date.now()-u.ts<30*60*1000)setUniverse(u.stocks||[]);const r=JSON.parse(localStorage.getItem('krx_ma20_retest_results_v1')||'[]');if(Array.isArray(r))setRows(r)}catch{}},[]);
  function set<K extends keyof Settings>(k:K,v:Settings[K]){setSettings(x=>({...x,[k]:v}))}
  async function loadUniverse(force=false){if(universe.length&&!force)return universe;setMsg('네이버 금융에서 코스피·코스닥 전종목 목록을 수집 중입니다…');const r=await fetch('/api/universe',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'종목 목록 수집 실패');const stocks:Stock[]=j.stocks||[];setUniverse(stocks);localStorage.setItem('krx_ma20_retest_universe',JSON.stringify({ts:Date.now(),stocks}));setMsg(`종목목록 완료 · KOSPI ${j.counts?.KOSPI||0} / KOSDAQ ${j.counts?.KOSDAQ||0}`);return stocks}
  async function scan(){setBusy(true);setRows([]);setMsg('장기 우하향 → 5/20 골든크로스 → 20일선 재접근을 분석합니다…');try{const allStocks=await loadUniverse();const stocks=market==='ALL'?allStocks:allStocks.filter(x=>x.market===market);if(!stocks.length)throw new Error('분석할 종목이 없습니다.');const start=Date.now();let found:Row[]=[],ok=0,fail=0,cross=0,down=0,near=0,match=0;setProgress({done:0,total:stocks.length,ok:0,fail:0,cross:0,down:0,near:0,match:0,start});for(let i=0;i<stocks.length;i+=20){const pack=stocks.slice(i,i+20);const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:pack,settings})});const j=await r.json();if(!r.ok)throw new Error(j.error||'스크리닝 API 오류');const got:Row[]=j.results||[];ok+=got.filter(x=>x.dataStatus==='ok').length;fail+=got.filter(x=>x.dataStatus!=='ok').length;cross+=got.filter(x=>x.daily?.crossPass).length;down+=got.filter(x=>x.daily?.downtrendPass).length;near+=got.filter(x=>x.daily?.downtrendPass&&x.daily?.near20Pass).length;match+=got.filter(x=>x.match).length;found=[...found,...got.filter(x=>x.match)];found.sort((a,b)=>(b.score-a.score)||(Math.abs(a.daily?.dist20Pct||99)-Math.abs(b.daily?.dist20Pct||99)));setRows([...found]);setProgress({done:Math.min(i+pack.length,stocks.length),total:stocks.length,ok,fail,cross,down,near,match,start});setMsg(`${Math.min(i+pack.length,stocks.length).toLocaleString()} / ${stocks.length.toLocaleString()} 분석 · 골든크로스 ${cross} · 장기우하향 통과 ${down} · 20일선 근접 ${near} · 최종 ${match}`)}localStorage.setItem('krx_ma20_retest_results_v1',JSON.stringify(found));setMsg(`완료: ${stocks.length.toLocaleString()}종목 중 골든크로스 ${cross} → 장기 우하향 ${down} → 20일선 근접 ${near} → 최종 ${match}종목`)}catch(e){setMsg(e instanceof Error?e.message:'분석 실패')}finally{setBusy(false)}}
  async function refreshUniverse(){setBusy(true);try{localStorage.removeItem('krx_ma20_retest_universe');setUniverse([]);await loadUniverse(true)}catch(e){setMsg(e instanceof Error?e.message:'목록 갱신 실패')}finally{setBusy(false)}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
  const filtered=useMemo(()=>rows.filter(x=>(!query||x.name.includes(query)||x.code.includes(query))&&(market==='ALL'||x.market===market)),[rows,query,market]);
  function reset(){setSettings(defaults);setMsg('기본값: 150일 우하향 / 최근 20일 내 골든크로스 / 종가 20일선 ±3% 로 초기화했습니다.')}
  function exportXlsx(){const data=filtered.map((r,i)=>({순위:i+1,시장:r.market,종목명:r.name,종목코드:r.code,현재가:r.currentPrice,점수:r.score,데이터:r.source||'',골든크로스일:day(r.daily?.crossDate),골든크로스경과일:r.daily?.crossDaysAgo,'우하향기간(일)':settings.downtrendDays,'우하향기간등락률(%)':r.daily?.declinePct,'우하향기울기(%/bar)':r.daily?.downtrendSlopePct,'우하향R²':r.daily?.downtrendR2,'20일선하락지속도(%)':r.daily?.negativeMa20Ratio,'현재5일선':r.daily?.ma5,'현재20일선':r.daily?.ma20,'현재종가-20일선(%)':r.daily?.dist20Pct,'5일선-20일선(%)':r.daily?.maSpreadPct,'네이버증권':`https://finance.naver.com/item/main.naver?code=${r.code}`,'포착이유':(r.reasons||[]).join(' | ')}));if(!data.length)return;const ws=XLSX.utils.json_to_sheet(data);ws['!autofilter']={ref:ws['!ref']||'A1:A1'};ws['!cols']=Object.keys(data[0]).map(k=>({wch:Math.min(42,Math.max(11,k.length+5))}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'20일선재접근후보');XLSX.writeFile(wb,`KRX_장기우하향_5_20골든크로스_20일선재접근_${new Date().toISOString().slice(0,10)}.xlsx`)}
  const elapsed=progress.start?Math.round((Date.now()-progress.start)/1000):0;
  return <main className="app">
    <header className="hero"><div><div className="eyebrow">PRIVATE · KOSPI + KOSDAQ ALL STOCKS</div><h1>장기 우하향 · 5/20 골든크로스 · 20일선 재접근 레이더</h1><p>오랫동안 하락하던 종목이 5일선으로 20일선을 돌파한 뒤, 현재 종가가 다시 20일선 근처로 내려온 구간을 찾습니다.</p></div><button className="ghost" onClick={logout}>로그아웃</button></header>
    <section className="ruleBox"><b>검색 논리</b><span>① 골든크로스 이전 {settings.downtrendDays}거래일이 회귀기울기·하락률·20일선 하락 지속도로 우하향인지 확인</span><span>② 최근 {settings.searchDays}거래일 안에 5일선이 20일선을 아래→위로 돌파</span><span>③ 현재 종가가 20일선 대비 ±{settings.near20Pct}% 안에 위치</span><span>④ 현재도 5일선 ≥ 20일선을 기본으로 유지</span></section>
    <section className="controls">
      <Field label="골든크로스 검색기간" value={settings.searchDays} onChange={v=>set('searchDays',v)} min={1} max={240} unit="거래일"/>
      <Field label="이전 우하향 확인기간" value={settings.downtrendDays} onChange={v=>set('downtrendDays',v)} min={30} max={240} unit="거래일"/>
      <Field label="20일선 근접 허용" value={settings.near20Pct} onChange={v=>set('near20Pct',v)} min={.5} max={15} step={.5} unit="±%"/>
      <Field label="최소 누적 하락률" value={settings.minDeclinePct} onChange={v=>set('minDeclinePct',v)} min={0} max={60} step={1} unit="%"/>
      <Field label="20일선 하락 지속도" value={settings.minNegativeMa20Ratio} onChange={v=>set('minNegativeMa20Ratio',v)} min={30} max={95} step={5} unit="% 이상"/>
      <Field label="우하향 R² 최소" value={settings.minDowntrendR2} onChange={v=>set('minDowntrendR2',v)} min={0} max={.9} step={.02} unit="0~1"/>
    </section>
    <section className="toolbar"><select value={market} onChange={e=>setMarket(e.target.value as 'ALL'|Market)}><option value="ALL">코스피+코스닥 전체</option><option value="KOSPI">코스피만</option><option value="KOSDAQ">코스닥만</option></select><label><input type="checkbox" checked={settings.requireStepDown} onChange={e=>set('requireStepDown',e.target.checked)}/> 초·중·후반 평균가격도 계단식 하락</label><label><input type="checkbox" checked={settings.requireMa5Above20Now} onChange={e=>set('requireMa5Above20Now',e.target.checked)}/> 현재 5일선이 20일선 위</label><button className="primary" onClick={scan} disabled={busy}>{busy?'전종목 분석 중…':'전종목 스크리닝 시작'}</button><button onClick={refreshUniverse} disabled={busy}>종목목록 새로고침</button><button onClick={reset} disabled={busy}>기본값 복원</button><button onClick={exportXlsx} disabled={!filtered.length}>Excel .xlsx 저장</button><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목명 / 코드 검색"/></section>
    {progress.total>0&&<section className="status"><div><b>{progress.done.toLocaleString()} / {progress.total.toLocaleString()}</b><span>분석 완료</span></div><div><b>{progress.cross}</b><span>골든크로스</span></div><div><b>{progress.down}</b><span>우하향 통과</span></div><div><b>{progress.near}</b><span>20일선 근접</span></div><div><b>{progress.match}</b><span>최종 후보</span></div><div><b>{progress.fail}</b><span>수집 실패</span></div><div><b>{elapsed}s</b><span>경과</span></div></section>}
    {msg&&<div className="message">{msg}</div>}
    <section className="results"><div className="resultHead"><h2>검색 결과 <span>{filtered.length}</span></h2><p>점수가 높을수록 20일선 근접도·우하향 선명도·골든크로스 최근성이 강합니다.</p></div>{!filtered.length&&!busy?<div className="empty">조건을 조절한 뒤 전종목 스크리닝을 시작하세요.</div>:filtered.map((r,i)=><article className="stockCard" key={`${r.market}-${r.code}`}><div className="stockTop"><div><div className="rank">#{i+1} · {r.market}</div><h3>{r.name} <small>{r.code}</small></h3><div className="chips"><span>점수 {fmt(r.score,1)}</span><span>현재가 {fmt(r.currentPrice)}</span><span>20일선 괴리 {pct(r.daily?.dist20Pct)}</span><span>골든크로스 {r.daily?.crossDaysAgo ?? '-'}일 전</span><span>{r.source||'-'}</span></div></div><a className="naver" href={`https://finance.naver.com/item/main.naver?code=${r.code}`} target="_blank" rel="noreferrer">네이버증권 ↗</a></div><div className="metrics"><div><b>{day(r.daily?.crossDate)}</b><span>골든크로스일</span></div><div><b>{pct(r.daily?.declinePct,1)}</b><span>이전 {settings.downtrendDays}일 등락률</span></div><div><b>{fmt(r.daily?.negativeMa20Ratio,0)}%</b><span>20일선 하락 지속도</span></div><div><b>{fmt(r.daily?.downtrendR2,2)}</b><span>우하향 R²</span></div><div><b>{pct(r.daily?.maSpreadPct)}</b><span>5일선-20일선</span></div></div><PriceChart bars={r.chartBars||[]} marks={[r.daily?.crossDate].filter(Boolean)}/><div className="reasons">{(r.reasons||[]).map((x,k)=><span key={k}>• {x}</span>)}</div></article>)}</section>
  </main>
}
