'use client';
import {useEffect,useMemo,useState} from 'react';
import * as XLSX from 'xlsx';
import PriceChart from './PriceChart';
import {BASE_WEIGHTS,type Weights,type WeightKey} from '@/lib/learning';

type Stock={name:string;code:string;market:'KOSPI'|'KOSDAQ';currentPrice:number|null;changePct:number|null;marketCap:number|null;sector:string|null;theme:string|null};
type Row=Stock&{ret5?:number;volumeScore?:number|null;newsScore?:number|null;supplyScore?:number|null;chartScore?:number|null;disclosureScore?:number|null;sectorScore?:number|null;penalty?:number;reasons?:string[];newsReasons?:string[];supplyReasons?:string[];news?:any[];detectedAt?:string;dataStatus?:string;error?:string;events?:any[];stats?:any;finalScore?:number;coverage?:number;stage?:string};
type Tab='top'|'all'|'30'|'50'|'70'|'engine'|'history'|'track'|'settings';
const rawMax:Record<WeightKey,number>={volume:25,news:20,supply:15,chart:15,disclosure:15,sector:10};
const field:Record<WeightKey,keyof Row>={volume:'volumeScore',news:'newsScore',supply:'supplyScore',chart:'chartScore',disclosure:'disclosureScore',sector:'sectorScore'};
const labels:Record<WeightKey,string>={volume:'거래량',news:'뉴스',supply:'수급',chart:'차트',disclosure:'공시',sector:'섹터'};
const pct=(n:any)=>typeof n==='number'&&Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)}%`:'데이터 없음';
const fmt=(n:any,d=0)=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('ko-KR',{maximumFractionDigits:d}):'데이터 없음';
const stage=(v:number)=>v>=85?'강한 전조':v>=70?'전조 집중':v>=50?'이상징후':v>=30?'관심':'관찰';
function scoreRow(r:Row,w:Weights){let earned=0,possible=0;for(const k of Object.keys(w) as WeightKey[]){const v=r[field[k]] as number|null|undefined;if(typeof v==='number'){earned+=Math.max(0,Math.min(1,v/rawMax[k]))*w[k];possible+=w[k];}}const base=possible?earned/possible*100:0;const final=Math.max(0,Math.min(100,base+(r.penalty||0)));return {...r,finalScore:+final.toFixed(1),coverage:+possible.toFixed(1),stage:stage(final)};}
function features(r:Row){const o:any={};for(const k of Object.keys(rawMax) as WeightKey[]){const v=r[field[k]] as any;if(typeof v==='number')o[k]=Math.max(0,Math.min(1,v/rawMax[k]));}return o;}

export default function DashboardV4(){
 const [tab,setTab]=useState<Tab>('top'),[universe,setUniverse]=useState<Stock[]>([]),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[period,setPeriod]=useState(120),[thr,setThr]=useState({d1:5,d3:8,d5:10,d10:15});
 const [progress,setProgress]=useState({done:0,total:0,ok:0,fail:0,start:0}),[weights,setWeights]=useState<Weights>(BASE_WEIGHTS),[learning,setLearning]=useState<any>(null),[round,setRound]=useState(0),[tracking,setTracking]=useState<any[]>([]),[selected,setSelected]=useState<Row|null>(null),[bars,setBars]=useState<any[]>([]);
 useEffect(()=>{try{const u=JSON.parse(localStorage.getItem('psr_v4_universe')||'null');if(u&&Date.now()-u.ts<6*3600000)setUniverse(u.stocks||[]);const r=JSON.parse(localStorage.getItem('psr_v4_latest')||'[]');if(Array.isArray(r))setRows(r);const w=JSON.parse(localStorage.getItem('psr_v4_weights')||'null');if(w)setWeights({...BASE_WEIGHTS,...w});const l=JSON.parse(localStorage.getItem('psr_v4_learning')||'null');if(l){setLearning(l);setRound(Number(l.round||0));}const t=JSON.parse(localStorage.getItem('psr_v4_tracking')||'[]');if(Array.isArray(t))setTracking(t);}catch{}},[]);
 async function loadUniverse(force=false){if(universe.length&&!force)return universe;setMsg('KOSPI 500 + KOSDAQ 300 종목목록 수집 중…');const r=await fetch('/api/universe',{cache:'no-store'});const j=await r.json();if(!r.ok||!j.stocks?.length)throw new Error(j.error||'종목목록 수집 실패');setUniverse(j.stocks);localStorage.setItem('psr_v4_universe',JSON.stringify({ts:Date.now(),stocks:j.stocks}));setMsg(`종목목록 ${j.stocks.length}개 준비 완료`);return j.stocks as Stock[];}
 async function updateTracking(base=tracking){if(!base.length)return base;const recent=base.slice(-25);try{const r=await fetch('/api/performance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({detections:recent})});const j=await r.json();if(!r.ok)return base;const m=new Map((j.results||[]).map((x:any)=>[`${x.date}-${x.code}`,x]));const merged=base.map(x=>m.get(`${x.date}-${x.code}`)||x);setTracking(merged);localStorage.setItem('psr_v4_tracking',JSON.stringify(merged));return merged;}catch{return base;}}
 async function autoLearn(source:Row[],tracked:any[]){const stats=source.filter(x=>x.dataStatus==='ok').map(x=>x.stats).filter(Boolean);const r=await fetch('/api/learn',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stats,tracking:tracked,previous:weights})});const j=await r.json();if(!r.ok)throw new Error(j.error||'자동학습 실패');const nw={...BASE_WEIGHTS,...j.weights} as Weights;const nr=round+1;const rec={...j,round:nr};setWeights(nw);setLearning(rec);setRound(nr);localStorage.setItem('psr_v4_weights',JSON.stringify(nw));localStorage.setItem('psr_v4_learning',JSON.stringify(rec));return nw;}
 function saveDetections(source:Row[],w:Weights){const day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});let old=tracking;const keys=new Set(old.map(x=>`${x.date}-${x.code}`));for(const r of source.filter(x=>x.dataStatus==='ok').slice(0,20)){const k=`${day}-${r.code}`;if(!keys.has(k)){old.push({date:day,code:r.code,name:r.name,market:r.market,price:r.currentPrice,score:r.finalScore,features:features(r),weights:w});keys.add(k);}}old=old.slice(-200);setTracking([...old]);localStorage.setItem('psr_v4_tracking',JSON.stringify(old));}
 async function scan(){setBusy(true);setRows([]);setMsg('자동학습 V4 분석 준비 중…');try{const stocks=await loadUniverse();const started=Date.now();setProgress({done:0,total:stocks.length,ok:0,fail:0,start:started});let all:Row[]=[];for(let i=0;i<stocks.length;i+=12){const batch=stocks.slice(i,i+12);const r=await fetch('/api/scan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:batch,period,thresholds:thr})});const j=await r.json();if(!r.ok)throw new Error(j.error||'분석 API 실패');all.push(...(j.results||[]));const scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);setProgress({done:all.length,total:stocks.length,ok:all.filter(x=>x.dataStatus==='ok').length,fail:all.filter(x=>x.dataStatus!=='ok').length,start:started});setMsg(`${all.length} / ${stocks.length} 가격·거래량·차트 분석`);}let scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));const pre=scored.filter(x=>x.dataStatus==='ok').slice(0,40);setMsg('상위 후보 뉴스·수급 보강 중…');for(let i=0;i<pre.length;i+=20){const pack=pre.slice(i,i+20);const r=await fetch('/api/enrich',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({stocks:pack})});if(!r.ok)continue;const j=await r.json();const map=new Map((j.results||[]).map((x:any)=>[x.code,x]));all=all.map(x=>{const e:any=map.get(x.code);return e?{...x,...e}:x;});scored=all.map(x=>scoreRow(x,weights)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);}setMsg('과거 백테스트 + 실제 탐지성과로 가중치 자동학습 중…');const tracked=await updateTracking(tracking);const nw=await autoLearn(all,tracked);scored=all.map(x=>scoreRow(x,nw)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(scored);localStorage.setItem('psr_v4_latest',JSON.stringify(scored));saveDetections(scored,nw);setMsg(`분석·자동학습 완료 · 학습 ${round+1}회차 · 성공 ${scored.filter(x=>x.dataStatus==='ok').length}`);}catch(e){setMsg(e instanceof Error?e.message:'분석 실패');}finally{setBusy(false)}}
 async function refreshTracking(){setMsg('실제 탐지 후 성과 갱신 중…');const t=await updateTracking(tracking);if(rows.length){try{const nw=await autoLearn(rows,t);const rescored=rows.map(x=>scoreRow(x,nw)).sort((a,b)=>(b.finalScore||0)-(a.finalScore||0));setRows(rescored);localStorage.setItem('psr_v4_latest',JSON.stringify(rescored));setMsg('성과 반영 + 가중치 재학습 완료');}catch{setMsg('성과 갱신 완료, 학습 갱신은 다음 분석 때 반영');}}else setMsg('탐지 후 성과 갱신 완료');}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 async function openDetail(r:Row){setSelected(r);setBars([]);try{const x=await fetch(`/api/detail?code=${r.code}&market=${r.market}`);const j=await x.json();if(x.ok)setBars(j.bars||[]);}catch{}}
 const filtered=useMemo(()=>{let a=rows.filter(r=>!query||r.name.includes(query)||r.code.includes(query));if(tab==='top')return a.filter(r=>r.dataStatus==='ok').slice(0,20);if(tab==='30')return a.filter(r=>(r.finalScore||0)>=30);if(tab==='50')return a.filter(r=>(r.finalScore||0)>=50);if(tab==='70')return a.filter(r=>(r.finalScore||0)>=70);return a;},[rows,query,tab]);
 const events=useMemo(()=>rows.flatMap(r=>(r.events||[]).map((e:any)=>({...e,name:r.name,code:r.code}))).sort((a,b)=>String(b.date).localeCompare(String(a.date))),[rows]);
 function exportXlsx(){const src=filtered.length?filtered:rows;const data=src.map(r=>({종목명:r.name,코드:r.code,시장:r.market,현재가:r.currentPrice,등락률:r.changePct,'5일수익률':r.ret5,자동학습점수:r.finalScore,단계:r.stage,거래량:r.volumeScore,뉴스:r.newsScore,수급:r.supplyScore,차트:r.chartScore,공시:r.disclosureScore,섹터:r.sectorScore,급등감점:r.penalty,커버리지:r.coverage,거래량가중치:weights.volume,뉴스가중치:weights.news,수급가중치:weights.supply,차트가중치:weights.chart,공시가중치:weights.disclosure,섹터가중치:weights.sector,포착이유:[...(r.reasons||[]),...(r.newsReasons||[]),...(r.supplyReasons||[])].join(' | '),탐지일:r.detectedAt?.slice(0,10)||''}));const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'자동학습V4');XLSX.writeFile(wb,`급등전조_자동학습V4_${new Date().toISOString().slice(0,10)}.xlsx`);}
 const elapsed=progress.start?Math.round((Date.now()-progress.start)/1000):0;
 return <main className="app"><header className="hero"><div><div className="eyebrow">KOREA PRE-SPIKE AUTO-LEARNING RADAR V4</div><h1>급등 전조 자동학습 레이더 V4</h1><p>과거 백테스트와 실제 탐지 성과를 반영해 신호 가중치를 자동 조정합니다.</p></div><button className="ghost" onClick={logout}>로그아웃</button></header>
 <nav className="tabs">{([['top','오늘의 전조 TOP20'],['all','전체 800종목'],['30','30점 이상'],['50','50점 이상'],['70','70점 이상'],['engine','자동학습 엔진'],['history','과거 급등 학습'],['track','탐지 후 성과'],['settings','설정']] as [Tab,string][]).map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 <section className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="종목명/코드 검색"/><button className="primary" onClick={scan} disabled={busy}>{busy?'분석·학습 중…':'800종목 분석 + 자동학습'}</button><button onClick={()=>loadUniverse(true)} disabled={busy}>종목목록 새로고침</button><button onClick={exportXlsx} disabled={!rows.length}>Excel .xlsx</button></section>
 {(busy||progress.done>0)&&<section className="progress"><div className="progressHead"><b>{progress.done} / {progress.total||800}</b><span>성공 {progress.ok} · 실패 {progress.fail} · {elapsed}초</span></div><div className="bar"><i style={{width:`${progress.total?progress.done/progress.total*100:0}%`}}/></div></section>}
 {msg&&<div className="status">{msg}</div>}
 {tab==='engine'?<Engine weights={weights} learning={learning} round={round}/>:tab==='history'?<History events={events}/>:tab==='track'?<Track tracking={tracking} refresh={refreshTracking}/>:tab==='settings'?<Settings period={period} setPeriod={setPeriod} thr={thr} setThr={setThr}/>:<Results title={tab==='top'?'아직 크게 오르지 않은 급등 전조 TOP 20':tab==='all'?'전체 분석 종목':`${tab}점 이상`} rows={filtered} weights={weights} open={openDetail}/>} 
 {selected&&<Detail row={selected} bars={bars} weights={weights} close={()=>setSelected(null)}/>}<footer>V4 점수는 상승 확률이 아닙니다. 자동학습은 과거·실제 성과에 맞춰 신호 가중치를 조정하지만 미래 수익을 보장하지 않습니다.</footer></main>;
}
function Engine({weights,learning,round}:{weights:Weights;learning:any;round:number}){const h=learning?.metrics?.historical;return <section className="panel"><h2>자동학습 엔진</h2><div className="stats"><article><span>학습 회차</span><b>{round}</b></article><article><span>실제성과 학습표본</span><b>{learning?.metrics?.labeled||0}</b></article><article><span>마지막 학습</span><b style={{fontSize:16}}>{learning?.learnedAt?new Date(learning.learnedAt).toLocaleString('ko-KR'):'대기'}</b></article></div><div className="metricGrid" style={{marginTop:12}}>{(Object.keys(weights) as WeightKey[]).map(k=><span key={k}>{labels[k]} 가중치<b>{weights[k].toFixed(1)}</b></span>)}</div><div className="metricCard"><h3>과거 검증 품질</h3><div className="metricGrid"><span>거래량 정밀도<b>{h?`${(h.volume.precision*100).toFixed(1)}%`:'-'}</b></span><span>거래량 FPR<b>{h?`${(h.volume.fpr*100).toFixed(1)}%`:'-'}</b></span><span>차트 정밀도<b>{h?`${(h.chart.precision*100).toFixed(1)}%`:'-'}</b></span><span>차트 FPR<b>{h?`${(h.chart.fpr*100).toFixed(1)}%`:'-'}</b></span></div></div><div className="note">매 전체 분석 후 자동으로 재학습합니다. 처음에는 과거 120거래일의 거래량·차트 선행성과를 반영하고, 실제 탐지 후 20거래일 성과 표본이 쌓이면 뉴스·수급·공시·섹터 신호도 함께 조정합니다. 가중치는 한 번에 크게 바뀌지 않도록 70% 이전값 + 30% 새값으로 완만하게 갱신합니다.</div></section>}
function Results({title,rows,weights,open}:{title:string;rows:Row[];weights:Weights;open:(r:Row)=>void}){return <section><div className="sectionTitle"><h2>{title}</h2><span>{rows.length}종목</span></div>{!rows.length?<div className="empty">아직 분석 결과가 없습니다.</div>:<div className="cards">{rows.map((r,i)=><article className="stockCard" key={`${r.market}-${r.code}`} onClick={()=>open(r)}><div className="rank">{i+1}</div><div className="stockMain"><div><b>{r.name}</b><span>{r.code} · {r.market}</span></div><div className="price"><b>{fmt(r.currentPrice)}</b><span className={(r.changePct||0)>=0?'up':'down'}>{pct(r.changePct)}</span></div></div><div className="scoreHero"><strong>{fmt(r.finalScore,1)}</strong><span>{r.stage} · 학습커버리지 {fmt(r.coverage,0)}%</span></div><div className="miniGrid"><label>5일<b>{pct(r.ret5)}</b></label>{(Object.keys(weights) as WeightKey[]).map(k=><label key={k}>{labels[k]} <small>w {weights[k].toFixed(1)}</small><b>{typeof r[field[k]]==='number'?`${r[field[k]]}/${rawMax[k]}`:'없음'}</b></label>)}</div>{r.error&&<div className="errorBox">{r.error}</div>}</article>)}</div>}</section>}
function History({events}:{events:any[]}){return <section className="panel"><h2>과거 급등 학습</h2><p className="note">급등일 D0 이전 D-30·20·10·5·3·1 시점의 거래량+차트 점수를 미래 데이터 없이 계산합니다.</p><div className="tableWrap"><table><thead><tr><th>종목</th><th>급등일</th><th>급등폭</th><th>D-30</th><th>D-20</th><th>D-10</th><th>D-5</th><th>D-3</th><th>D-1</th></tr></thead><tbody>{events.slice(0,300).map((e,i)=><tr key={i}><td>{e.name}<small>{e.code}</small></td><td>{e.date}</td><td>{fmt(e.spikePct,1)}%</td>{[30,20,10,5,3,1].map(n=><td key={n}>{e[`d${n}`]?.score??'-'}</td>)}</tr>)}</tbody></table></div></section>}
function Track({tracking,refresh}:{tracking:any[];refresh:()=>void}){return <section className="panel"><div className="sectionTitle"><h2>탐지 후 실제 성과</h2><button onClick={refresh}>성과 갱신 + 재학습</button></div><div className="tableWrap"><table><thead><tr><th>탐지일/종목</th><th>점수</th><th>1일</th><th>3일</th><th>5일</th><th>10일</th><th>20일</th><th>20일 MFE</th><th>20일 MAE</th><th>+5%도달</th></tr></thead><tbody>{[...tracking].reverse().map((x:any,i)=><tr key={i}><td>{x.date} {x.name}<small>{x.code}</small></td><td>{fmt(x.score,1)}</td>{[1,3,5,10,20].map(n=><td key={n}>{pct(x[`r${n}`])}</td>)}<td>{pct(x.mfe20)}</td><td>{pct(x.mae20)}</td><td>{typeof x.hit5_20==='boolean'?(x.hit5_20?'YES':'NO'):'대기'}</td></tr>)}</tbody></table></div></section>}
function Settings({period,setPeriod,thr,setThr}:{period:number;setPeriod:(x:number)=>void;thr:any;setThr:(x:any)=>void}){return <section className="panel"><h2>설정</h2><div className="choice" style={{margin:'12px 0'}}>{[30,60,90,120].map(n=><button key={n} className={period===n?'active':''} onClick={()=>setPeriod(n)}>{n}거래일</button>)}</div><div className="settingsGrid">{([['d1','1일 급등 기준'],['d3','3일 누적 기준'],['d5','5일 누적 기준'],['d10','10일 누적 기준']] as const).map(([k,l])=><label key={k}>{l}<div><input type="range" min="1" max="30" value={thr[k]} onChange={e=>setThr({...thr,[k]:Number(e.target.value)})}/><b>{thr[k]}%</b></div></label>)}</div><div className="note">자동학습은 급등 기준을 바꾸면 그 기준에 맞춰 다시 학습합니다. 미래 데이터는 현재점수 계산에 사용하지 않습니다.</div></section>}
function Detail({row,bars,weights,close}:{row:Row;bars:any[];weights:Weights;close:()=>void}){const reasons=[...(row.reasons||[]),...(row.newsReasons||[]),...(row.supplyReasons||[])];return <div className="modalBack" onClick={close}><section className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><h2>{row.name} <small>{row.code} · {row.market}</small></h2><div className="detailHero"><div><span>자동학습 점수</span><b>{fmt(row.finalScore,1)}</b><small>{row.stage} · 커버리지 {fmt(row.coverage)}%</small></div><div><span>현재가</span><b>{fmt(row.currentPrice)}</b><small>{pct(row.changePct)} · 5일 {pct(row.ret5)}</small></div></div><h3>이 종목을 포착한 이유</h3>{reasons.length?<ul className="reasons">{reasons.map((x,i)=><li key={i}>{x}</li>)}</ul>:<div className="empty">포착 상세 이유 없음</div>}<div className="metricGrid" style={{margin:'12px 0'}}>{(Object.keys(weights) as WeightKey[]).map(k=><span key={k}>{labels[k]}<b>{typeof row[field[k]]==='number'?`${row[field[k]]}/${rawMax[k]} · w ${weights[k].toFixed(1)}`:'데이터 없음'}</b></span>)}</div><h3>120거래일 차트</h3><PriceChart bars={bars} marks={(row.events||[]).map((e:any)=>e.date)}/>{row.news?.length?<><h3>최근 뉴스</h3><div className="newsList">{row.news.map((n:any,i)=><a key={i} href={n.link} target="_blank" rel="noreferrer"><time>{n.date?.slice(0,10)}</time><span>{n.title}</span></a>)}</div></>:null}</section></div>}
