import { NextResponse } from 'next/server';
import { fetchUniverse, fetchYahooBars, type Bar, type UniverseStock } from '@/lib/market';
export const runtime='nodejs'; export const dynamic='force-dynamic'; export const maxDuration=60;
const avg=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const pct=(a:number,b:number)=>b?(a/b-1)*100:0;
const sma=(b:Bar[],n:number,i=b.length-1)=>i+1<n?null:avg(b.slice(i-n+1,i+1).map(x=>x.close));
const localMinima=(v:number[])=>{const r:number[]=[];for(let i=2;i<v.length-2;i++)if(v[i]<=v[i-1]&&v[i]<=v[i+1]&&v[i]<=v[i-2]&&v[i]<=v[i+2])r.push(i);return r};
const clamp=(v:number,a=0,c=100)=>Math.max(a,Math.min(c,v));
function indicators(b:Bar[]){return b.map((x,i)=>{const ret=i?pct(x.close,b[i-1].close):null,ma=(n:number)=>i>=n-1?avg(b.slice(i-n+1,i+1).map(z=>z.close)):null,base=i>=20?avg(b.slice(i-20,i).map(z=>z.volume)):0;return {...x,ret,ma5:ma(5),ma20:ma(20),ma60:ma(60),vr:base>0?x.volume/base:null}})}
function nextdayScore(b:Bar[]){const a=indicators(b),i=a.length-1;if(i<65)return null;const p={lookback:15,spikePct:7,spikeVolRatio:2.5,pullbackMaxDays:6,ma20Distance:8,maxTodayRise:6};const last=a[i];let score=0,pen=0;const spikes:number[]=[];for(let j=Math.max(20,i-p.lookback);j<=i;j++)if((a[j].ret??-999)>=p.spikePct&&(a[j].vr??0)>=p.spikeVolRatio)spikes.push(j);const si=spikes.length?spikes.at(-1)!:-1;const abnormal=a.slice(Math.max(20,i-5),i+1).filter(x=>(x.vr??0)>=1.5).length;if(si>=0){const s=a[si];score+=10;const vr=s.vr??0;score+=vr>=5?15:vr>=3?12:vr>=2.2?9:6;if(spikes.length>=2)score+=3;const age=i-si,pb=pct(last.close,s.close);if(age>=1&&age<=p.pullbackMaxDays&&pb>=-28&&pb<=4)score+=10;const after=a.slice(si+1,i+1),con=after.length?avg(after.map(x=>x.volume))/Math.max(1,s.volume):null;if(con!==null&&con<=.65)score+=6;else if(con!==null&&con<=.85)score+=3}else if(abnormal>=2)score+=9;if((last.vr??0)>=2&&Math.abs(last.ret??0)<4)score+=8;else if((last.vr??0)>=1.5)score+=4;const g=last.ma20?pct(last.close,last.ma20):null;if(g!==null&&Math.abs(g)<=3)score+=8;else if(g!==null&&Math.abs(g)<=p.ma20Distance)score+=5;const g5=last.ma5?pct(last.close,last.ma5):null;if(g5!==null&&Math.abs(g5)<=2.5)score+=4;if(last.ma20&&a[i-8].ma20&&last.ma20>=a[i-8].ma20!)score+=3;if(last.ma5&&a[i-3].ma5&&last.ma5>a[i-3].ma5!)score+=3;const closes=a.slice(Math.max(0,i-24),i+1).map(x=>x.close),mins=localMinima(closes);if(mins.length>=2){const x=closes[mins.at(-2)!],y=closes[mins.at(-1)!];if(Math.abs(x-y)/Math.min(x,y)<=.055)score+=4;else if(y>x)score+=3}else if(mins.length)score+=1;const td=last.ret??0;if(td<=3&&td>=-5)score+=6;else if(td<=p.maxTodayRise)score+=3;else pen+=td>=10?18:10;const r5=i>=5?pct(last.close,a[i-5].close):0;if(r5>=20)pen+=10;if(g!==null&&g>15)pen+=8;return Math.max(0,Math.min(70,Math.round(score-pen)))}
function thirdDayScore(b:Bar[]){const a=indicators(b),last=a.length-1;if(last<25)return null;const p={lookback:20,spikePct:7,vr:3,waitDays:3,maxAfterSpike:15,ma20Distance:10,pullbackMin:-25,pullbackMax:8};const start=Math.max(20,last-p.lookback+1),spikes:number[]=[];for(let i=start;i<last;i++)if((a[i].ret??-999)>=p.spikePct&&(a[i].vr??0)>=p.vr)spikes.push(i);for(const si of [...spikes].reverse()){if(last-si>p.maxAfterSpike)continue;if(!(a[last].ma5&&a[last].close<a[last].ma5!))continue;const minPivot=Math.max(si+1,last-(p.waitDays+3));let first=-1,age=0;for(let j=last-1;j>=minPivot;j--){const seq=a.slice(j,last+1),down=seq.slice(1).every(x=>(x.ret??0)<=1),has=seq.slice(1).some(x=>(x.ret??0)<-.15),pivot=(a[j].ret??-999)>=-.2&&!!a[j].ma5&&a[j].close<=a[j].ma5!*1.06,near=seq.filter(x=>x.ma5&&x.close<=x.ma5!*1.035).length>=Math.max(1,seq.length-1);if(pivot&&down&&has&&near){first=j;age=last-j+1;break}}if(first<0)continue;const pb=pct(a[last].close,a[si].close),g=a[last].ma20?pct(a[last].close,a[last].ma20!):null,ok=pb>=p.pullbackMin&&pb<=p.pullbackMax&&(g===null||Math.abs(g)<=p.ma20Distance);if(!(age===p.waitDays&&ok))continue;return clamp(Math.round(55+Math.min(20,(a[si].vr??0)*2)+Math.min(12,(a[si].ret??0)*.7)+Math.max(0,8-Math.abs(g??8))))}return null}
function realStock(s:UniverseStock){const n=s.name.toUpperCase();return !/(KODEX|TIGER|ACE |ACE$|RISE |RISE$|KOSEF|HANARO|SOL |SOL$|TIMEFOLIO|PLUS |PLUS$|ARIRANG|KBSTAR|FOCUS|WOORI|ETN|스팩|SPAC)/.test(n)}
type Key='nextdayEarly'|'ma5ThirdDay'; const models:Record<Key,(b:Bar[])=>number|null>={nextdayEarly:nextdayScore,ma5ThirdDay:thirdDayScore};
export async function GET(req:Request){const u=new URL(req.url),start=u.searchParams.get('start')||'2026-08-25',end=u.searchParams.get('end')||'2026-09-23';const uni=await fetchUniverse();const stocks=[...uni.stocks.filter(x=>x.market==='KOSPI'&&realStock(x)).slice(0,300),...uni.stocks.filter(x=>x.market==='KOSDAQ'&&realStock(x)).slice(0,200)];const data:{s:UniverseStock;bars:Bar[]}[]=[];let errors=0;for(let i=0;i<stocks.length;i+=25){const z=await Promise.all(stocks.slice(i,i+25).map(async s=>{try{return {s,bars:await fetchYahooBars(s.code,s.market,340)}}catch{return null}}));for(const x of z)if(x)data.push(x);else errors++}const dates=[...new Set(data.flatMap(d=>d.bars.filter((_,i)=>i<d.bars.length-1).map(x=>x.date)).filter(d=>d>=start&&d<=end))].sort();const out:any={};for(const key of Object.keys(models) as Key[]){let eqFull=1,eqFixed=1,peak=1,mdd=0;const days:any[]=[];for(const date of dates){const c:{score:number;r:number;name:string}[]=[];for(const d of data){const idx=d.bars.findIndex(x=>x.date===date);if(idx<65||idx>=d.bars.length-1)continue;const score=models[key](d.bars.slice(0,idx+1));if(score===null)continue;c.push({score,r:pct(d.bars[idx+1].close,d.bars[idx].close),name:d.s.name})}c.sort((a,b)=>b.score-a.score);const top=c.slice(0,5),retFull=top.length?avg(top.map(x=>x.r)):0,retFixed=top.reduce((s,x)=>s+x.r,0)/5;eqFull*=1+retFull/100;eqFixed*=1+retFixed/100;peak=Math.max(peak,eqFixed);mdd=Math.min(mdd,(eqFixed/peak-1)*100);days.push({date,n:top.length,retFull:+retFull.toFixed(3),retFixed5:+retFixed.toFixed(3),names:top.map(x=>x.name)})}out[key]={days:dates.length,activeDays:days.filter(x=>x.n).length,exact5Days:days.filter(x=>x.n===5).length,avgPicks:+avg(days.map(x=>x.n)).toFixed(2),compoundInvestAvailable:+((eqFull-1)*100).toFixed(2),compoundFixed5:+((eqFixed-1)*100).toFixed(2),mddFixed5:+mdd.toFixed(2),winRateFixed5:+(days.filter(x=>x.retFixed5>0).length/days.length*100).toFixed(1),recent:days.slice(-5)}}return NextResponse.json({ok:true,start,end,requested:stocks.length,loaded:data.length,errors,dates:dates.length,filter:'exclude ETF/ETN/SPAC by name; common/pref/reit equities retained',rule:'signal at close; five 20% slots; unused slots cash; next close exit; gross before fees/tax/slippage; historical bars sliced as-of each date',summary:out})}
