import * as cheerio from 'cheerio';
import iconv from 'iconv-lite';

export type Market='KOSPI'|'KOSDAQ';
export type UniverseStock={name:string;code:string;market:Market;currentPrice:number|null;changePct:number|null;marketCap:number|null};
export type Bar={date:string;open:number;high:number;low:number;close:number;volume:number};

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const num=(v:unknown)=>{if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v!=='string')return null;const n=Number(v.replace(/[,+%원\s]/g,''));return Number.isFinite(n)?n:null};
async function timed(url:string,init:RequestInit={},ms=9000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
async function json(url:string,revalidate=900){let last='';for(let i=0;i<3;i++){try{const r=await timed(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*','Accept-Language':'ko-KR,ko;q=.9','Referer':'https://m.stock.naver.com/'},next:{revalidate}} as RequestInit&{next:{revalidate:number}},9000);if(!r.ok){last=`HTTP ${r.status}`;await sleep(180*(i+1));continue}return await r.json()}catch(e){last=e instanceof Error?e.message:'JSON 수집 오류';await sleep(180*(i+1))}}throw new Error(last||'JSON 수집 실패')}
async function html(url:string,revalidate=900){const r=await timed(url,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'ko-KR,ko;q=.9','Referer':'https://finance.naver.com/'},next:{revalidate}} as RequestInit&{next:{revalidate:number}},9000);if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());return (r.headers.get('content-type')||'').toLowerCase().includes('utf-8')?b.toString('utf8'):iconv.decode(b,'EUC-KR')}
function pickArray(j:any):any[]{if(Array.isArray(j))return j;for(const k of ['stocks','items','stockList','data'])if(Array.isArray(j?.[k]))return j[k];if(Array.isArray(j?.result?.stocks))return j.result.stocks;if(Array.isArray(j?.result?.items))return j.result.items;return []}
function norm(x:any,market:Market):UniverseStock|null{const code=String(x?.itemCode??x?.itemcode??x?.stockCode??x?.code??'').match(/\d{6}/)?.[0]||'';const name=String(x?.stockName??x?.name??x?.itemName??'').trim();if(!code||!name)return null;return{name,code,market,currentPrice:num(x?.closePrice??x?.currentPrice??x?.nowVal??x?.price),changePct:num(x?.fluctuationsRatio??x?.changeRate??x?.changePct??x?.rate),marketCap:num(x?.marketValue??x?.marketCap??x?.marketValueAmount)}}

async function mobileUniverse(market:Market){const out:UniverseStock[]=[];for(let page=1;page<=40;page++){const j=await json(`https://m.stock.naver.com/api/stocks/marketValue/${market}?page=${page}&pageSize=100`);const rows=pickArray(j);if(!rows.length)break;for(const x of rows){const s=norm(x,market);if(s)out.push(s)}if(rows.length<100)break;await sleep(35)}return [...new Map(out.map(x=>[x.code,x])).values()]}
async function pcUniverse(market:Market){const out:UniverseStock[]=[];const sosok=market==='KOSPI'?0:1;for(let page=1;page<=45;page++){const $=cheerio.load(await html(`https://finance.naver.com/sise/sise_market_sum.naver?sosok=${sosok}&page=${page}`));let count=0;$('table.type_2 tr,table.type2 tr').each((_,tr)=>{const a=$(tr).find('a.tltle,a[href*="/item/main.naver?code="]').first();const code=(a.attr('href')||'').match(/code=(\d{6})/)?.[1],name=a.text().trim();if(!code||!name)return;const td=$(tr).find('td').map((_,x)=>$(x).text().replace(/\s+/g,' ').trim()).get();out.push({name,code,market,currentPrice:num(td[2]),changePct:num(td[4]),marketCap:num(td[6])});count++});if(!count)break;await sleep(45)}return [...new Map(out.map(x=>[x.code,x])).values()]}
async function oneUniverse(market:Market){const errors:string[]=[];try{const stocks=await mobileUniverse(market);if(stocks.length>=100)return{stocks,source:'Naver Finance mobile',errors};errors.push(`모바일 ${stocks.length}건`)}catch(e){errors.push(`모바일: ${e instanceof Error?e.message:'오류'}`)}try{const stocks=await pcUniverse(market);if(stocks.length)return{stocks,source:'Naver Finance PC',errors};errors.push('PC 0건')}catch(e){errors.push(`PC: ${e instanceof Error?e.message:'오류'}`)}return{stocks:[] as UniverseStock[],source:'Naver Finance',errors}}
export async function fetchUniverse(only?:Market){const markets:Market[]=only?[only]:['KOSPI','KOSDAQ'];const sets=await Promise.all(markets.map(async market=>({market,...await oneUniverse(market)})));const stocks=sets.flatMap(x=>x.stocks),errors=sets.flatMap(x=>x.errors.map(e=>`${x.market} ${e}`));if(!stocks.length)throw new Error(`네이버금융 종목목록 수집 실패 · ${errors.join(' / ')}`);return{stocks,errors,sources:sets.map(x=>`${x.market}: ${x.source} ${x.stocks.length}종목`)}}

export const yahooSymbol=(code:string,market:Market)=>`${code}.${market==='KOSDAQ'?'KQ':'KS'}`;
async function yahoo(code:string,market:Market,interval:'1d'|'30m',p1:number,p2:number){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yahooSymbol(code,market))}?period1=${p1}&period2=${p2}&interval=${interval}&events=history&includeAdjustedClose=true&includePrePost=false`;let last='';for(let a=0;a<3;a++){try{const r=await timed(u,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,*/*'},next:{revalidate:interval==='1d'?600:120}} as RequestInit&{next:{revalidate:number}},7000);if(!r.ok){last=`HTTP ${r.status}`;await sleep(220*(a+1));continue}const j=await r.json(),z=j?.chart?.result?.[0],ts:number[]=z?.timestamp||[],q=z?.indicators?.quote?.[0]||{};const bars:Bar[]=ts.map((v,i)=>({date:new Date(v*1000).toISOString(),open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i]})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));if(bars.length<10)throw new Error('가격 이력 부족');return bars}catch(e){last=e instanceof Error?e.message:'Yahoo 오류';await sleep(220*(a+1))}}throw new Error(last||'Yahoo Finance 수집 실패')}
export async function fetchYahooBars(code:string,market:Market,days=120){const p2=Math.floor(Date.now()/1000)+86400,p1=Math.floor((Date.now()-days*2.3*86400000)/1000);return (await yahoo(code,market,'1d',p1,p2)).slice(-Math.max(days,90))}
export async function fetchYahoo30m(code:string,market:Market){const p2=Math.floor(Date.now()/1000)+3600,p1=Math.floor((Date.now()-59*86400000)/1000);return (await yahoo(code,market,'30m',p1,p2)).slice(-700)}

async function fetchNaverDaily(code:string,days=120){const out:Bar[]=[];const pages=Math.min(55,Math.max(6,Math.ceil(days/10)+1));for(let page=1;page<=pages;page++){const $=cheerio.load(await html(`https://finance.naver.com/item/sise_day.naver?code=${code}&page=${page}`,300));let got=0;$('table.type2 tr').each((_,tr)=>{const td=$(tr).find('td').map((_,x)=>$(x).text().replace(/\s+/g,' ').trim()).get();if(td.length<7||!/^\d{4}\.\d{2}\.\d{2}$/.test(td[0]||''))return;const close=num(td[1]),open=num(td[3]),high=num(td[4]),low=num(td[5]),volume=num(td[6]);if([open,high,low,close,volume].some(v=>v===null))return;const date=`${td[0].replace(/\./g,'-')}T06:30:00.000Z`;out.push({date,open:open!,high:high!,low:low!,close:close!,volume:volume!});got++});if(!got)break;await sleep(30)}const bars=[...new Map(out.map(x=>[x.date,x])).values()].sort((a,b)=>a.date.localeCompare(b.date));if(bars.length<20)throw new Error(`네이버 일봉 이력 부족 ${bars.length}건`);return bars.slice(-days)}
export async function fetchDailyBars(code:string,market:Market,preferred:'yahoo'|'naver'='yahoo',days=120){if(preferred==='naver'){try{return{bars:await fetchNaverDaily(code,days),source:'Naver Finance'}}catch{ return{bars:await fetchYahooBars(code,market,days),source:'Yahoo Finance'} }}try{return{bars:await fetchYahooBars(code,market,days),source:'Yahoo Finance'}}catch(yahooError){try{return{bars:await fetchNaverDaily(code,days),source:'Naver Finance'}}catch(naverError){const y=yahooError instanceof Error?yahooError.message:'Yahoo 실패',n=naverError instanceof Error?naverError.message:'Naver 실패';throw new Error(`Yahoo/Naver 시세 수집 실패 · ${y} / ${n}`)}}}
