import * as cheerio from 'cheerio';
import iconv from 'iconv-lite';

export type UniverseStock={name:string;code:string;market:'KOSPI'|'KOSDAQ';currentPrice:number|null;changePct:number|null;marketCap:number|null;sector?:string|null;theme?:string|null};
export type Bar={date:string;open:number;high:number;low:number;close:number;volume:number};

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function num(v:unknown){if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v!=='string')return null;const n=Number(v.replace(/[,+%원\s]/g,''));return Number.isFinite(n)?n:null}
async function fetchWithTimeout(url:string,init:RequestInit={},timeout=9000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
async function fetchJson(url:string,revalidate=900){let last='';for(let i=0;i<3;i++){try{const r=await fetchWithTimeout(url,{headers:{'User-Agent':'Mozilla/5.0','Accept':'application/json,text/plain,*/*','Accept-Language':'ko-KR,ko;q=0.9','Referer':'https://m.stock.naver.com/'},next:{revalidate}} as RequestInit&{next:{revalidate:number}});if(!r.ok){last=`HTTP ${r.status}`;await sleep(200*(i+1));continue}return await r.json()}catch(e){last=e instanceof Error?e.message:'fetch error';await sleep(200*(i+1))}}throw new Error(last||'JSON 수집 실패')}
async function fetchHtmlEuckr(url:string,revalidate=900){const r=await fetchWithTimeout(url,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'ko-KR,ko;q=0.9','Referer':'https://finance.naver.com/'},next:{revalidate}} as RequestInit&{next:{revalidate:number}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());return (r.headers.get('content-type')||'').toLowerCase().includes('utf-8')?b.toString('utf8'):iconv.decode(b,'EUC-KR')}
function pickArray(j:any):any[]{if(Array.isArray(j))return j;for(const k of ['stocks','items','stockList','data'])if(Array.isArray(j?.[k]))return j[k];if(Array.isArray(j?.result?.stocks))return j.result.stocks;if(Array.isArray(j?.result?.items))return j.result.items;return []}
function norm(x:any):UniverseStock|null{const code=String(x?.itemCode??x?.itemcode??x?.stockCode??x?.code??'').match(/\d{6}/)?.[0]||'';const name=String(x?.stockName??x?.name??x?.itemName??'').trim();if(!code||!name)return null;return{name,code,market:'KOSPI',currentPrice:num(x?.closePrice??x?.currentPrice??x?.nowVal??x?.price),changePct:num(x?.fluctuationsRatio??x?.changeRate??x?.changePct??x?.rate),marketCap:num(x?.marketValue??x?.marketCap??x?.marketValueAmount),sector:null,theme:null}}

async function mobileUniverse(){const out:UniverseStock[]=[];for(let page=1;page<=16;page++){const j=await fetchJson(`https://m.stock.naver.com/api/stocks/marketValue/KOSPI?page=${page}&pageSize=100`);const rows=pickArray(j);if(!rows.length)break;for(const x of rows){const s=norm(x);if(s)out.push(s)}if(rows.length<100)break}return [...new Map(out.map(x=>[x.code,x])).values()]}
async function pcUniverse(){const out:UniverseStock[]=[];for(let page=1;page<=30;page++){const html=await fetchHtmlEuckr(`https://finance.naver.com/sise/sise_market_sum.naver?sosok=0&page=${page}`);const $=cheerio.load(html);let count=0;$('table.type_2 tr,table.type2 tr').each((_,tr)=>{const a=$(tr).find('a.tltle,a[href*="/item/main.naver?code="]').first();if(!a.length)return;const code=(a.attr('href')||'').match(/code=(\d{6})/)?.[1];const name=a.text().trim();if(!code||!name)return;const td=$(tr).find('td').map((_,x)=>$(x).text().replace(/\s+/g,' ').trim()).get();out.push({name,code,market:'KOSPI',currentPrice:num(td[2]),changePct:num(td[4]),marketCap:num(td[6]),sector:null,theme:null});count++});if(count===0)break}return [...new Map(out.map(x=>[x.code,x])).values()]}
export async function fetchUniverse(){const errors:string[]=[];let stocks:UniverseStock[]=[];try{stocks=await mobileUniverse();if(stocks.length<500)throw new Error(`mobile ${stocks.length}건`)}catch(e){errors.push(e instanceof Error?e.message:'mobile 오류');stocks=[]}if(stocks.length<500){try{stocks=await pcUniverse()}catch(e){errors.push(e instanceof Error?e.message:'pc 오류')}}if(!stocks.length)throw new Error(`KOSPI 종목목록 수집 실패 · ${errors.join(' / ')}`);return{stocks,errors,sources:[`KOSPI 전체 ${stocks.length}종목`]}}

export function yahooSymbol(code:string,market:'KOSPI'|'KOSDAQ'='KOSPI'){return `${code}.${market==='KOSDAQ'?'KQ':'KS'}`}
async function yahoo(code:string,market:'KOSPI'|'KOSDAQ',interval:'1d'|'30m',period1:number,period2:number){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yahooSymbol(code,market))}?period1=${period1}&period2=${period2}&interval=${interval}&events=history&includeAdjustedClose=true&includePrePost=false`;let last='';for(let a=0;a<3;a++){const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'Mozilla/5.0'},next:{revalidate:interval==='1d'?600:120}} as RequestInit&{next:{revalidate:number}});clearTimeout(t);if(!r.ok){last=`HTTP ${r.status}`;await sleep(250*(a+1));continue}const j=await r.json();const z=j?.chart?.result?.[0];const ts:number[]=z?.timestamp||[];const q=z?.indicators?.quote?.[0]||{};const bars:Bar[]=ts.map((v,i)=>({date:new Date(v*1000).toISOString(),open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i]})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));if(bars.length<10)throw new Error('가격 이력 부족');return bars}catch(e){clearTimeout(t);last=e instanceof Error?e.message:'fetch error';await sleep(250*(a+1))}}throw new Error(last||'Yahoo Finance 수집 실패')}
export async function fetchYahooBars(code:string,marketOrDays:'KOSPI'|'KOSDAQ'|number='KOSPI',daysMaybe=120){const market=typeof marketOrDays==='string'?marketOrDays:'KOSPI';const days=typeof marketOrDays==='number'?marketOrDays:daysMaybe;const p2=Math.floor(Date.now()/1000)+86400;const p1=Math.floor((Date.now()-days*2.2*86400000)/1000);return (await yahoo(code,market,'1d',p1,p2)).slice(-Math.max(days,90))}
export async function fetchYahoo30m(code:string,market:'KOSPI'|'KOSDAQ'='KOSPI'){const p2=Math.floor(Date.now()/1000)+3600;const p1=Math.floor((Date.now()-59*86400000)/1000);return (await yahoo(code,market,'30m',p1,p2)).slice(-700)}

export async function fetchInvestorFlow(code:string){try{const html=await fetchHtmlEuckr(`https://finance.naver.com/item/frgn.naver?code=${code}`,900);const $=cheerio.load(html);const rows:{date:string;inst:number;foreign:number}[]=[];$('table.type2 tr').each((_,tr)=>{const tds=$(tr).find('td').map((_,td)=>$(td).text().replace(/\s+/g,' ').trim()).get();if(tds.length<7||!/^\d{4}\.\d{2}\.\d{2}/.test(tds[0]||''))return;const inst=num(tds[5]||''),foreign=num(tds[6]||'');if(inst!==null&&foreign!==null)rows.push({date:tds[0],inst,foreign})});return rows.slice(0,10)}catch{return null}}
