import * as cheerio from 'cheerio';
import iconv from 'iconv-lite';
export type Market='KOSPI'|'KOSDAQ';
export type UniverseStock={name:string;code:string;market:Market;currentPrice:number|null;changePct:number|null;marketCap:number|null};
export type Bar={date:string;open:number;high:number;low:number;close:number;volume:number};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const num=(v:unknown)=>{if(typeof v==='number')return Number.isFinite(v)?v:null;if(typeof v!=='string')return null;const n=Number(v.replace(/[,+%원\s]/g,''));return Number.isFinite(n)?n:null};
async function timed(url:string,init:RequestInit={},ms=9000){const c=new AbortController();const t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
async function html(url:string){const r=await timed(url,{headers:{'User-Agent':'Mozilla/5.0','Accept-Language':'ko-KR,ko;q=.9','Referer':'https://finance.naver.com/'},next:{revalidate:900}} as RequestInit&{next:{revalidate:number}});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b=Buffer.from(await r.arrayBuffer());return (r.headers.get('content-type')||'').toLowerCase().includes('utf-8')?b.toString('utf8'):iconv.decode(b,'EUC-KR')}
async function pcUniverse(market:Market){const out:UniverseStock[]=[];const sosok=market==='KOSPI'?0:1;for(let page=1;page<=45;page++){const $=cheerio.load(await html(`https://finance.naver.com/sise/sise_market_sum.naver?sosok=${sosok}&page=${page}`));let count=0;$('table.type_2 tr,table.type2 tr').each((_,tr)=>{const a=$(tr).find('a.tltle,a[href*="/item/main.naver?code="]').first();const code=(a.attr('href')||'').match(/code=(\d{6})/)?.[1],name=a.text().trim();if(!code||!name)return;const td=$(tr).find('td').map((_,x)=>$(x).text().replace(/\s+/g,' ').trim()).get();out.push({name,code,market,currentPrice:num(td[2]),changePct:num(td[4]),marketCap:num(td[6])});count++});if(!count)break}return [...new Map(out.map(x=>[x.code,x])).values()]}
export async function fetchUniverse(only?:Market){const markets:Market[]=only?[only]:['KOSPI','KOSDAQ'];const sets=await Promise.all(markets.map(async market=>{try{return{market,stocks:await pcUniverse(market),error:''}}catch(e){return{market,stocks:[] as UniverseStock[],error:e instanceof Error?e.message:'목록 오류'}}}));const stocks=sets.flatMap(x=>x.stocks),errors=sets.filter(x=>x.error).map(x=>`${x.market}: ${x.error}`);if(!stocks.length)throw new Error(`KRX 종목목록 수집 실패 · ${errors.join(' / ')}`);return{stocks,errors,sources:markets.map(m=>`${m} 전체`)}}
export const yahooSymbol=(code:string,market:Market)=>`${code}.${market==='KOSDAQ'?'KQ':'KS'}`;
async function yahoo(code:string,market:Market,interval:'1d'|'30m',p1:number,p2:number){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yahooSymbol(code,market))}?period1=${p1}&period2=${p2}&interval=${interval}&events=history&includeAdjustedClose=true&includePrePost=false`;let last='';for(let a=0;a<3;a++){try{const r=await timed(u,{headers:{'User-Agent':'Mozilla/5.0'},next:{revalidate:interval==='1d'?600:120}} as RequestInit&{next:{revalidate:number}},7000);if(!r.ok){last=`HTTP ${r.status}`;await sleep(220*(a+1));continue}const j=await r.json(),z=j?.chart?.result?.[0],ts:number[]=z?.timestamp||[],q=z?.indicators?.quote?.[0]||{};const bars:Bar[]=ts.map((v,i)=>({date:new Date(v*1000).toISOString(),open:q.open?.[i],high:q.high?.[i],low:q.low?.[i],close:q.close?.[i],volume:q.volume?.[i]})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite));if(bars.length<10)throw new Error('가격 이력 부족');return bars}catch(e){last=e instanceof Error?e.message:'Yahoo 오류';await sleep(220*(a+1))}}throw new Error(last||'Yahoo Finance 수집 실패')}
export async function fetchYahooBars(code:string,market:Market,days=120){const p2=Math.floor(Date.now()/1000)+86400,p1=Math.floor((Date.now()-days*2.3*86400000)/1000);return (await yahoo(code,market,'1d',p1,p2)).slice(-Math.max(days,90))}
export async function fetchYahoo30m(code:string,market:Market){const p2=Math.floor(Date.now()/1000)+3600,p1=Math.floor((Date.now()-59*86400000)/1000);return (await yahoo(code,market,'30m',p1,p2)).slice(-700)}
export async function fetchDailyBars(code:string,market:Market,_preferred:'yahoo'|'naver'='yahoo',days=120){return{bars:await fetchYahooBars(code,market,days),source:'Yahoo Finance'}}
