import type {Bar} from './market';

export type ScanStock={name:string;code:string;market:'KOSDAQ';rank?:number;currentPrice:number|null;changePct:number|null;marketCap:number|null;sector:string|null;theme:string|null;currentVolume:number|null;openPrice:number|null;highPrice:number|null;lowPrice:number|null;quoteDate:string|null};
export type NextDayConfig={lookback:number;priorSpikePct:number;priorVolumeRatio:number;holdPct:number;repeatRisePct:number;todayMinPct:number;todayMaxPct:number;todayVolumeRatio:number;nearHighPct:number;breakoutDistancePct:number;max5DayRisePct:number;maGapPct:number;minPrice:number;minScore:number};
export const defaultConfig:NextDayConfig={lookback:7,priorSpikePct:8,priorVolumeRatio:3.5,holdPct:60,repeatRisePct:4,todayMinPct:0.5,todayMaxPct:9,todayVolumeRatio:1.2,nearHighPct:3,breakoutDistancePct:2.5,max5DayRisePct:22,maGapPct:4,minPrice:1000,minScore:60};
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;
const pct=(a:number,b:number)=>b?((a/b)-1)*100:0;
const sma=(bars:Bar[],n:number,idx=bars.length-1)=>idx+1<n?null:avg(bars.slice(idx-n+1,idx+1).map(b=>b.close));
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function kstParts(){const p=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',hour12:false,hour:'2-digit',minute:'2-digit',weekday:'short'}).formatToParts(new Date());return {hour:Number(p.find(x=>x.type==='hour')?.value||0),minute:Number(p.find(x=>x.type==='minute')?.value||0),weekday:p.find(x=>x.type==='weekday')?.value||''};}
export function sessionProjectionFactor(){const {hour,minute,weekday}=kstParts();if(['Sat','Sun'].includes(weekday))return 1;const now=hour*60+minute,start=540,end=930;if(now<=start)return 1.6;if(now>=end)return 1;return clamp(1/clamp((now-start)/(end-start),0.55,1),1,1.6);}
function liveBar(stock:ScanStock,prev:Bar):Bar{const close=stock.currentPrice??prev.close;const previous=stock.changePct!==null&&stock.changePct>-99?close/(1+stock.changePct/100):prev.close;const open=stock.openPrice??previous,high=stock.highPrice??Math.max(open,close,previous),low=stock.lowPrice??Math.min(open,close,previous);return {date:stock.quoteDate||new Date().toISOString().slice(0,10),open,high,low,close,volume:stock.currentVolume??0};}
export function scoreNextDay(stock:ScanStock,bars:Bar[],cfg:NextDayConfig){
  const history=[...bars];if(stock.quoteDate&&history.at(-1)?.date===stock.quoteDate)history.pop();if(history.length<70)throw new Error('70거래일 이상 가격이력 필요');const today=liveBar(stock,history.at(-1)!);const last=history.length-1,start=Math.max(21,last-cfg.lookback+1);
  let eventIdx=-1,eventDayPct=-999,eventVolRatio=0,eventStrength=-999;for(let i=start;i<=last;i++){const r=pct(history[i].close,history[i-1].close),av=avg(history.slice(i-20,i).map(x=>x.volume)),vr=av?history[i].volume/av:0,strength=Math.max(0,r)*1.5+Math.min(vr,8)*3;if(strength>eventStrength){eventStrength=strength;eventIdx=i;eventDayPct=r;eventVolRatio=vr;}}
  const eventBase=eventIdx>0?history[eventIdx-1].close:history[last].close,eventClose=eventIdx>=0?history[eventIdx].close:eventBase,eventGain=Math.max(1,eventClose-eventBase),hold=clamp((today.close-eventBase)/eventGain*100,-100,180);let repeatMax=-999;for(let i=Math.max(eventIdx+1,1);i<=last;i++)repeatMax=Math.max(repeatMax,pct(history[i].close,history[i-1].close));
  const avg20Vol=avg(history.slice(-20).map(x=>x.volume)),rawVolumeRatio=avg20Vol?(today.volume||0)/avg20Vol:0,projectionFactor=sessionProjectionFactor(),projectedVolumeRatio=rawVolumeRatio*projectionFactor,todayPct=stock.changePct??pct(today.close,history[last].close),nearHigh=today.high>0?(today.high-today.close)/today.high*100:99,high20=Math.max(...history.slice(-20).map(x=>x.high)),breakoutDistance=(high20-today.close)/high20*100,ret5=pct(today.close,history[Math.max(0,last-4)].close),ma5=sma([...history,today],5)!,ma5p=sma(history,5,last-3)!,ma20=sma([...history,today],20)!,ma20p=sma(history,20,last-8)!,ma60=sma([...history,today],60)!,maGap=Math.abs(ma20-ma60)/ma60*100,ma20Distance=(today.close/ma20-1)*100;
  let score=0;const reasons:string[]=[],warnings:string[]=[];const add=(pts:number,ok:boolean,text:string)=>{if(ok){score+=pts;reasons.push(text);}};add(15,eventDayPct>=cfg.priorSpikePct,`최근 ${cfg.lookback}일 내 +${eventDayPct.toFixed(1)}% 선행 상승`);add(15,eventVolRatio>=cfg.priorVolumeRatio,`선행일 거래량 ${eventVolRatio.toFixed(1)}배`);add(15,hold>=cfg.holdPct,`선행 상승분 ${hold.toFixed(0)}% 유지`);add(10,repeatMax>=cfg.repeatRisePct,`선행 후 재상승 최대 +${Math.max(0,repeatMax).toFixed(1)}%`);add(10,todayPct>=cfg.todayMinPct&&todayPct<=cfg.todayMaxPct,`당일 +${todayPct.toFixed(1)}%로 추격 과열 전 구간`);add(15,projectedVolumeRatio>=cfg.todayVolumeRatio,`당일 예상 거래량 ${projectedVolumeRatio.toFixed(1)}배`);add(10,nearHigh<=cfg.nearHighPct,`현재가가 당일 고가와 ${nearHigh.toFixed(1)}% 차이`);add(5,breakoutDistance<=cfg.breakoutDistancePct&&breakoutDistance>=-4,`20일 고점과 ${breakoutDistance.toFixed(1)}% 거리`);add(5,ma5>ma5p&&ma20>ma20p&&maGap<=cfg.maGapPct,`5·20일선 상승, 20/60 간격 ${maGap.toFixed(1)}%`);
  let penalty=0;if(todayPct>cfg.todayMaxPct){penalty-=18;warnings.push(`당일 +${todayPct.toFixed(1)}%로 이미 과열`);}if(ret5>cfg.max5DayRisePct){penalty-=12;warnings.push(`5일 +${ret5.toFixed(1)}%로 단기 과열`);}if(ma20Distance>18){penalty-=8;warnings.push(`20일선 위 ${ma20Distance.toFixed(1)}% 이격`);}if((stock.currentPrice||0)<cfg.minPrice){penalty-=20;warnings.push('최소 주가 조건 미달');}score=clamp(score+penalty,0,100);const stage=score>=85?'A+ 최우선 감시':score>=75?'A 집중 감시':score>=65?'B+ 후보':score>=cfg.minScore?'B 조건부':'관찰',pass=score>=cfg.minScore&&todayPct>=cfg.todayMinPct&&todayPct<=cfg.todayMaxPct&&(stock.currentPrice||0)>=cfg.minPrice;
  return {score:Math.round(score*10)/10,stage,pass,penalty,reasons,warnings,metrics:{eventDate:eventIdx>=0?history[eventIdx].date:null,eventDayPct,eventVolRatio,holdPct:hold,repeatMaxPct:Math.max(0,repeatMax),todayPct,rawVolumeRatio,projectedVolumeRatio,nearHighPct:nearHigh,breakoutDistancePct:breakoutDistance,ret5,maGapPct:maGap,ma20DistancePct:ma20Distance,projectionFactor}};
}
