import { NextResponse } from 'next/server';
import { fetchUniverse, fetchYahooBars, type Bar, type UniverseStock } from '@/lib/market';

export const runtime='nodejs';
export const dynamic='force-dynamic';
export const maxDuration=60;

const avg=(a:number[])=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0;
const med=(a:number[])=>{if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2};
const clamp=(v:number,a=0,b=100)=>Math.max(a,Math.min(b,v));
const pct=(a:number,b:number)=>b?(a/b-1)*100:0;
const sma=(b:Bar[],n:number,i=b.length-1)=>i+1<n?null:avg(b.slice(i-n+1,i+1).map(x=>x.close));
const localMinima=(v:number[])=>{const r:number[]=[];for(let i=2;i<v.length-2;i++)if(v[i]<=v[i-1]&&v[i]<=v[i+1]&&v[i]<=v[i-2]&&v[i]<=v[i+2])r.push(i);return r};

function rets(b:Bar[]){const i=b.length-1,c=b[i].close,r=(n:number)=>i-n>=0?pct(c,b[i-n].close):0;return {r1:r(1),r3:r(3),r5:r(5),r10:r(10),r20:r(20)}}
function volRatio(b:Bar[],i=b.length-1){if(i<20)return 0;const base=avg(b.slice(i-20,i).map(x=>x.volume));return base?b[i].volume/base:0}
function rsi14(b:Bar[]){const i=b.length-1;if(i<15)return 50;let g=0,l=0;for(let j=i-13;j<=i;j++){const d=b[j].close-b[j-1].close;if(d>=0)g+=d;else l-=d}if(!l)return 100;const rs=(g/14)/(l/14);return 100-100/(1+rs)}
function ema(v:number[],p:number){if(!v.length)return [];const k=2/(p+1),o=[v[0]];for(let i=1;i<v.length;i++)o.push(v[i]*k+o[i-1]*(1-k));return o}
function macdHist(b:Bar[]){const c=b.slice(-90).map(x=>x.close),e12=ema(c,12),e26=ema(c,26),m=c.map((_,i)=>e12[i]-e26[i]),s=ema(m,9);return (m.at(-1)||0)-(s.at(-1)||0)}
function obvSlope(b:Bar[]){const x=b.slice(-22);if(x.length<8)return 0;let obv=0;const a:number[]=[];for(let i=1;i<x.length;i++){obv+=x[i].close>x[i-1].close?x[i].volume:x[i].close<x[i-1].close?-x[i].volume:0;a.push(obv)}const A=avg(a.slice(-3)),B=avg(a.slice(-8,-5)),d=Math.max(1,avg(a.map(v=>Math.abs(v))));return (A-B)/d}

function v5Score(b:Bar[]){const i=b.length-1;if(i<65)return null;const r=rets(b),vr=volRatio(b);let vs=0;if(vr>=5)vs+=15;else if(vr>=3)vs+=11;else if(vr>=2)vs+=7;else if(vr>=1.5)vs+=4;if(vr>=2&&r.r1<3)vs+=4;if(vr>=3&&r.r1>=-2&&r.r1<=2.5)vs+=2;let repeat=0;for(let j=Math.max(20,i-4);j<=i;j++)if(volRatio(b,j)>=1.5)repeat++;if(repeat>=2)vs+=Math.min(4,repeat-1);let obv=0,obs:number[]=[];for(let j=Math.max(1,i-20);j<=i;j++){obv+=b[j].close>b[j-1].close?b[j].volume:b[j].close<b[j-1].close?-b[j].volume:0;obs.push(obv)}if(obs.length>=6&&obs.at(-1)!>obs.at(-6)!)vs+=2;vs=Math.min(25,vs);
 const m5=sma(b,5)!,m5p=sma(b,5,i-3)!,m20=sma(b,20)!,m20p=sma(b,20,i-8)!,m60=sma(b,60)!;let cs=0;if(m5>m5p)cs+=3;if(m20>m20p)cs+=2;const gap=Math.abs(m20-m60)/m60*100;if(gap<=2.5)cs+=3;const p20=sma(b,20,i-5)!,p60=sma(b,60,i-5)!,pg=(p60-p20)/p60*100,ng=(m60-m20)/m60*100;if(m20<m60&&ng>0&&ng<3.5&&ng<pg)cs+=2;const closes=b.slice(i-45,i+1).map(x=>x.close),mins=localMinima(closes);if(mins.length>=2){const a=closes[mins.at(-2)!],c=closes[mins.at(-1)!];if(Math.abs(a-c)/Math.min(a,c)<.04)cs+=2;else if(c>a)cs+=1}const hi=Math.max(...b.slice(i-20,i).map(x=>x.high)),dist=(hi-b[i].close)/hi*100,av=avg(b.slice(i-20,i).map(x=>x.volume));if(dist>=0&&dist<=2.5&&b[i].volume>av*1.2)cs+=2;cs=Math.min(15,cs);
 let quiet=10;if(r.r1>=3)quiet-=Math.min(6,(r.r1-3)*1.5);if(r.r5>=8)quiet-=Math.min(6,(r.r5-8)*.8);quiet=clamp(quiet,0,10);let ma=0;if(m5>m5p)ma+=3;if(m20>m20p)ma+=3;if(b[i].close>=m5&&m5>=m20)ma+=2;if(cs>=5)ma+=2;ma=Math.min(10,ma);let conv=gap<=1.5?8:gap<=2.5?6:gap<=4?4:gap<=6?2:0;let mom=0,rr=rsi14(b);if(rr>=45&&rr<=67)mom+=2;if(macdHist(b)>0)mom+=2;if(obvSlope(b)>0)mom+=2;if(rr<72)mom+=1;mom=Math.min(7,mom);let run=0;if(r.r1>=10)run-=30;else if(r.r1>=7)run-=22;else if(r.r1>=5)run-=12;else if(r.r1>=3)run-=5;if(r.r5>=20)run-=15;else if(r.r5>=12)run-=9;let risk=0;if(rr>=75)risk+=20;if(b[i].close>m20*1.12)risk+=18;if(vr>=4&&b[i].close<m20)risk+=25;if(m5<m5p&&vr>=2)risk+=18;if(r.r1>=7)risk+=20;risk=Math.min(100,risk);const score=vs/25*20+quiet+ma+conv+mom+run-Math.round(risk*.1);return {score,eligible:r.r1<5&&r.r3<10&&r.r5<12};}

function v6Score(b:Bar[]){const i=b.length-1;if(i<65)return null;const cur=b[i],prev=b[i-1],vr=volRatio(b,i),day=pct(cur.close,prev.close),range=Math.max(cur.high-cur.low,1e-9),cp=(cur.close-cur.low)/range;let a=0;if(vr>=3)a+=13;else if(vr>=2)a+=10;else if(vr>=1.5)a+=7;else if(vr>=1.2)a+=4;if(vr>=1.5&&day>-2&&day<4)a+=6;if(vr>=1.3&&cp>=.7)a+=4;let absorb=0;for(let j=Math.max(20,i-4);j<=i;j++){const v=volRatio(b,j),d=pct(b[j].close,b[j-1].close),rg=Math.max(b[j].high-b[j].low,1e-9),c=(b[j].close-b[j].low)/rg;if(v>=1.3&&d>-3&&d<5&&c>=.55)absorb++}if(absorb>=2)a+=Math.min(4,absorb);const rr=avg(b.slice(i-4,i+1).map(x=>(x.high-x.low)/Math.max(x.close,1))),pr=avg(b.slice(i-20,i-5).map(x=>(x.high-x.low)/Math.max(x.close,1))),rv=avg(b.slice(i-4,i+1).map(x=>x.volume)),pv=avg(b.slice(i-20,i-5).map(x=>x.volume));if(pr>0&&pv>0&&rr<pr*.92&&rv>pv*1.2)a+=3;a=Math.min(30,a);
 let t=0;const m5=sma(b,5,i)!,m5p=sma(b,5,i-3)!,m20=sma(b,20,i)!,m20p=sma(b,20,i-8)!,m60=sma(b,60,i)!;if(m5>m5p)t+=4;if(m20>m20p)t+=5;const old=Math.min(...b.slice(i-30,i-15).map(x=>x.low)),nw=Math.min(...b.slice(i-14,i+1).map(x=>x.low));if(nw>old*1.01)t+=5;const gap=Math.abs(m20-m60)/m60*100;if(gap<=3)t+=4;if(cur.close>=m20)t+=3;const closes=b.slice(i-45,i+1).map(x=>x.close),mins=localMinima(closes);if(mins.length>=2){const x=closes[mins.at(-2)!],y=closes[mins.at(-1)!];if(Math.abs(x-y)/Math.max(Math.min(x,y),1)<.045)t+=4;else if(y>x)t+=3}t=Math.min(25,t);
 let s=0,obv=0,os:number[]=[];for(let j=Math.max(1,i-20);j<=i;j++){obv+=b[j].close>b[j-1].close?b[j].volume:b[j].close<b[j-1].close?-b[j].volume:0;os.push(obv)}if(os.length>=6&&os.at(-1)!>os.at(-6)!)s+=4;const rec=avg(b.slice(i-4,i+1).map(x=>x.volume)),base=avg(b.slice(i-24,i-5).map(x=>x.volume)),r5=pct(cur.close,b[i-5].close);if(base>0&&rec/base>=1.3&&r5>-3&&r5<9)s+=4;if(vr>=1.4&&day<=1.5&&cp>=.6)s+=2;s=Math.min(10,s);const r=rets(b);let p=0;if(r.r1>=8)p-=6;if(r.r3>=12)p-=6;if(r.r5>=18)p-=5;if(r.r20>=30)p-=3;return {score:a+t+s+Math.max(-20,p),eligible:true};}

function indicators(b:Bar[]){return b.map((x,i)=>{const ret=i?pct(x.close,b[i-1].close):null,ma=(n:number)=>i>=n-1?avg(b.slice(i-n+1,i+1).map(z=>z.close)):null,base=i>=20?avg(b.slice(i-20,i).map(z=>z.volume)):0;return {...x,ret,ma5:ma(5),ma20:ma(20),ma60:ma(60),vr:base>0?x.volume/base:null}})}
function nextdayScore(b:Bar[]){const a=indicators(b),i=a.length-1;if(i<65)return null;const p={lookback:15,spikePct:7,spikeVolRatio:2.5,pullbackMaxDays:6,ma20Distance:8,maxTodayRise:6};const last=a[i];let score=0,pen=0;const spikes:number[]=[];for(let j=Math.max(20,i-p.lookback);j<=i;j++)if((a[j].ret??-999)>=p.spikePct&&(a[j].vr??0)>=p.spikeVolRatio)spikes.push(j);const si=spikes.length?spikes.at(-1)!:-1;const abnormal=a.slice(Math.max(20,i-5),i+1).filter(x=>(x.vr??0)>=1.5).length;if(si>=0){const s=a[si];score+=10;const vr=s.vr??0;score+=vr>=5?15:vr>=3?12:vr>=2.2?9:6;if(spikes.length>=2)score+=3;const age=i-si,pb=pct(last.close,s.close);if(age>=1&&age<=p.pullbackMaxDays&&pb>=-28&&pb<=4)score+=10;const after=a.slice(si+1,i+1),con=after.length?avg(after.map(x=>x.volume))/Math.max(1,s.volume):null;if(con!==null&&con<=.65)score+=6;else if(con!==null&&con<=.85)score+=3}else if(abnormal>=2)score+=9;if((last.vr??0)>=2&&Math.abs(last.ret??0)<4)score+=8;else if((last.vr??0)>=1.5)score+=4;const g=last.ma20?pct(last.close,last.ma20):null;if(g!==null&&Math.abs(g)<=3)score+=8;else if(g!==null&&Math.abs(g)<=p.ma20Distance)score+=5;const g5=last.ma5?pct(last.close,last.ma5):null;if(g5!==null&&Math.abs(g5)<=2.5)score+=4;if(last.ma20&&a[i-8].ma20&&last.ma20>=a[i-8].ma20!)score+=3;if(last.ma5&&a[i-3].ma5&&last.ma5>a[i-3].ma5!)score+=3;const closes=a.slice(Math.max(0,i-24),i+1).map(x=>x.close),mins=localMinima(closes);if(mins.length>=2){const x=closes[mins.at(-2)!],y=closes[mins.at(-1)!];if(Math.abs(x-y)/Math.min(x,y)<=.055)score+=4;else if(y>x)score+=3}else if(mins.length)score+=1;const td=last.ret??0;if(td<=3&&td>=-5)score+=6;else if(td<=p.maxTodayRise)score+=3;else pen+=td>=10?18:10;const r5=i>=5?pct(last.close,a[i-5].close):0;if(r5>=20)pen+=10;if(g!==null&&g>15)pen+=8;return {score:Math.max(0,Math.min(70,Math.round(score-pen))),eligible:true};}

function thirdDayScore(b:Bar[]){const a=indicators(b),last=a.length-1;if(last<25)return null;const p={lookback:20,spikePct:7,vr:3,waitDays:3,maxAfterSpike:15,ma20Distance:10,pullbackMin:-25,pullbackMax:8};const start=Math.max(20,last-p.lookback+1),spikes:number[]=[];for(let i=start;i<last;i++)if((a[i].ret??-999)>=p.spikePct&&(a[i].vr??0)>=p.vr)spikes.push(i);for(const si of [...spikes].reverse()){if(last-si>p.maxAfterSpike)continue;if(!(a[last].ma5&&a[last].close<a[last].ma5!))continue;const minPivot=Math.max(si+1,last-(p.waitDays+3));let first=-1,age=0;for(let j=last-1;j>=minPivot;j--){const seq=a.slice(j,last+1),down=seq.slice(1).every(x=>(x.ret??0)<=1),has=seq.slice(1).some(x=>(x.ret??0)<-.15),pivot=(a[j].ret??-999)>=-.2&&!!a[j].ma5&&a[j].close<=a[j].ma5!*1.06,near=seq.filter(x=>x.ma5&&x.close<=x.ma5!*1.035).length>=Math.max(1,seq.length-1);if(pivot&&down&&has&&near){first=j;age=last-j+1;break}}if(first<0)continue;const pb=pct(a[last].close,a[si].close),g=a[last].ma20?pct(a[last].close,a[last].ma20!):null,ok=pb>=p.pullbackMin&&pb<=p.pullbackMax&&(g===null||Math.abs(g)<=p.ma20Distance),stage=age===p.waitDays&&ok?'buy':age<p.waitDays?'wait':age>p.waitDays&&age<=p.waitDays+2?'late':'none',score=clamp(Math.round(55+Math.min(20,(a[si].vr??0)*2)+Math.min(12,(a[si].ret??0)*.7)+Math.max(0,8-Math.abs(g??8))-(age>p.waitDays?8:0)),0,100);return {score,eligible:stage==='buy'}}return null;}

function pivots(rows:Bar[]){const n=rows.length,w=n<35?1:n<90?2:3,p:{type:'low'|'high';idx:number;price:number}[]=[];for(let i=w;i<n-w;i++){const c=rows[i].close,ns:number[]=[];for(let j=i-w;j<=i+w;j++)if(j!==i)ns.push(rows[j].close);if(ns.every(x=>c<=x)&&ns.some(x=>c<x))p.push({type:'low',idx:i,price:c});if(ns.every(x=>c>=x)&&ns.some(x=>c>x))p.push({type:'high',idx:i,price:c})}const z= [] as typeof p;for(const x of p){const l=z.at(-1);if(!l||l.type!==x.type)z.push(x);else if((x.type==='low'&&x.price<l.price)||(x.type==='high'&&x.price>l.price))z[z.length-1]=x}return z}
function lowPointScore(b:Bar[]){const rows=b.slice(-240);if(rows.length<60)return null;const p=pivots(rows),lo=p.filter(x=>x.type==='low'),hi=p.filter(x=>x.type==='high');if(lo.length<2||hi.length<2)return null;const L=lo.slice(-5),H=hi.slice(-5),support=med(L.map(x=>x.price)),res=med(H.map(x=>x.price));if(!(support>0&&res>support))return null;const disp=(a:number[],c:number)=>med(a.map(v=>Math.abs(v-c)/c*100)),ld=disp(L.map(x=>x.price),support),hd=disp(H.map(x=>x.price),res),amp=pct(res,support),cur=rows.at(-1)!.close,d=pct(cur,support),pos=(cur-support)/(res-support),alt=Math.max(0,p.length-1),r5=rows.length>6?pct(cur,rows.at(-6)!.close):0,gaps:number[]=[];for(let i=1;i<lo.length;i++)gaps.push(lo[i].idx-lo[i-1].idx);const ga=avg(gaps),gd=ga?med(gaps.map(g=>Math.abs(g-ga)/ga*100)):50,prox=clamp(100-Math.max(d,0)/7*100),rep=clamp(100-ld*7-hd*3),cyc=clamp(25+alt*8-gd*.45),am=clamp((amp-5)*4.2),score=clamp(Math.round(prox*.4+rep*.28+cyc*.17+am*.15+(r5<0?8:0)));const ok=d>=-5&&d<=7&&pos<=.38&&amp>=7&&ld<=12&&hd<=20&&alt>=4;return {score,eligible:ok};}
function lowRetestScore(b:Bar[]){const rows=b.slice(-60),n=rows.length;if(n<20)return null;const c={riseMin:10,riseMax:30,retMin:-5,retMax:10,lowPeakGap:1,peakNowGap:1};const cur=rows[n-1],lastPeak=n-1-c.peakNowGap;let best:{ret:number;rise:number}|null=null,rmin=Infinity;for(let i=0;i<=lastPeak-c.lowPeakGap;i++){const low=rows[i].low;rmin=Math.min(rmin,low);if(low>rmin*1.000001)continue;let peak=-Infinity,pi=-1;for(let j=i+c.lowPeakGap;j<=lastPeak;j++)if(rows[j].high>peak){peak=rows[j].high;pi=j}if(pi<0)continue;let bad=false;for(let k=i+1;k<=pi;k++)if(rows[k].low<low){bad=true;break}if(bad)continue;const rise=pct(peak,low),ret=pct(cur.close,low);if(rise<c.riseMin||rise>c.riseMax||ret<c.retMin||ret>c.retMax)continue;if(!best||Math.abs(ret)<Math.abs(best.ret))best={ret,rise}}if(!best)return null;return {score:100-Math.abs(best.ret)*4+Math.min(best.rise,30)*.3,eligible:true};}

type StockData={s:UniverseStock;bars:Bar[]};
type ModelKey='preSpikeV5'|'accumV6'|'nextdayEarly'|'ma5ThirdDay'|'lowPointCycle'|'lowRetest';
const models:Record<ModelKey,(b:Bar[])=>{score:number;eligible:boolean}|null>={preSpikeV5:v5Score,accumV6:v6Score,nextdayEarly:nextdayScore,ma5ThirdDay:thirdDayScore,lowPointCycle:lowPointScore,lowRetest:lowRetestScore};

export async function GET(req:Request){
 const u=new URL(req.url), start=u.searchParams.get('start')||'2026-08-25', end=u.searchParams.get('end')||'2026-09-24', kp=Math.min(500,Math.max(50,Number(u.searchParams.get('kospi')||300))), kq=Math.min(300,Math.max(50,Number(u.searchParams.get('kosdaq')||200)));
 const uni=await fetchUniverse();const ks=uni.stocks.filter(x=>x.market==='KOSPI').slice(0,kp),kqs=uni.stocks.filter(x=>x.market==='KOSDAQ').slice(0,kq),stocks=[...ks,...kqs];const data:StockData[]=[];let errors=0;
 for(let i=0;i<stocks.length;i+=25){const z=await Promise.all(stocks.slice(i,i+25).map(async s=>{try{return {s,bars:await fetchYahooBars(s.code,s.market,340)}}catch{return null}}));for(const x of z)if(x)data.push(x);else errors++;}
 const dateSet=new Set<string>();for(const d of data)for(const b of d.bars)if(b.date>=start&&b.date<=end)dateSet.add(b.date);const dates=[...dateSet].sort();
 const daily:Record<ModelKey,{date:string;ret1:number;ret5:number|null;n:number;names:string[]}[]>={preSpikeV5:[],accumV6:[],nextdayEarly:[],ma5ThirdDay:[],lowPointCycle:[],lowRetest:[]};
 for(const date of dates){for(const key of Object.keys(models) as ModelKey[]){const cand:{score:number;r1:number;r5:number|null;name:string}[]=[];for(const d of data){const idx=d.bars.findIndex(x=>x.date===date);if(idx<65||idx>=d.bars.length-1)continue;const slice=d.bars.slice(0,idx+1),sig=models[key](slice);if(!sig||!sig.eligible)continue;const r1=pct(d.bars[idx+1].close,d.bars[idx].close),r5=idx+5<d.bars.length?pct(d.bars[idx+5].close,d.bars[idx].close):null;cand.push({score:sig.score,r1,r5,name:d.s.name})}cand.sort((a,b)=>b.score-a.score);const top=cand.slice(0,5);const p1=top.length?avg(top.map(x=>x.r1)):0,valid5=top.filter(x=>x.r5!==null);const p5=valid5.length?avg(valid5.map(x=>x.r5 as number)):null;daily[key].push({date,ret1:p1,ret5:p5,n:top.length,names:top.map(x=>x.name)})}}
 const summary:any={};for(const key of Object.keys(daily) as ModelKey[]){const ds=daily[key],r1=ds.map(x=>x.ret1),r5=ds.filter(x=>x.ret5!==null).map(x=>x.ret5 as number);let eq=1,peak=1,mdd=0;for(const r of r1){eq*=1+r/100;peak=Math.max(peak,eq);mdd=Math.min(mdd,(eq/peak-1)*100)}summary[key]={days:ds.length,activeDays:ds.filter(x=>x.n>0).length,avgPicks:+avg(ds.map(x=>x.n)).toFixed(2),avgNextDay:+avg(r1).toFixed(3),compoundedNextDay:+((eq-1)*100).toFixed(2),winDayRate:+(ds.length?ds.filter(x=>x.ret1>0).length/ds.length*100:0).toFixed(1),mdd:+mdd.toFixed(2),avg5Day:+(r5.length?avg(r5):0).toFixed(3),recent:ds.slice(-5)}}
 return NextResponse.json({ok:true,start,end,universeRequested:stocks.length,universeLoaded:data.length,errors,dates:dates.length,method:'same-day close signal -> next close; top5 equal weight; 5d auxiliary; no future data in scoring; price/volume replay only',summary});
}
